import { computed, ref } from 'vue';
import de from './locales/de';
import en from './locales/en';
import ru from './locales/ru';
import uk from './locales/uk';

export type Locale = 'de' | 'en' | 'ru' | 'uk';
const storedLocale = localStorage.getItem('lookdo-locale');
export const locale = ref<Locale>((['de', 'en', 'ru', 'uk'].includes(storedLocale || '') ? storedLocale : 'de') as Locale);

const messages: Record<Locale, Record<string, string>> = { de, en, ru, uk };

Object.assign(messages.ru, {
    noTemplate: 'Точного совпадения нет — выбран универсальный шаблон. Его можно изменить позже.',
    heroTagline: 'СМОТРИ. ДЕЛАЙ.',
    heroBenefitBrand: 'Ваш бренд и домен', heroBenefitFast: 'Быстрый старт за 15 минут', heroBenefitSafe: 'Данные в безопасности',
    howShow: 'Клиент показывает задачу', howPhone: 'Оставляет телефон', howReceive: 'Вы получаете заявку', howReply: 'Отвечаете и договариваетесь',
    audienceAuto: 'Автосервис', audienceDoors: 'Установка дверей', audienceConstruction: 'Ремонт и строительство', audienceAppliance: 'Бытовая техника', audienceFurniture: 'Мебель', audienceGarden: 'Сад и участок', audienceCleaning: 'Уборка',
    benefitDomainTitle: 'Собственный домен', benefitMediaTitle: 'Фото и видео заявки', benefitPushTitle: 'Push-уведомления', benefitReviewTitle: 'Отзывы и До/После',
    audienceBrows:'Уход за бровями', audienceBeauty:'Красота и уход', bookingTitle:'Онлайн-запись', bookingText:'Услуги, свободное время, напоминания и повторные визиты.', socialTitle:'Контент и связь', socialText:'Подготовка публикаций и переход в реально подключённые каналы.', appAddress:'Адрес приложения', appAddressHelp:'Необязательно. Если оставить пустым, LOOKDO создаст адрес из названия бизнеса.', heroProduct:'Помощник для мастера, который работает сам на себя.', heroText:'Клиент отправляет фото или видео задачи — мастер получает понятную заявку и может сразу ответить.', customerAppTitle:'Чем вам помочь?', customerAppText:'Отправьте фото или видео — мастер получит понятную заявку.', sendPhotoVideo:'Отправить фото или видео', masterWorkspace:'Рабочий кабинет', newRequests:'Новые заявки', inProgress:'В работе', completed:'Выполнено', incomingRequests:'Новые заявки', viewAll:'Смотреть все', phoneMessages:'Сообщения', phoneHome:'Главная',
    check:'Проверить', describeActivityFirst:'Сначала опишите деятельность.', activityAutoHint:'Напишите не менее четырёх слов — LOOKDO сразу начнёт подбор.', activityWaiting:'Готовим подбор шаблона…', templateFound:'Подходящие шаблоны найдены. Выберите вариант.', checkAgain:'Проверить ещё раз', showTemplate:'Показать приложение', templatePreview:'Предпросмотр приложения', templateReady:'Визуальная заявка', yourTemplateReady:'Вот как будет выглядеть ваше приложение', templateChangesLive:'После подтверждения ИИ адаптирует подписи, кнопки, вопросы и фотографии под вашу специализацию.', templateConfirmText:'Это основа приложения. После регистрации LOOKDO создаст индивидуальный вариант по вашему описанию, а базовый шаблон останется безопасной резервной версией.', changeActivity:'Изменить деятельность', currency:'Валюта', perYear:'/ год', save:'Экономия', dictate:'Продиктовать', stopRecording:'Остановить', transcribing:'Распознаём…', voiceHint:'Можно написать или продиктовать до 60 секунд. После распознавания шаблон подберётся автоматически.', microphoneUnavailable:'Браузер не дал доступ к микрофону. Разрешите микрофон или введите текст.',
});
Object.assign(messages.de, {
    noTemplate: 'Kein exakter Treffer – die universelle Vorlage wurde gewählt. Sie kann später geändert werden.',
    heroTagline: 'SCHAU. MACH.',
    heroBenefitBrand: 'Ihre Marke und Domain', heroBenefitFast: 'Start in 15 Minuten', heroBenefitSafe: 'Sichere Daten',
    howShow: 'Kunde zeigt die Aufgabe', howPhone: 'Hinterlässt die Nummer', howReceive: 'Sie erhalten die Anfrage', howReply: 'Sie antworten direkt',
    audienceAuto: 'Autoservice', audienceDoors: 'Türmontage', audienceConstruction: 'Bau & Renovierung', audienceAppliance: 'Haushaltsgeräte', audienceFurniture: 'Möbel', audienceGarden: 'Garten', audienceCleaning: 'Reinigung',
    benefitDomainTitle: 'Eigene Domain', benefitMediaTitle: 'Foto- und Videoanfragen', benefitPushTitle: 'Push-Benachrichtigungen', benefitReviewTitle: 'Bewertungen & Vorher/Nachher',
    audienceBrows:'Augenbrauenpflege', audienceBeauty:'Beauty & Pflege', bookingTitle:'Online-Termine', bookingText:'Leistungen, freie Zeiten, Erinnerungen und Wiederbesuche.', socialTitle:'Inhalte & Kontakt', socialText:'Beiträge vorbereiten und zu tatsächlich verbundenen Kanälen wechseln.', appAddress:'App-Adresse', appAddressHelp:'Optional. Ohne Eingabe erzeugt LOOKDO die Adresse aus dem Betriebsnamen.', heroProduct:'Der Helfer für Handwerker, die selbstständig arbeiten.', heroText:'Der Kunde sendet ein Foto oder Video seiner Aufgabe – der Handwerker erhält eine klare Anfrage und kann sofort antworten.', customerAppTitle:'Wobei brauchen Sie Hilfe?', customerAppText:'Senden Sie ein Foto oder Video – der Handwerker erhält eine klare Anfrage.', sendPhotoVideo:'Foto oder Video senden', masterWorkspace:'Arbeitsbereich', newRequests:'Neue Anfragen', inProgress:'In Arbeit', completed:'Erledigt', incomingRequests:'Neue Anfragen', viewAll:'Alle anzeigen', phoneMessages:'Nachrichten', phoneHome:'Startseite',
    check:'Prüfen', describeActivityFirst:'Beschreiben Sie zuerst Ihre Tätigkeit.', activityAutoHint:'Schreiben Sie mindestens vier Wörter – LOOKDO startet dann automatisch.', activityWaiting:'Vorlagen werden vorbereitet…', templateFound:'Passende Vorlagen wurden gefunden. Bitte wählen Sie.', checkAgain:'Erneut prüfen', showTemplate:'App anzeigen', templatePreview:'App-Vorschau', templateReady:'Visuelle Anfrage', yourTemplateReady:'So wird Ihre App aussehen', templateChangesLive:'Nach der Bestätigung passt die KI Beschriftungen, Schaltflächen, Fragen und Fotos an Ihre Spezialisierung an.', templateConfirmText:'Dies ist die sichere Grundlage. Nach der Registrierung erstellt LOOKDO daraus Ihre individuelle Variante.', changeActivity:'Tätigkeit ändern', currency:'Währung', perYear:'/ Jahr', save:'Sie sparen', dictate:'Diktieren', stopRecording:'Aufnahme stoppen', transcribing:'Wird erkannt…', voiceHint:'Schreiben oder bis zu 60 Sekunden diktieren. Danach startet die Vorlagensuche automatisch.', microphoneUnavailable:'Der Browser hat den Mikrofonzugriff nicht erlaubt. Bitte freigeben oder Text eingeben.',
});
Object.assign(messages.en, {
    noTemplate: 'No exact match — the universal template is selected. You can change it later.',
    heroTagline: 'LOOK. DO.',
    heroBenefitBrand: 'Your brand and domain', heroBenefitFast: 'Launch in 15 minutes', heroBenefitSafe: 'Secure data',
    howShow: 'Customer shows the task', howPhone: 'Leaves a phone number', howReceive: 'You receive the request', howReply: 'You reply and agree',
    audienceAuto: 'Auto service', audienceDoors: 'Door installation', audienceConstruction: 'Renovation & construction', audienceAppliance: 'Appliances', audienceFurniture: 'Furniture', audienceGarden: 'Garden', audienceCleaning: 'Cleaning',
    benefitDomainTitle: 'Custom domain', benefitMediaTitle: 'Photo and video requests', benefitPushTitle: 'Push notifications', benefitReviewTitle: 'Reviews & Before/After',
    audienceBrows:'Brow care', audienceBeauty:'Beauty & care', bookingTitle:'Online booking', bookingText:'Services, available times, reminders and repeat visits.', socialTitle:'Content & contact', socialText:'Prepare posts and open channels the business actually connected.', appAddress:'App address', appAddressHelp:'Optional. If left blank, LOOKDO creates it from the business name.', heroProduct:'The helper for tradespeople who work on their own.', heroText:'The customer sends a photo or video of the job – the tradesperson receives a clear request and can reply right away.', customerAppTitle:'What do you need help with?', customerAppText:'Send a photo or video and get the right tradesperson.', sendPhotoVideo:'Send a photo or video', masterWorkspace:'Workspace', newRequests:'New requests', inProgress:'In progress', completed:'Completed', incomingRequests:'Incoming requests', viewAll:'View all', phoneMessages:'Messages', phoneHome:'Home',
    check:'Check', describeActivityFirst:'Describe your activity first.', activityAutoHint:'Write at least four words and LOOKDO will start matching automatically.', activityWaiting:'Preparing template matches…', templateFound:'Matching templates found. Choose one.', checkAgain:'Check again', showTemplate:'Show my app', templatePreview:'App preview', templateReady:'Visual request', yourTemplateReady:'This is how your app will look', templateChangesLive:'After confirmation, AI adapts labels, buttons, questions, and photo guidance to your specialization.', templateConfirmText:'This is the safe foundation. After registration LOOKDO creates your individual variant from it.', changeActivity:'Change activity', currency:'Currency', perYear:'/ year', save:'Save', dictate:'Dictate', stopRecording:'Stop recording', transcribing:'Transcribing…', voiceHint:'Type or dictate for up to 60 seconds. Template matching starts automatically after transcription.', microphoneUnavailable:'The browser did not allow microphone access. Allow it or enter the text.',
});

Object.assign(messages.uk, {
    heroTagline:'LOOK. DO.', heroProduct:'Помічник для майстра, який працює сам на себе.', heroText:'Клієнт надсилає фото або відео запиту — майстер отримує зрозумілу заявку і може одразу відповісти.', customerAppTitle:'У чому вам потрібна допомога?', customerAppText:'Надішліть фото або відео — майстер отримає зрозумілу заявку.', sendPhotoVideo:'Надіслати фото або відео', masterWorkspace:'Робочий кабінет', newRequests:'Нові запити', inProgress:'В роботі', completed:'Завершено', incomingRequests:'Вхідні запити', viewAll:'Переглянути всі', phoneMessages:'Повідомлення', phoneHome:'Головна', check:'Перевірити', describeActivityFirst:'Спочатку опишіть діяльність.', activityAutoHint:'Напишіть щонайменше чотири слова — LOOKDO одразу почне підбір.', activityWaiting:'Готуємо підбір шаблону…', templateFound:'Відповідні шаблони знайдено. Оберіть варіант.', checkAgain:'Перевірити ще раз', showTemplate:'Показати застосунок', templatePreview:'Перегляд застосунку', templateReady:'Візуальна заявка', yourTemplateReady:'Ось як виглядатиме ваш застосунок', templateChangesLive:'Після підтвердження ШІ адаптує підписи, кнопки, запитання та фотографії до вашої спеціалізації.', templateConfirmText:'Це безпечна основа. Після реєстрації LOOKDO створить з неї ваш індивідуальний варіант.', changeActivity:'Змінити діяльність', currency:'Валюта', perYear:'/ рік', save:'Економія', dictate:'Продиктувати', stopRecording:'Зупинити запис', transcribing:'Розпізнаємо…', voiceHint:'Можна написати або диктувати до 60 секунд. Після розпізнавання шаблон підбереться автоматично.', microphoneUnavailable:'Браузер не дозволив доступ до мікрофона. Дозвольте його або введіть текст.',
});

Object.assign(messages.ru, {
    poweredBy:'Работает на LOOKDO', tenantAppPreparing:'Приложение бизнеса доступно по собственному адресу', tenantAppPreparingText:'Приём заявок и рабочие разделы будут подключены на следующем этапе.',
    active:'Активно', paymentRequired:'Тариф ещё не оплачен', paymentRequiredText:'Оплатите выбранный тариф, чтобы активировать подписку и приложение.', payNow:'Оплатить тариф', openApp:'Открыть приложение',
    setupNext:'Что нужно сделать дальше', profileStep:'Заполнить профиль', domainStep:'Проверить адрес', paymentStep:'Оплатить подписку', done:'Готово', paid:'Оплачено', unpaid:'Не оплачено',
    complimentaryStatus:'Бесплатно', manualAccessStatus:'Доступ предоставлен вручную · осталось :days дн.', paymentProcessing:'Оплата принята в обработку. Статус обновится автоматически.', checkoutUnavailable:'Не удалось открыть страницу оплаты. Повторите попытку.', date:'Дата', amount:'Сумма', status:'Статус', payment:'Платёж'
});
Object.assign(messages.de, {
    poweredBy:'Bereitgestellt von LOOKDO', tenantAppPreparing:'Die App des Betriebs ist unter der eigenen Adresse erreichbar', tenantAppPreparingText:'Anfragen und Arbeitsbereiche werden in der nächsten Phase aktiviert.',
    active:'Aktiv', paymentRequired:'Der Tarif ist noch nicht bezahlt', paymentRequiredText:'Bezahlen Sie den gewählten Tarif, um Abonnement und App zu aktivieren.', payNow:'Tarif bezahlen', openApp:'App öffnen',
    setupNext:'Nächste Schritte', profileStep:'Profil ausfüllen', domainStep:'Adresse prüfen', paymentStep:'Abonnement bezahlen', done:'Erledigt', paid:'Bezahlt', unpaid:'Nicht bezahlt',
    complimentaryStatus:'Kostenlos', manualAccessStatus:'Manuell freigeschaltet · noch :days Tage', paymentProcessing:'Die Zahlung wird verarbeitet. Der Status wird automatisch aktualisiert.', checkoutUnavailable:'Die Zahlungsseite konnte nicht geöffnet werden. Bitte erneut versuchen.', date:'Datum', amount:'Betrag', status:'Status', payment:'Zahlung'
});
Object.assign(messages.en, {
    poweredBy:'Powered by LOOKDO', tenantAppPreparing:'This business app is available at its own address', tenantAppPreparingText:'Requests and workspace sections will be enabled in the next stage.',
    active:'Active', paymentRequired:'Your plan has not been paid yet', paymentRequiredText:'Pay for the selected plan to activate the subscription and app.', payNow:'Pay for plan', openApp:'Open app',
    setupNext:'What to do next', profileStep:'Complete profile', domainStep:'Check address', paymentStep:'Pay subscription', done:'Done', paid:'Paid', unpaid:'Not paid',
    complimentaryStatus:'Complimentary', manualAccessStatus:'Manually enabled · :days days left', paymentProcessing:'Payment is being processed. The status will update automatically.', checkoutUnavailable:'The payment page could not be opened. Please try again.', date:'Date', amount:'Amount', status:'Status', payment:'Payment'
});
Object.assign(messages.uk, {
    poweredBy:'Працює на LOOKDO', tenantAppPreparing:'Застосунок бізнесу доступний за власною адресою', tenantAppPreparingText:'Заявки й робочі розділи буде підключено на наступному етапі.',
    active:'Активно', paymentRequired:'Тариф ще не оплачено', paymentRequiredText:'Оплатіть вибраний тариф, щоб активувати підписку та застосунок.', payNow:'Оплатити тариф', openApp:'Відкрити застосунок',
    setupNext:'Що зробити далі', profileStep:'Заповнити профіль', domainStep:'Перевірити адресу', paymentStep:'Оплатити підписку', done:'Готово', paid:'Оплачено', unpaid:'Не оплачено',
    complimentaryStatus:'Безкоштовно', manualAccessStatus:'Доступ надано вручну · залишилося :days дн.', paymentProcessing:'Платіж обробляється. Статус оновиться автоматично.', checkoutUnavailable:'Не вдалося відкрити сторінку оплати. Спробуйте ще раз.', date:'Дата', amount:'Сума', status:'Статус', payment:'Платіж'
});

messages.ru.whyTitle = 'Получайте заявки, ведите запись и общайтесь с клиентами — в одном приложении';
messages.de.whyTitle = 'Anfragen erhalten, Termine verwalten und mit Kunden kommunizieren — in einer App';
messages.en.whyTitle = 'Receive requests, manage bookings and talk to customers — all in one app';
messages.uk.whyTitle = 'Отримуйте заявки, ведіть запис і спілкуйтеся з клієнтами — в одному застосунку';

Object.assign(messages.de, {
    socialImageStep:'Vorschaubild ergänzen', socialImageEyebrow:'LINK-VORSCHAU', socialImageTitle:'Bild für WhatsApp und soziale Netzwerke', socialImageText:'Dieses Bild erscheint, wenn Sie Ihre App als Link teilen. Es ist ein Pflichtschritt vor der Veröffentlichung.', socialImageFormat:'Empfohlen: Querformat 1200 × 630 Pixel, JPG, PNG oder WebP.', socialImageMissing:'Noch kein Vorschaubild', uploadImage:'Eigenes Bild hochladen', generateImage:'Mit KI erstellen', pleaseWait:'Bitte warten…', socialImageUploaded:'Das Vorschaubild wurde gespeichert.', socialImageGenerated:'Das Vorschaubild wurde mit KI erstellt.'
});
Object.assign(messages.en, {
    socialImageStep:'Add sharing image', socialImageEyebrow:'LINK PREVIEW', socialImageTitle:'Image for WhatsApp and social networks', socialImageText:'This image appears when you share your app link. It is required before publishing.', socialImageFormat:'Recommended: landscape 1200 × 630 pixels, JPG, PNG or WebP.', socialImageMissing:'No preview image yet', uploadImage:'Upload my image', generateImage:'Create with AI', pleaseWait:'Please wait…', socialImageUploaded:'The preview image was saved.', socialImageGenerated:'The preview image was created with AI.'
});
Object.assign(messages.ru, {
    socialImageStep:'Добавить картинку ссылки', socialImageEyebrow:'ПРЕДПРОСМОТР ССЫЛКИ', socialImageTitle:'Картинка для WhatsApp и социальных сетей', socialImageText:'Эта картинка показывается, когда вы делитесь ссылкой на приложение. Перед публикацией её нужно обязательно добавить.', socialImageFormat:'Рекомендуется: горизонтальная 1200 × 630 пикселей, JPG, PNG или WebP.', socialImageMissing:'Картинка ещё не добавлена', uploadImage:'Загрузить свою', generateImage:'Создать с помощью ИИ', pleaseWait:'Подождите…', socialImageUploaded:'Картинка ссылки сохранена.', socialImageGenerated:'Картинка ссылки создана с помощью ИИ.'
});
Object.assign(messages.uk, {
    socialImageStep:'Додати картинку посилання', socialImageEyebrow:'ПЕРЕГЛЯД ПОСИЛАННЯ', socialImageTitle:'Картинка для WhatsApp і соціальних мереж', socialImageText:'Ця картинка показується, коли ви ділитеся посиланням на застосунок. Перед публікацією її потрібно обов’язково додати.', socialImageFormat:'Рекомендовано: горизонтальна 1200 × 630 пікселів, JPG, PNG або WebP.', socialImageMissing:'Картинку ще не додано', uploadImage:'Завантажити свою', generateImage:'Створити за допомогою ШІ', pleaseWait:'Зачекайте…', socialImageUploaded:'Картинку посилання збережено.', socialImageGenerated:'Картинку посилання створено за допомогою ШІ.'
});

Object.assign(messages.de, {
    imagePromptEyebrow:'KI-BILD', checkImagePrompt:'Prompt vor der Erstellung prüfen', selectedIndustry:'Gewählter Bereich', enteredActivity:'Ihre Tätigkeit', imagePromptLabel:'Prompt für die Bildgenerierung', preparingPrompt:'KI bereitet einen passenden Prompt vor…', imagePromptPreparationFailed:'Der Bild-Prompt konnte nicht vorbereitet werden. Bitte versuchen Sie es erneut.', checkPromptBeforeGenerate:'Bitte prüfen und korrigieren Sie den Prompt. Erst danach wird das kostenpflichtige Bildmodell gestartet.', freeImagesRemaining:'Noch :remaining von :limit kostenlosen Bildern', purchasedCredits:'Gekaufte Credits', additionalImagePrice:'Weiteres Bild:', freeLimitReached:'Die kostenlosen Generierungen sind verbraucht.', buyCreditsText:'Kaufen Sie Credits, um weitere Bilder zu erstellen.', creditQuantity:'Anzahl', buyCredits:'Credits kaufen', generateAfterCheck:'Geprüft — Bild erstellen', imageCreditProcessing:'Die Zahlung wird verarbeitet. Die Credits erscheinen nach der Stripe-Bestätigung automatisch.', imageCreditCancelled:'Der Kauf der Bild-Credits wurde abgebrochen.'
});
Object.assign(messages.en, {
    imagePromptEyebrow:'AI IMAGE', checkImagePrompt:'Review the prompt before generation', selectedIndustry:'Selected industry', enteredActivity:'Your activity', imagePromptLabel:'Image generation prompt', preparingPrompt:'AI is preparing a suitable prompt…', imagePromptPreparationFailed:'The image prompt could not be prepared. Please try again.', checkPromptBeforeGenerate:'Please review and correct the prompt. The paid image model starts only after your confirmation.', freeImagesRemaining:':remaining of :limit free images remaining', purchasedCredits:'Purchased credits', additionalImagePrice:'Additional image:', freeLimitReached:'Your free generations have been used.', buyCreditsText:'Buy credits to create more images.', creditQuantity:'Quantity', buyCredits:'Buy credits', generateAfterCheck:'Reviewed — generate image', imageCreditProcessing:'Payment is processing. Credits appear automatically after Stripe confirms it.', imageCreditCancelled:'The image credit purchase was cancelled.'
});
Object.assign(messages.ru, {
    imagePromptEyebrow:'ИИ-ИЗОБРАЖЕНИЕ', checkImagePrompt:'Проверьте промпт перед генерацией', selectedIndustry:'Выбранная сфера', enteredActivity:'Ваша деятельность', imagePromptLabel:'Промпт для генерации изображения', preparingPrompt:'ИИ готовит подходящий промпт…', imagePromptPreparationFailed:'Не удалось подготовить промпт изображения. Попробуйте ещё раз.', checkPromptBeforeGenerate:'Пожалуйста, проверьте и при необходимости исправьте промпт. Только после подтверждения запускается платная генерация изображения.', freeImagesRemaining:'Осталось бесплатно: :remaining из :limit', purchasedCredits:'Купленные кредиты', additionalImagePrice:'Следующее изображение:', freeLimitReached:'Бесплатные генерации закончились.', buyCreditsText:'Купите кредиты, чтобы создавать дополнительные изображения.', creditQuantity:'Количество', buyCredits:'Купить кредиты', generateAfterCheck:'Проверил — создать изображение', imageCreditProcessing:'Оплата обрабатывается. Кредиты появятся автоматически после подтверждения Stripe.', imageCreditCancelled:'Покупка кредитов отменена.'
});
Object.assign(messages.uk, {
    imagePromptEyebrow:'ШІ-ЗОБРАЖЕННЯ', checkImagePrompt:'Перевірте промпт перед генерацією', selectedIndustry:'Обрана сфера', enteredActivity:'Ваша діяльність', imagePromptLabel:'Промпт для генерації зображення', preparingPrompt:'ШІ готує відповідний промпт…', imagePromptPreparationFailed:'Не вдалося підготувати промпт зображення. Спробуйте ще раз.', checkPromptBeforeGenerate:'Будь ласка, перевірте та за потреби виправте промпт. Платна генерація зображення запускається лише після підтвердження.', freeImagesRemaining:'Залишилося безкоштовно: :remaining з :limit', purchasedCredits:'Придбані кредити', additionalImagePrice:'Наступне зображення:', freeLimitReached:'Безкоштовні генерації закінчилися.', buyCreditsText:'Придбайте кредити, щоб створювати додаткові зображення.', creditQuantity:'Кількість', buyCredits:'Придбати кредити', generateAfterCheck:'Перевірено — створити зображення', imageCreditProcessing:'Оплата обробляється. Кредити з’являться автоматично після підтвердження Stripe.', imageCreditCancelled:'Придбання кредитів скасовано.'
});
Object.assign(messages.de, { aiRequiresPayment:'Bezahlen Sie zuerst Ihren Tarif. Die KI-Bildgenerierung wird erst nach der Aktivierung freigeschaltet.' });
Object.assign(messages.en, { aiRequiresPayment:'Pay for your plan first. AI image generation is unlocked after activation.' });
Object.assign(messages.ru, { aiRequiresPayment:'Сначала оплатите тариф. Генерация изображений с помощью ИИ станет доступна после активации подписки.' });
Object.assign(messages.uk, { aiRequiresPayment:'Спочатку оплатіть тариф. Генерація зображень за допомогою ШІ стане доступною після активації підписки.' });
Object.assign(messages.ru, { trialAccessTitle:'Включён полный тестовый доступ', trialAccessText:'Все функции LOOKDO доступны ещё :days дн. Выберите подходящий тариф до окончания теста.', trialStatus:'Тест: :days дн.', choosePlan:'Выбрать тариф' });
Object.assign(messages.de, { trialAccessTitle:'Voller Testzugang ist aktiv', trialAccessText:'Alle LOOKDO Funktionen sind noch :days Tage verfügbar. Wählen Sie vor Ablauf des Tests den passenden Tarif.', trialStatus:'Test: :days Tg.', choosePlan:'Tarif wählen' });
Object.assign(messages.en, { trialAccessTitle:'Full trial access is active', trialAccessText:'All LOOKDO features are available for :days more days. Choose the right plan before the trial ends.', trialStatus:'Trial: :days days', choosePlan:'Choose plan' });
Object.assign(messages.uk, { trialAccessTitle:'Увімкнено повний тестовий доступ', trialAccessText:'Усі функції LOOKDO доступні ще :days дн. Оберіть відповідний тариф до завершення тесту.', trialStatus:'Тест: :days дн.', choosePlan:'Обрати тариф' });
Object.assign(messages.de, { pageNotFound:'Diese Seite wurde nicht gefunden.', returnHome:'Zur Startseite' });
Object.assign(messages.en, { pageNotFound:'This page could not be found.', returnHome:'Back to home' });
Object.assign(messages.ru, { pageNotFound:'Эта страница не найдена.', returnHome:'На главную' });
Object.assign(messages.uk, { pageNotFound:'Цю сторінку не знайдено.', returnHome:'На головну' });
export const t = (key: string) => computed(() => messages[locale.value][key] || key);
export function tr(key: string): string { return messages[locale.value][key] || key; }
export function setLocale(value: Locale) { locale.value=value;localStorage.setItem('lookdo-locale',value);document.documentElement.lang=value; }
