<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { api } from '../api';
import AppIcon from './AppIcon.vue';
const props=defineProps<{app:any;copy:any;locale:string;token:string}>();
const emit=defineEmits<{close:[];success:[payload:any]}>();
const stage=ref<'service'|'date'|'contact'|'success'>('service'); const selectedService=ref<any>(null); const selectedDate=ref(''); const selectedSlot=ref<any>(null); const slots=ref<any[]>([]); const busy=ref(false); const error=ref(''); const result=ref<any>(null);
const form=reactive({name:'',phone:'',email:'',comment:'',preferred_channel:'phone'});
const days=computed(()=>Array.from({length:14},(_,index)=>{const date=new Date();date.setDate(date.getDate()+index);const iso=date.toISOString().slice(0,10);return{iso,day:date.toLocaleDateString(props.locale,{weekday:'short'}),date:date.getDate(),month:date.toLocaleDateString(props.locale,{month:'short'}),special:index===0?props.copy.today:index===1?props.copy.tomorrow:''}}));
function chooseService(service:any){selectedService.value=service;stage.value='date';selectedDate.value=days.value[0].iso;loadSlots();}
async function loadSlots(){if(!selectedService.value||!selectedDate.value)return;busy.value=true;error.value='';try{const response=await api(`/tenant-app/availability?service_id=${selectedService.value.id}&date=${selectedDate.value}`,{headers:props.token?{'X-Lookdo-Client-Token':props.token}:{}});slots.value=response.slots;selectedSlot.value=null;}catch(e:any){error.value=e.message;}finally{busy.value=false;}}
async function book(){if(!form.phone){error.value=props.copy.phone;return;}busy.value=true;error.value='';try{result.value=await api('/tenant-app/appointments',{method:'POST',headers:props.token?{'X-Lookdo-Client-Token':props.token}:{},body:JSON.stringify({...form,service_id:selectedService.value.id,starts_at:selectedSlot.value.starts_at})});stage.value='success';emit('success',result.value);}catch(e:any){error.value=e.message;}finally{busy.value=false;}}
function back(){if(stage.value==='contact')stage.value='date';else if(stage.value==='date')stage.value='service';else emit('close');}
onMounted(()=>{if(props.app.session?.customer){form.name=props.app.session.customer.name||'';form.phone=props.app.session.customer.phone||'';}});
</script>
<template>
<section class="ta-flow ta-booking-flow">
  <header class="ta-flow-head"><button class="ta-icon-button" @click="back"><AppIcon name="back"/></button><div><span>{{ app.template.name }}</span><b>{{ stage==='service'?copy.services:stage==='date'?copy.selectTime:stage==='contact'?copy.appointmentDetails:copy.booked }}</b></div><button class="ta-icon-button" @click="emit('close')"><AppIcon name="close"/></button></header>
  <div v-if="stage==='service'" class="ta-flow-body"><div class="ta-flow-intro"><h1>{{ app.template.hero.action }}</h1><p>{{ app.template.hero.text }}</p></div><div class="ta-service-list"><button v-for="service in app.services" :key="service.id" class="ta-service-card" @click="chooseService(service)"><span><b>{{ service.name }}</b><small>{{ service.description }}</small></span><em>{{ service.duration }} {{ copy.duration }}</em><AppIcon name="arrow"/></button></div></div>
  <div v-else-if="stage==='date'" class="ta-flow-body"><div class="ta-selected-service"><AppIcon name="calendar"/><span><b>{{ selectedService.name }}</b><small>{{ selectedService.duration }} {{ copy.duration }}</small></span></div><h2>{{ copy.selectDate }}</h2><div class="ta-date-strip"><button v-for="day in days" :key="day.iso" :class="{active:selectedDate===day.iso}" @click="selectedDate=day.iso;loadSlots()"><small>{{ day.special||day.day }}</small><b>{{ day.date }}</b><span>{{ day.month }}</span></button></div><h2>{{ copy.selectTime }}</h2><div v-if="busy" class="ta-loading-line"></div><div v-else class="ta-time-grid"><button v-for="slot in slots" :key="slot.starts_at" :class="{active:selectedSlot?.starts_at===slot.starts_at}" @click="selectedSlot=slot">{{ slot.label }}</button><p v-if="!slots.length">—</p></div><p v-if="error" class="ta-error">{{ error }}</p><div class="ta-sticky-action"><button class="ta-primary" :disabled="!selectedSlot" @click="stage='contact'">{{ copy.continue }} <AppIcon name="arrow" :size="20"/></button></div></div>
  <div v-else-if="stage==='contact'" class="ta-flow-body ta-form-screen"><div class="ta-appointment-summary"><b>{{ selectedService.name }}</b><span>{{ new Date(selectedSlot.starts_at).toLocaleString(locale,{dateStyle:'long',timeStyle:'short'}) }}</span></div><h1>{{ copy.appointmentDetails }}</h1><div class="ta-fields two"><label><span>{{ copy.name }}</span><input v-model="form.name" autocomplete="name"></label><label><span>{{ copy.phone }} *</span><input v-model="form.phone" type="tel" inputmode="tel" autocomplete="tel"></label><label><span>{{ copy.email }}</span><input v-model="form.email" type="email" autocomplete="email"></label><label class="full"><span>{{ copy.summary }}</span><textarea v-model="form.comment" rows="3"/></label></div><p v-if="error" class="ta-error">{{ error }}</p><div class="ta-sticky-action"><button class="ta-primary" :disabled="busy" @click="book">{{ busy?copy.booking:copy.bookNow }} <AppIcon name="arrow" :size="20"/></button></div></div>
  <div v-else class="ta-success-screen"><div class="ta-success-mark"><AppIcon name="check" :size="42"/></div><h1>{{ copy.booked }}</h1><p>{{ new Date(result.appointment.starts_at).toLocaleString(locale,{dateStyle:'long',timeStyle:'short'}) }}</p><strong>{{ result.appointment.service.name }}</strong><button class="ta-primary" @click="emit('close')">{{ copy.activity }} <AppIcon name="arrow" :size="20"/></button></div>
</section>
</template>