<script setup lang="ts">
import { computed,onMounted,reactive,ref,watch } from 'vue';import { useRoute,useRouter } from 'vue-router';import { api } from '../api';
const route=useRoute();const router=useRouter();const section=computed(()=>String(route.params.section||'dashboard'));const data=ref<any>(null);const me=ref<any>(null);const error=ref('');const busy=ref(false);const selectedTenant=ref<any>(null);
const planForm=reactive<any>({code:'',name:{de:'',en:'',ru:''},description:{de:'',en:'',ru:''},price_monthly:19,price_yearly:190,currency:'EUR',trial_days:0,is_active:true,is_public:true,sort_order:50,badge_text:{},entitlements:{storage_mb:'2048',custom_domain:'0',staff_users:'1'}});
const phraseForm=reactive<any>({category_id:null,variation_id:null,locale:'ru',phrase:'',weight:1,enabled:true});
const nav=[['dashboard','▦','Dashboard'],['tenants','◎','Tenants'],['users','♙','Users'],['plans','€','Plans'],['domains','◇','Domains'],['templates','≡','Templates'],['ai','✦','AI dictionary'],['classifications','↯','AI decisions'],['content','□','Content & settings'],['audit','⌁','Audit log']];
async function load(){error.value='';try{me.value=await api('/me');if(!me.value.user?.is_super_admin)return router.push('/login');const endpoint:{[k:string]:string}={dashboard:'/control/dashboard',tenants:'/control/tenants',users:'/control/users',plans:'/control/plans',domains:'/control/domains',templates:'/control/taxonomy',ai:'/control/phrases',classifications:'/control/classifications',content:'/control/settings',audit:'/control/audits'};data.value=await api(endpoint[section.value]||endpoint.dashboard)}catch(e:any){error.value=e.message;if(String(e.message).includes('Unauthenticated'))router.push('/login')}}
onMounted(load);watch(section,()=>{selectedTenant.value=null;load()});
async function openTenant(item:any){selectedTenant.value=await api(`/control/tenants/${item.id}`)}
async function updateTenant(payload:any){busy.value=true;try{await api(`/control/tenants/${selectedTenant.value.id}`,{method:'PUT',body:JSON.stringify(payload)});selectedTenant.value=await api(`/control/tenants/${selectedTenant.value.id}`);await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function impersonate(){await api(`/control/tenants/${selectedTenant.value.id}/impersonate`,{method:'POST'});location.href='/app'}
async function toggleUser(user:any){await api(`/control/users/${user.id}`,{method:'PUT',body:JSON.stringify({is_active:!user.is_active})});await load()}
async function createPlan(){busy.value=true;try{await api('/control/plans',{method:'POST',body:JSON.stringify(planForm)});Object.assign(planForm,{code:'',name:{de:'',en:'',ru:''},description:{de:'',en:'',ru:''}});await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function syncPlan(plan:any){busy.value=true;try{await api(`/control/plans/${plan.id}/stripe-sync`,{method:'POST'});await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function domainAction(domain:any,action:string){busy.value=true;try{await api(`/control/domains/${domain.id}/${action}`,{method:'POST'});await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function toggleTemplate(template:any){await api(`/control/templates/${template.id}/toggle`,{method:'PUT',body:JSON.stringify({enabled:!template.enabled})});await load()}
async function addPhrase(){busy.value=true;try{await api('/control/phrases',{method:'POST',body:JSON.stringify(phraseForm)});phraseForm.phrase='';await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function saveSetting(key:string,value:any){await api('/control/settings',{method:'PUT',body:JSON.stringify({key,value})});await load()}
async function savePage(page:any){await api(`/control/pages/${page.id}`,{method:'PUT',body:JSON.stringify({title:page.title,content:page.content,is_published:page.is_published})});await load()}
async function logout(){await api('/logout',{method:'POST'});router.push('/login')}
</script>
<template><div class="control-shell"><aside class="control-sidebar"><div class="brand light-brand"><span class="brand-mark">L·D</span><span>LOOKDO<small>SUPER ADMIN</small></span></div><nav><RouterLink v-for="item in nav" :key="item[0]" :to="`/control/${item[0]}`" :class="{active:section===item[0]}"><span>{{item[1]}}</span>{{item[2]}}</RouterLink></nav><button class="sidebar-logout" @click="logout">Sign out</button></aside><main class="control-main"><header class="control-header"><div><p class="eyebrow">LOOKDO CONTROL</p><h1>{{nav.find(x=>x[0]===section)?.[2]}}</h1></div><div class="admin-chip"><span>SA</span><div><b>{{me?.user?.name}}</b><small>{{me?.user?.email}}</small></div></div></header><p v-if="error" class="alert error">{{error}}</p><div v-if="!data" class="loading">Loading…</div>
<template v-else><section v-if="section==='dashboard'" class="admin-metrics"><article v-for="(value,key) in data" :key="key"><span>{{String(key).replaceAll('_',' ')}}</span><strong>{{key==='mrr'?`${Number(value).toFixed(2)} €`:value}}</strong></article></section>
<section v-if="section==='tenants'" class="admin-section"><div class="admin-table-wrap"><table><thead><tr><th>Tenant</th><th>Owner</th><th>Template</th><th>Domain</th><th>Plan</th><th>Status</th></tr></thead><tbody><tr v-for="tenant in data.data" :key="tenant.id" @click="openTenant(tenant)"><td><b>{{tenant.name}}</b><small>{{tenant.slug}}</small></td><td>{{tenant.users?.[0]?.email}}</td><td>{{tenant.business_profile?.variation?.code||'—'}}</td><td>{{tenant.primary_domain?.domain}}</td><td>{{tenant.current_subscription?.plan?.code||'—'}}</td><td><span class="table-status">{{tenant.status}}</span></td></tr></tbody></table></div><aside v-if="selectedTenant" class="drawer"><button class="drawer-close" @click="selectedTenant=null">×</button><p class="eyebrow">TENANT #{{selectedTenant.id}}</p><h2>{{selectedTenant.name}}</h2><p>{{selectedTenant.slug}}.lookdo.app</p><dl><div><dt>Owner</dt><dd>{{selectedTenant.users?.[0]?.email}}</dd></div><div><dt>Plan</dt><dd>{{selectedTenant.current_subscription?.plan?.code||'—'}}</dd></div><div><dt>Status</dt><dd>{{selectedTenant.status}}</dd></div></dl><button class="button full" @click="impersonate">Open tenant account</button><div class="drawer-actions"><button class="button ghost" @click="updateTenant({status:selectedTenant.status==='active'?'suspended':'active'})">{{selectedTenant.status==='active'?'Suspend':'Activate'}}</button><button class="button ghost" @click="updateTenant({plan_id:data.data[0]?.current_subscription?.plan_id||selectedTenant.current_subscription?.plan_id,complimentary:true,discount_percent:100})">Complimentary</button></div><h3>Domains</h3><p v-for="domain in selectedTenant.domains" :key="domain.id">{{domain.domain}} · {{domain.status}}</p></aside></section>
<section v-if="section==='users'" class="admin-section"><div class="admin-table-wrap"><table><thead><tr><th>User</th><th>Tenant</th><th>Role</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="user in data.data" :key="user.id"><td><b>{{user.name}}</b><small>{{user.email}}</small></td><td>{{user.tenants?.map((t:any)=>t.name).join(', ')||'Platform'}}</td><td>{{user.is_super_admin?'Super Admin':user.tenants?.[0]?.pivot?.role}}</td><td>{{user.is_active?'active':'blocked'}}</td><td><button class="link-button" @click="toggleUser(user)">{{user.is_active?'Block':'Activate'}}</button></td></tr></tbody></table></div></section>
<section v-if="section==='plans'" class="admin-section"><div class="plan-admin-grid"><article v-for="plan in data" :key="plan.id" class="admin-card"><div class="row-between"><div><p class="eyebrow">{{plan.code}}</p><h2>{{plan.name.de}}</h2></div><span class="table-status">{{plan.is_active?'active':'archive'}}</span></div><strong class="admin-price">{{plan.price_monthly}} €</strong><p>{{plan.description.de}}</p><div class="tag-list"><span v-for="e in plan.entitlements" :key="e.id">{{e.key}}={{e.value}}</span></div><button class="button ghost small" :disabled="busy" @click="syncPlan(plan)">Sync Stripe</button></article></div><form class="admin-card form-grid" @submit.prevent="createPlan"><h2 class="wide">New plan</h2><label>Code<input v-model="planForm.code" required></label><label>Monthly price<input v-model.number="planForm.price_monthly" type="number" required></label><label>German name<input v-model="planForm.name.de" required></label><label>English name<input v-model="planForm.name.en" required></label><label class="wide">Russian name<input v-model="planForm.name.ru" required></label><label class="wide">German description<textarea v-model="planForm.description.de"></textarea></label><button class="button">Create plan</button></form></section>
<section v-if="section==='domains'" class="admin-section"><div class="admin-table-wrap"><table><thead><tr><th>Domain</th><th>Tenant</th><th>Type</th><th>DNS / SSL</th><th>Checked</th><th></th></tr></thead><tbody><tr v-for="domain in data.data" :key="domain.id"><td><b>{{domain.domain}}</b></td><td>{{domain.tenant?.name}}</td><td>{{domain.type}}</td><td>{{domain.status}} / {{domain.ssl_status||'—'}}</td><td>{{domain.last_checked_at||'—'}}</td><td><button v-if="domain.type==='custom'" class="link-button" @click="domainAction(domain,'verify')">Verify</button><button v-if="domain.status==='ssl_pending'" class="link-button" @click="domainAction(domain,'activate')">Activate</button></td></tr></tbody></table></div></section>
<section v-if="section==='templates'" class="admin-section"><div class="taxonomy-grid"><article class="admin-card" v-for="category in data.categories" :key="category.id"><div class="row-between"><h2>{{category.name.de}}</h2><span>{{category.enabled?'active':'off'}}</span></div><div class="variation" v-for="variation in category.variations" :key="variation.id"><b>{{variation.name.de}}</b><code>{{variation.code}}</code><span>priority {{variation.priority}}</span></div></article></div><div class="admin-table-wrap"><table><thead><tr><th>Template</th><th>Parent</th><th>Version</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="template in data.templates" :key="template.id"><td><b>{{template.code}}</b></td><td>{{template.parent_code||'—'}}</td><td>{{template.version}}</td><td>{{template.enabled?'enabled':'disabled'}}</td><td><button class="link-button" @click="toggleTemplate(template)">{{template.enabled?'Disable':'Enable'}}</button></td></tr></tbody></table></div></section>
<section v-if="section==='ai'" class="admin-section"><form class="admin-card phrase-form" @submit.prevent="addPhrase"><div><p class="eyebrow">DICTIONARY</p><h2>Add a business phrase</h2></div><label>Locale<select v-model="phraseForm.locale"><option>de</option><option>en</option><option>ru</option></select></label><label>Category ID<input v-model.number="phraseForm.category_id" type="number" required></label><label>Variation ID<input v-model.number="phraseForm.variation_id" type="number"></label><label>Phrase<input v-model="phraseForm.phrase" required></label><button class="button">Add</button></form><div class="admin-table-wrap"><table><thead><tr><th>Phrase</th><th>Locale</th><th>Category</th><th>Variation</th><th>Weight</th></tr></thead><tbody><tr v-for="phrase in data.data" :key="phrase.id"><td><b>{{phrase.phrase}}</b><small>{{phrase.normalized_phrase}}</small></td><td>{{phrase.locale}}</td><td>{{phrase.category?.code}}</td><td>{{phrase.variation?.code}}</td><td>{{phrase.weight}}</td></tr></tbody></table></div></section>
<section v-if="section==='classifications'" class="admin-section"><div class="admin-table-wrap"><table><thead><tr><th>Date</th><th>Input</th><th>Tenant</th><th>Result</th><th>Confidence</th><th>Source</th><th>Confirmed</th></tr></thead><tbody><tr v-for="item in data.data" :key="item.id"><td>{{item.created_at}}</td><td><b>{{item.original_text}}</b><small>{{item.normalized_text}}</small></td><td>{{item.tenant?.name||'registration'}}</td><td>{{item.category?.code||'—'}}<small>{{item.variation?.code||'general'}}</small></td><td>{{Math.round(Number(item.confidence)*100)}}%</td><td>{{item.source}}{{item.ai_model?` · ${item.ai_model}`:''}}</td><td>{{item.confirmed_by_user_at?'yes':'no'}}</td></tr></tbody></table></div></section>
<section v-if="section==='content'" class="admin-section"><div class="settings-grid"><article class="admin-card"><h2>System settings</h2><label v-for="(value,key) in data.settings" :key="key">{{String(key).replaceAll('_',' ')}}<div class="setting-row"><input :value="typeof value==='object'?JSON.stringify(value):String(value)" @change="saveSetting(String(key),($event.target as HTMLInputElement).value)"><span>Save on change</span></div></label></article><article v-for="page in data.pages" :key="page.id" class="admin-card page-editor"><div class="row-between"><div><p class="eyebrow">/{{page.key}}</p><h2>{{page.title.de}}</h2></div><label class="check"><input v-model="page.is_published" type="checkbox"> Published</label></div><label>DE title<input v-model="page.title.de"></label><label>DE content<textarea v-model="page.content.de" rows="6"></textarea></label><label>EN content<textarea v-model="page.content.en" rows="4"></textarea></label><label>RU content<textarea v-model="page.content.ru" rows="4"></textarea></label><button class="button small" @click="savePage(page)">Save page</button></article></div></section>
<section v-if="section==='audit'" class="admin-section"><div class="admin-table-wrap"><table><thead><tr><th>Date</th><th>Action</th><th>Actor</th><th>Tenant</th><th>Subject</th></tr></thead><tbody><tr v-for="log in data.data" :key="log.id"><td>{{log.created_at}}</td><td><b>{{log.action}}</b></td><td>{{log.actor_id||'system'}}</td><td>{{log.tenant_id||'—'}}</td><td>{{log.subject_type}} #{{log.subject_id}}</td></tr></tbody></table></div></section>
</template></main></div></template>
