<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { api } from '../api';
import AdminModal from '../components/admin/AdminModal.vue';
import AdminPagination from '../components/admin/AdminPagination.vue';
import RegistryToolbar from '../components/admin/RegistryToolbar.vue';
import RichContentEditor from '../components/admin/RichContentEditor.vue';

const route = useRoute();
const router = useRouter();
const section = computed(() => String(route.params.section || 'dashboard'));
const data = ref<any>(null); const me = ref<any>(null); const error = ref(''); const noticeText = ref(''); const busy = ref(false);
const modal = ref(''); const selectedTenant = ref<any>(null); const selectedPage = ref<any>(null); const selectedSetting = ref<any>(null);
const contentLocale = ref('de'); const catalogKind = ref('template'); const editingPlanId = ref<number | null>(null);
const lookups = ref<any>({ plans: [], variations: [], categories: [] });

const nav = [
    ['dashboard', '▦', 'Übersicht'], ['tenants', '◎', 'Kunden'], ['users', '♙', 'Benutzer'],
    ['subscriptions', '◉', 'Abrechnung'], ['plans', '€', 'Tarife'], ['stripe', 'S', 'Stripe'],
    ['domains', '◇', 'Domains'], ['templates', '≡', 'Vorlagen'], ['ai', '✦', 'KI-Wörterbuch'],
    ['classifications', '↯', 'KI-Entscheidungen'], ['content', '□', 'Inhalte & Einstellungen'],
    ['backups', '↥', 'Backups'], ['audit', '⌁', 'Prüfprotokoll'],
];
const endpoint: Record<string, string> = {
    dashboard: '/control/dashboard', tenants: '/control/tenants', users: '/control/users', subscriptions: '/control/subscriptions',
    plans: '/control/plans', stripe: '/control/stripe', domains: '/control/domains', templates: '/control/taxonomy', ai: '/control/phrases',
    classifications: '/control/classifications', content: '/control/settings', backups: '/control/backups', audit: '/control/audits',
};
const serverSections = new Set(['tenants', 'users', 'subscriptions', 'domains', 'ai', 'classifications', 'audit']);
const addLabels: Record<string, string> = { tenants: 'Kunde', plans: 'Tarif', templates: 'Eintrag', ai: 'Begriff' };
const metricLabels: Record<string, string> = { tenants: 'Kunden', active_tenants: 'Aktive Kunden', trialing: 'Testphase', paid: 'Bezahlt', complimentary: 'Kostenlos', domains_attention: 'Domains prüfen', classifications_30d: 'Klassifizierungen (30 Tage)', ai_spend_month: 'KI-Kosten im Monat', mrr: 'Monatlicher Umsatz' };
const sortOptions: Record<string, Array<[string, string]>> = {
    tenants: [['created_at', 'Erstellt'], ['name', 'Name'], ['status', 'Status'], ['last_activity_at', 'Letzte Aktivität']], users: [['created_at', 'Erstellt'], ['name', 'Name'], ['email', 'E-Mail'], ['last_login_at', 'Letzte Anmeldung']],
    subscriptions: [['created_at', 'Erstellt'], ['status', 'Status'], ['provider', 'Anbieter'], ['current_period_end', 'Periodenende']], plans: [['sort_order', 'Reihenfolge'], ['code', 'Code'], ['price_monthly', 'Preis']],
    domains: [['created_at', 'Erstellt'], ['domain', 'Domain'], ['status', 'Status'], ['last_checked_at', 'Zuletzt geprüft']], templates: [['kind', 'Typ'], ['code', 'Code'], ['sort_order', 'Reihenfolge'], ['enabled', 'Status']],
    ai: [['created_at', 'Erstellt'], ['phrase', 'Begriff'], ['locale', 'Sprache'], ['weight', 'Gewichtung']], classifications: [['created_at', 'Datum'], ['confidence', 'Sicherheit'], ['source', 'Quelle']],
    content: [['kind', 'Typ'], ['label', 'Name']], backups: [['created_at', 'Erstellt'], ['name', 'Name']], audit: [['created_at', 'Datum'], ['action', 'Aktion'], ['actor_id', 'Benutzer']],
};
const statusOptions: Record<string, Array<[string, string]>> = {
    tenants: [['active', 'Aktiv'], ['suspended', 'Gesperrt'], ['archived', 'Archiviert']], users: [['active', 'Aktiv'], ['inactive', 'Gesperrt']],
    subscriptions: [['active', 'Aktiv'], ['trialing', 'Testphase'], ['complimentary', 'Kostenlos'], ['incomplete', 'Unvollständig'], ['past_due', 'Überfällig'], ['canceled', 'Gekündigt']],
    plans: [['active', 'Aktiv'], ['inactive', 'Archiviert']], domains: [['pending', 'Ausstehend'], ['verifying', 'Prüfung'], ['ssl_pending', 'SSL ausstehend'], ['active', 'Aktiv'], ['failed', 'Fehler'], ['disabled', 'Deaktiviert']],
    templates: [['active', 'Aktiv'], ['inactive', 'Inaktiv']], ai: [['active', 'Aktiv'], ['inactive', 'Inaktiv']], content: [['active', 'Veröffentlicht'], ['inactive', 'Entwurf']],
};
const filters = reactive({ search: '', status: '', secondary: '', sort: 'created_at', direction: 'desc', per_page: 25, page: 1 });
const tenantForm = reactive<any>({ name: '', slug: '', owner_name: '', owner_email: '', owner_password: '', country: 'DE', locale: 'ru', business_description: '', variation_id: null, plan_id: null, complimentary: true });
const planForm = reactive<any>({ code: '', name: { de: '', en: '', ru: '', uk: '' }, description: { de: '', en: '', ru: '', uk: '' }, price_monthly: 19, price_yearly: 190, currency: 'EUR', trial_days: 0, is_active: true, is_public: true, sort_order: 50, badge_text: {}, entitlements: { storage_mb: '2048', custom_domain: '0', staff_users: '1' } });
const phraseForm = reactive<any>({ category_id: null, variation_id: null, locale: 'ru', phrase: '', weight: 1, enabled: true });
const categoryForm = reactive<any>({ code: '', name: { ru: '', de: '', en: '', uk: '' }, enabled: true, sort_order: 50 });
const variationForm = reactive<any>({ category_id: null, code: '', name: { ru: '', de: '', en: '', uk: '' }, template_code: '', enabled: true, priority: 50 });
const templateForm = reactive<any>({ category_id: null, variation_id: null, code: '', parent_code: '', name: { ru: '', de: '', en: '', uk: '' }, configuration: '{\n  "media": {"photos_min": 1, "photos_max": 5, "video_allowed": true},\n  "fields": []\n}', enabled: true, version: 1, sort_order: 50 });
const overrideForm = reactive({ key: '', value: '' });

function toast(message: string) { noticeText.value = message; window.setTimeout(() => noticeText.value = '', 3500); }
function queryString() {
    const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => value !== '' && params.set(key, String(value)));
    const secondaryKeys: Record<string, string> = { users: 'role', subscriptions: 'provider', domains: 'type', ai: 'locale', classifications: 'source' };
    if (secondaryKeys[section.value] && filters.secondary) params.set(secondaryKeys[section.value], filters.secondary); return params.toString();
}
async function load() {
    error.value = '';
    try {
        me.value ||= await api('/me'); if (!me.value.user?.is_super_admin) return router.push('/login');
        const url = endpoint[section.value] || endpoint.dashboard; data.value = await api(serverSections.has(section.value) ? `${url}?${queryString()}` : url);
        if (['tenants', 'ai', 'templates'].includes(section.value)) {
            const [plans, taxonomy] = await Promise.all([api<any[]>('/control/plans'), api<any>('/control/taxonomy')]);
            lookups.value = { plans, categories: taxonomy.categories, variations: taxonomy.categories.flatMap((category: any) => category.variations) };
        }
    } catch (exception: any) { error.value = exception.message; if (String(exception.message).includes('Unauthenticated')) router.push('/login'); }
}
function resetFilters() { Object.assign(filters, { search: '', status: '', secondary: '', sort: sortOptions[section.value]?.[0]?.[0] || 'created_at', direction: 'desc', per_page: 25, page: 1 }); }
let debounce: number | undefined;
watch(section, () => { selectedTenant.value = null; modal.value = ''; resetFilters(); data.value = null; load(); });
watch(filters, () => { if (!serverSections.has(section.value)) return; window.clearTimeout(debounce); debounce = window.setTimeout(load, 280); }, { deep: true });
onMounted(load);

const catalogRows = computed(() => {
    if (section.value === 'plans') return (data.value || []).map((item: any) => ({ ...item, label: item.name?.de || item.code }));
    if (section.value === 'templates') {
        const categories = (data.value?.categories || []).map((item: any) => ({ ...item, kind: 'category', label: item.name?.de || item.code }));
        const variations = (data.value?.categories || []).flatMap((category: any) => category.variations.map((item: any) => ({ ...item, kind: 'variation', categoryLabel: category.name?.de || category.code, label: item.name?.de || item.code, sort_order: item.priority })));
        const templates = (data.value?.templates || []).map((item: any) => ({ ...item, kind: 'template', label: item.name?.de || item.code })); return [...categories, ...variations, ...templates];
    }
    if (section.value === 'content') {
        const pages = (data.value?.pages || []).map((item: any) => ({ ...item, kind: 'page', label: item.title?.de || item.key }));
        const settings = Object.entries(data.value?.settings || {}).map(([key, value]) => ({ id: `setting-${key}`, key, value, kind: 'setting', label: key.replaceAll('_', ' ') })); return [...pages, ...settings];
    }
    if (section.value === 'backups') return data.value?.backups || []; return [];
});
const localFiltered = computed(() => {
    let result = [...catalogRows.value]; const term = filters.search.toLowerCase().trim(); if (term) result = result.filter((row: any) => JSON.stringify(row).toLowerCase().includes(term));
    if (filters.status) result = result.filter((row: any) => filters.status === 'active' ? (row.enabled ?? row.is_active ?? row.is_published) : !(row.enabled ?? row.is_active ?? row.is_published));
    if (filters.secondary) result = result.filter((row: any) => row.kind === filters.secondary); const key = filters.sort;
    result.sort((a: any, b: any) => String(a[key] ?? '').localeCompare(String(b[key] ?? ''), 'de', { numeric: true })); if (filters.direction === 'desc') result.reverse(); return result;
});
const localPageRows = computed(() => localFiltered.value.slice((filters.page - 1) * filters.per_page, filters.page * filters.per_page));
const rows = computed(() => serverSections.has(section.value) ? (data.value?.data || []) : localPageRows.value);
const pager = computed(() => serverSections.has(section.value) ? { current: data.value?.current_page || 1, last: data.value?.last_page || 1, from: data.value?.from, to: data.value?.to, total: data.value?.total || 0 } : { current: filters.page, last: Math.max(1, Math.ceil(localFiltered.value.length / filters.per_page)), from: localFiltered.value.length ? (filters.page - 1) * filters.per_page + 1 : 0, to: Math.min(filters.page * filters.per_page, localFiltered.value.length), total: localFiltered.value.length });
function changePage(page: number) { filters.page = Math.max(1, Math.min(page, pager.value.last)); }
function openAdd() { if (section.value === 'tenants') modal.value = 'tenant'; if (section.value === 'plans') { editingPlanId.value = null; modal.value = 'plan'; } if (section.value === 'templates') modal.value = 'catalog'; if (section.value === 'ai') modal.value = 'phrase'; }
async function submit(action: () => Promise<any>, success: string) { busy.value = true; error.value = ''; try { await action(); modal.value = ''; toast(success); await load(); } catch (exception: any) { error.value = exception.message; } finally { busy.value = false; } }
async function createTenant() { await submit(() => api('/control/tenants', { method: 'POST', body: JSON.stringify(tenantForm) }), 'Kunde wurde angelegt.'); }
async function savePlan() { await submit(() => api(editingPlanId.value ? `/control/plans/${editingPlanId.value}` : '/control/plans', { method: editingPlanId.value ? 'PUT' : 'POST', body: JSON.stringify(planForm) }), 'Tarif wurde gespeichert.'); }
function editPlan(plan: any) { editingPlanId.value = plan.id; Object.assign(planForm, { ...plan, name: { ...plan.name }, description: { ...(plan.description || {}) }, badge_text: { ...(plan.badge_text || {}) }, entitlements: Object.fromEntries(plan.entitlements.map((item: any) => [item.key, item.value])) }); modal.value = 'plan'; }
async function saveCatalog() {
    if (catalogKind.value === 'category') return submit(() => api('/control/categories', { method: 'POST', body: JSON.stringify(categoryForm) }), 'Kategorie wurde angelegt.');
    if (catalogKind.value === 'variation') return submit(() => api('/control/variations', { method: 'POST', body: JSON.stringify(variationForm) }), 'Variante wurde angelegt.');
    const payload = { ...templateForm, configuration: JSON.parse(templateForm.configuration) }; return submit(() => api('/control/templates', { method: 'POST', body: JSON.stringify(payload) }), 'Vorlage wurde angelegt.');
}
function choosePhraseVariation() { const variation = lookups.value.variations.find((item: any) => item.id === phraseForm.variation_id); phraseForm.category_id = variation?.category_id || null; }
async function savePhrase() { choosePhraseVariation(); await submit(() => api('/control/phrases', { method: 'POST', body: JSON.stringify(phraseForm) }), 'Begriff wurde hinzugefügt.'); }
async function togglePhrase(item: any) { await api(`/control/phrases/${item.id}`, { method: 'PUT', body: JSON.stringify({ ...item, enabled: !item.enabled, category_id: item.category_id, variation_id: item.variation_id }) }); await load(); }
async function toggleCatalog(item: any) { const path = item.kind === 'category' ? `categories/${item.id}` : item.kind === 'variation' ? `variations/${item.id}` : `templates/${item.id}/toggle`; const body = item.kind === 'template' ? { enabled: !item.enabled } : { ...item, enabled: !item.enabled }; await api(`/control/${path}`, { method: 'PUT', body: JSON.stringify(body) }); await load(); }
async function openTenant(item: any) { selectedTenant.value = await api(`/control/tenants/${item.id}`); }
async function updateTenant(payload: any) { busy.value = true; try { await api(`/control/tenants/${selectedTenant.value.id}`, { method: 'PUT', body: JSON.stringify(payload) }); selectedTenant.value = await api(`/control/tenants/${selectedTenant.value.id}`); await load(); toast('Kunde wurde aktualisiert.'); } finally { busy.value = false; } }
async function saveOverride() { await api(`/control/tenants/${selectedTenant.value.id}/entitlement`, { method: 'PUT', body: JSON.stringify(overrideForm) }); toast('Leistung wurde gespeichert.'); }
async function impersonate() { await api(`/control/tenants/${selectedTenant.value.id}/impersonate`, { method: 'POST' }); location.href = '/app'; }
async function toggleUser(user: any, field: string) { await api(`/control/users/${user.id}`, { method: 'PUT', body: JSON.stringify({ [field]: !user[field] }) }); await load(); }
async function resetPassword(user: any) { await api(`/control/users/${user.id}/password-reset`, { method: 'POST' }); toast('Link zum Zurücksetzen wurde versendet.'); }
async function domainAction(domain: any, action: string) { await api(`/control/domains/${domain.id}/${action}`, { method: 'POST' }); await load(); }
async function deleteDomain(domain: any) { if (!confirm(`${domain.domain} wirklich löschen?`)) return; await api(`/control/domains/${domain.id}`, { method: 'DELETE' }); await load(); }
async function syncPlan(plan: any) { await submit(() => api(`/control/plans/${plan.id}/stripe-sync`, { method: 'POST' }), 'Tarif wurde mit Stripe synchronisiert.'); }
async function syncAllPlans() { await submit(() => api('/control/stripe/sync-plans', { method: 'POST' }), 'Alle Tarife wurden synchronisiert.'); }
async function backupAction(action: string, name?: string) { if (action === 'delete' && !confirm(`${name} wirklich löschen?`)) return; await submit(() => api(name ? `/control/backups/${name}${action === 'verify' ? '/verify' : ''}` : '/control/backups', { method: action === 'delete' ? 'DELETE' : 'POST' }), action === 'create' ? 'Backup wurde erstellt.' : action === 'verify' ? 'Backup ist vollständig.' : 'Backup wurde gelöscht.'); }
function editPage(page: any) { selectedPage.value = JSON.parse(JSON.stringify(page)); contentLocale.value = 'de'; modal.value = 'page'; }
async function savePage() { await submit(() => api(`/control/pages/${selectedPage.value.id}`, { method: 'PUT', body: JSON.stringify({ title: selectedPage.value.title, content: selectedPage.value.content, is_published: selectedPage.value.is_published }) }), 'Inhalt wurde veröffentlicht.'); }
function editSetting(item: any) { selectedSetting.value = { ...item, serialized: typeof item.value === 'object' ? JSON.stringify(item.value, null, 2) : String(item.value ?? '') }; modal.value = 'setting'; }
async function saveSetting() { let value: any = selectedSetting.value.serialized; try { value = JSON.parse(value); } catch {} await submit(() => api('/control/settings', { method: 'PUT', body: JSON.stringify({ key: selectedSetting.value.key, value }) }), 'Einstellung wurde gespeichert.'); }
async function logout() { await api('/logout', { method: 'POST' }); router.push('/login'); }
function formatDate(value: string | null) { return value ? new Intl.DateTimeFormat('de-DE', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—'; }
</script>

<template>
<div class="control-shell"><aside class="control-sidebar"><div class="control-wordmark"><b>LOOK</b><span>DO</span><small>SUPER ADMIN</small></div><nav><RouterLink v-for="item in nav" :key="item[0]" :to="`/control/${item[0]}`" :class="{ active: section === item[0] }"><span>{{ item[1] }}</span>{{ item[2] }}</RouterLink></nav><button class="sidebar-logout" @click="logout">Abmelden</button></aside>
<main class="control-main"><header class="control-header"><div><p class="eyebrow">LOOKDO VERWALTUNG</p><h1>{{ nav.find(item => item[0] === section)?.[2] }}</h1></div><div class="admin-chip"><span>SA</span><div><b>{{ me?.user?.name }}</b><small>{{ me?.user?.email }}</small></div></div></header><p v-if="error" class="alert error">{{ error }}</p><p v-if="noticeText" class="admin-toast">{{ noticeText }}</p><div v-if="!data" class="loading">Wird geladen…</div>
<template v-else><section v-if="section === 'dashboard'" class="admin-metrics"><article v-for="(value, key) in data" :key="key"><span>{{ metricLabels[String(key)] || key }}</span><strong>{{ key === 'mrr' ? `${Number(value).toFixed(2)} €` : value }}</strong></article></section>
<section v-else-if="section === 'stripe'" class="stripe-status"><article><p class="eyebrow">VERBINDUNG</p><h2>{{ data.configured ? 'Stripe verbunden' : 'Stripe nicht konfiguriert' }}</h2><p v-if="data.account">{{ data.account.id }} · {{ data.account.livemode ? 'Live-Modus' : 'Testmodus' }} · {{ data.account.country }}</p></article><article><p class="eyebrow">WEBHOOK</p><h2>{{ data.webhook_configured ? 'Bereit' : 'Fehlt' }}</h2><p>{{ data.plans_pending }} Tarife warten auf Synchronisierung.</p></article><button class="button" :disabled="busy || !data.configured" @click="syncAllPlans">Tarife synchronisieren</button></section>
<section v-else class="admin-section registry-page"><RegistryToolbar v-model:search="filters.search" :total="pager.total" :add-label="addLabels[section]" :busy="busy" @add="openAdd" @refresh="load">
<select v-if="section === 'templates' || section === 'content'" v-model="filters.secondary"><option value="">Alle Typen</option><option v-if="section === 'templates'" value="category">Kategorien</option><option v-if="section === 'templates'" value="variation">Varianten</option><option v-if="section === 'templates'" value="template">Vorlagen</option><option v-if="section === 'content'" value="page">Seiten</option><option v-if="section === 'content'" value="setting">Einstellungen</option></select>
<select v-else-if="section === 'users'" v-model="filters.secondary"><option value="">Alle Rollen</option><option value="super_admin">Super Admin</option><option value="client">Kundenbenutzer</option></select><select v-else-if="section === 'subscriptions'" v-model="filters.secondary"><option value="">Alle Anbieter</option><option value="stripe">Stripe</option><option value="manual">Manuell</option></select><select v-else-if="section === 'domains'" v-model="filters.secondary"><option value="">Alle Typen</option><option value="platform">Plattform</option><option value="custom">Eigene Domain</option></select><select v-else-if="section === 'ai'" v-model="filters.secondary"><option value="">Alle Sprachen</option><option value="de">Deutsch</option><option value="en">Englisch</option><option value="ru">Russisch</option><option value="uk">Ukrainisch</option></select><select v-else-if="section === 'classifications'" v-model="filters.secondary"><option value="">Alle Quellen</option><option value="dictionary">Wörterbuch</option><option value="fuzzy">Ähnlichkeit</option><option value="ai">KI</option><option value="fallback">Standard</option></select>
<select v-if="statusOptions[section]" v-model="filters.status"><option value="">Alle Status</option><option v-for="option in statusOptions[section]" :key="option[0]" :value="option[0]">{{ option[1] }}</option></select><select v-model="filters.sort"><option v-for="option in sortOptions[section] || []" :key="option[0]" :value="option[0]">{{ option[1] }}</option></select><button type="button" class="sort-direction" @click="filters.direction = filters.direction === 'asc' ? 'desc' : 'asc'">{{ filters.direction === 'asc' ? '↑' : '↓' }}</button><select v-model.number="filters.per_page"><option :value="10">10</option><option :value="25">25</option><option :value="50">50</option><option :value="100">100</option></select></RegistryToolbar>
<div class="admin-table-wrap"><table><thead v-if="section === 'tenants'"><tr><th>Kunde</th><th>Inhaber</th><th>Vorlage</th><th>Domain</th><th>Tarif</th><th>Status</th></tr></thead><tbody v-if="section === 'tenants'"><tr v-for="item in rows" :key="item.id" class="clickable" @click="openTenant(item)"><td><b>{{ item.name }}</b><small>{{ item.slug }}</small></td><td>{{ item.users?.[0]?.email || '—' }}</td><td>{{ item.business_profile?.variation?.name?.de || item.business_profile?.variation?.code || 'Standard' }}</td><td>{{ item.primary_domain?.domain || '—' }}</td><td>{{ item.current_subscription?.plan?.name?.de || item.current_subscription?.plan?.code || '—' }}</td><td><span class="table-status" :class="item.status">{{ item.status === 'active' ? 'aktiv' : item.status }}</span></td></tr></tbody>
<thead v-if="section === 'users'"><tr><th>Benutzer</th><th>Kunde</th><th>Rolle</th><th>Letzte Anmeldung</th><th>Status</th><th>Aktionen</th></tr></thead><tbody v-if="section === 'users'"><tr v-for="item in rows" :key="item.id"><td><b>{{ item.name }}</b><small>{{ item.email }}</small></td><td>{{ item.tenants?.map((tenant:any) => tenant.name).join(', ') || 'Plattform' }}</td><td>{{ item.is_super_admin ? 'Super Admin' : (item.tenants?.[0]?.pivot?.role || 'Benutzer') }}</td><td>{{ formatDate(item.last_login_at) }}</td><td>{{ item.is_active ? 'aktiv' : 'gesperrt' }}</td><td class="table-actions"><button @click="toggleUser(item, 'is_active')">{{ item.is_active ? 'Sperren' : 'Aktivieren' }}</button><button @click="resetPassword(item)">Zugang</button><button @click="toggleUser(item, 'is_super_admin')">{{ item.is_super_admin ? 'Admin entziehen' : 'Admin machen' }}</button></td></tr></tbody>
<thead v-if="section === 'subscriptions'"><tr><th>Kunde</th><th>Tarif</th><th>Anbieter</th><th>Status</th><th>Periodenende</th><th>Rabatt</th><th>Provider-ID</th></tr></thead><tbody v-if="section === 'subscriptions'"><tr v-for="item in rows" :key="item.id"><td><b>{{ item.tenant?.name }}</b><small>{{ item.tenant?.slug }}</small></td><td>{{ item.plan?.name?.de || item.plan?.code }}</td><td>{{ item.provider === 'manual' ? 'Manuell' : item.provider }}</td><td>{{ item.complimentary ? 'kostenlos' : item.status }}</td><td>{{ formatDate(item.current_period_end) }}</td><td>{{ item.discount_percent }}%</td><td><small>{{ item.provider_subscription_id || '—' }}</small></td></tr></tbody>
<thead v-if="section === 'plans'"><tr><th>Tarif</th><th>Monat</th><th>Jahr</th><th>Kunden</th><th>Sichtbarkeit</th><th>Stripe</th><th>Aktionen</th></tr></thead><tbody v-if="section === 'plans'"><tr v-for="item in rows" :key="item.id"><td><b>{{ item.name?.de || item.code }}</b><small>{{ item.code }}</small></td><td>{{ item.price_monthly }} {{ item.currency }}</td><td>{{ item.price_yearly || '—' }} {{ item.currency }}</td><td>{{ item.subscriptions_count }}</td><td>{{ item.is_active ? (item.is_public ? 'öffentlich' : 'intern') : 'archiviert' }}</td><td>{{ item.stripe_synced_at ? 'synchron' : (item.stripe_sync_error || 'offen') }}</td><td class="table-actions"><button @click="editPlan(item)">Bearbeiten</button><button @click="syncPlan(item)">Stripe</button></td></tr></tbody>
<thead v-if="section === 'domains'"><tr><th>Domain</th><th>Kunde</th><th>Typ</th><th>DNS</th><th>SSL</th><th>Geprüft</th><th>Aktionen</th></tr></thead><tbody v-if="section === 'domains'"><tr v-for="item in rows" :key="item.id"><td><b>{{ item.domain }}</b></td><td>{{ item.tenant?.name }}</td><td>{{ item.type === 'custom' ? 'Eigene Domain' : 'Plattform' }}</td><td>{{ item.status }}</td><td>{{ item.ssl_status || '—' }}</td><td>{{ formatDate(item.last_checked_at) }}</td><td class="table-actions"><button v-if="item.type === 'custom'" @click="domainAction(item, 'verify')">Prüfen</button><button v-if="item.status === 'ssl_pending'" @click="domainAction(item, 'activate')">Aktivieren</button><button v-if="item.type === 'custom' && item.status === 'active'" @click="domainAction(item, 'disable')">Deaktivieren</button><button v-if="item.type === 'custom' && item.status !== 'active'" class="danger" @click="deleteDomain(item)">Löschen</button></td></tr></tbody>
<thead v-if="section === 'templates'"><tr><th>Typ</th><th>Name</th><th>Code</th><th>Kategorie / Eltern</th><th>Priorität / Version</th><th>Status</th><th>Aktion</th></tr></thead><tbody v-if="section === 'templates'"><tr v-for="item in rows" :key="`${item.kind}-${item.id}`"><td>{{ item.kind === 'category' ? 'Kategorie' : item.kind === 'variation' ? 'Variante' : 'Vorlage' }}</td><td><b>{{ item.label }}</b></td><td><code>{{ item.code }}</code></td><td>{{ item.categoryLabel || item.parent_code || '—' }}</td><td>{{ item.kind === 'template' ? `v${item.version}` : (item.priority ?? item.sort_order) }}</td><td>{{ item.enabled ? 'aktiv' : 'inaktiv' }}</td><td class="table-actions"><button @click="toggleCatalog(item)">{{ item.enabled ? 'Deaktivieren' : 'Aktivieren' }}</button></td></tr></tbody>
<thead v-if="section === 'ai'"><tr><th>Begriff</th><th>Sprache</th><th>Kategorie</th><th>Variante</th><th>Gewichtung</th><th>Status</th><th>Aktion</th></tr></thead><tbody v-if="section === 'ai'"><tr v-for="item in rows" :key="item.id"><td><b>{{ item.phrase }}</b><small>{{ item.normalized_phrase }}</small></td><td>{{ item.locale.toUpperCase() }}</td><td>{{ item.category?.name?.de || item.category?.code }}</td><td>{{ item.variation?.name?.de || item.variation?.code || 'Standard' }}</td><td>{{ item.weight }}</td><td>{{ item.enabled ? 'aktiv' : 'inaktiv' }}</td><td class="table-actions"><button @click="togglePhrase(item)">{{ item.enabled ? 'Deaktivieren' : 'Aktivieren' }}</button></td></tr></tbody>
<thead v-if="section === 'classifications'"><tr><th>Datum</th><th>Eingabe</th><th>Kunde</th><th>Ergebnis</th><th>Sicherheit</th><th>Quelle</th><th>Bestätigt</th></tr></thead><tbody v-if="section === 'classifications'"><tr v-for="item in rows" :key="item.id"><td>{{ formatDate(item.created_at) }}</td><td><b>{{ item.original_text }}</b><small>{{ item.normalized_text }}</small></td><td>{{ item.tenant?.name || 'Registrierung' }}</td><td>{{ item.category?.name?.de || item.category?.code || 'Standard' }}<small>{{ item.variation?.name?.de || item.variation?.code || 'allgemein' }}</small></td><td>{{ Math.round(Number(item.confidence) * 100) }}%</td><td>{{ item.source }}<small>{{ item.ai_model }}</small></td><td>{{ item.confirmed_by_user_at ? 'ja' : 'nein' }}</td></tr></tbody>
<thead v-if="section === 'content'"><tr><th>Typ</th><th>Name</th><th>Schlüssel / URL</th><th>Status / Wert</th><th>Aktion</th></tr></thead><tbody v-if="section === 'content'"><tr v-for="item in rows" :key="item.id"><td>{{ item.kind === 'page' ? 'Inhaltsseite' : 'Einstellung' }}</td><td><b>{{ item.label }}</b></td><td><code>{{ item.kind === 'page' ? `/${item.key}` : item.key }}</code></td><td>{{ item.kind === 'page' ? (item.is_published ? 'veröffentlicht' : 'Entwurf') : String(typeof item.value === 'object' ? JSON.stringify(item.value) : item.value).slice(0, 80) }}</td><td class="table-actions"><button @click="item.kind === 'page' ? editPage(item) : editSetting(item)">Bearbeiten</button></td></tr></tbody>
<thead v-if="section === 'backups'"><tr><th>Backup</th><th>Erstellt</th><th>Dateien</th><th>Aktionen</th></tr></thead><tbody v-if="section === 'backups'"><tr v-for="item in rows" :key="item.name"><td><b>{{ item.name }}</b></td><td>{{ formatDate(item.created_at) }}</td><td>{{ Object.keys(item.files || {}).length }}</td><td class="table-actions"><button @click="backupAction('verify', item.name)">Prüfen</button><button class="danger" @click="backupAction('delete', item.name)">Löschen</button></td></tr></tbody>
<thead v-if="section === 'audit'"><tr><th>Datum</th><th>Aktion</th><th>Benutzer</th><th>Kunde</th><th>Objekt</th><th>IP-Adresse</th></tr></thead><tbody v-if="section === 'audit'"><tr v-for="item in rows" :key="item.id"><td>{{ formatDate(item.created_at) }}</td><td><b>{{ item.action }}</b></td><td>{{ item.actor_id || 'System' }}</td><td>{{ item.tenant_id || '—' }}</td><td>{{ item.subject_type ? `${item.subject_type.split('\\').pop()} #${item.subject_id}` : '—' }}</td><td>{{ item.ip_address || '—' }}</td></tr></tbody><tbody v-if="!rows.length"><tr><td colspan="9" class="empty-table">Keine passenden Einträge gefunden.</td></tr></tbody></table></div>
<div v-if="section === 'backups'" class="registry-context"><span>Speicherort: {{ data.path }}</span><span>Aufbewahrung: {{ data.keep }}</span><button class="button" :disabled="busy" @click="backupAction('create')">＋ Backup erstellen</button></div><AdminPagination :current="pager.current" :last="pager.last" :from="pager.from" :to="pager.to" :total="pager.total" @change="changePage" /></section></template></main>
<aside v-if="selectedTenant" class="drawer"><button class="drawer-close" @click="selectedTenant = null">×</button><p class="eyebrow">KUNDE #{{ selectedTenant.id }}</p><h2>{{ selectedTenant.name }}</h2><p>{{ selectedTenant.slug }}.lookdo.app</p><dl><div><dt>Inhaber</dt><dd>{{ selectedTenant.users?.[0]?.email }}</dd></div><div><dt>Tarif</dt><dd>{{ selectedTenant.current_subscription?.plan?.name?.de || '—' }}</dd></div><div><dt>Status</dt><dd>{{ selectedTenant.status }}</dd></div></dl><button class="button full" @click="impersonate">Kundenkonto öffnen</button><div class="drawer-actions"><button class="button ghost" @click="updateTenant({ status: selectedTenant.status === 'active' ? 'suspended' : 'active' })">{{ selectedTenant.status === 'active' ? 'Sperren' : 'Aktivieren' }}</button></div><h3>Tarif ändern</h3><select v-model.number="selectedTenant.current_subscription.plan_id"><option v-for="plan in lookups.plans" :key="plan.id" :value="plan.id">{{ plan.name.de || plan.code }}</option></select><button class="button ghost small" @click="updateTenant({ plan_id: selectedTenant.current_subscription.plan_id, complimentary: selectedTenant.current_subscription.complimentary, discount_percent: selectedTenant.current_subscription.discount_percent })">Tarif speichern</button><h3>Leistung überschreiben</h3><input v-model="overrideForm.key" placeholder="Schlüssel"><input v-model="overrideForm.value" placeholder="Wert"><button class="button ghost small" @click="saveOverride">Speichern</button><h3>Domains</h3><p v-for="domain in selectedTenant.domains" :key="domain.id">{{ domain.domain }} · {{ domain.status }}</p></aside>
<AdminModal v-if="modal === 'tenant'" title="Kunden anlegen" wide @close="modal = ''"><form class="modal-form form-grid" @submit.prevent="createTenant"><label>Unternehmen<input v-model="tenantForm.name" required></label><label>Subdomain<input v-model="tenantForm.slug" placeholder="automatisch"></label><label>Name des Inhabers<input v-model="tenantForm.owner_name" required></label><label>E-Mail des Inhabers<input v-model="tenantForm.owner_email" type="email" required></label><label>Temporäres Passwort<input v-model="tenantForm.owner_password" type="password" minlength="10" required></label><label>Tarif<select v-model.number="tenantForm.plan_id" required><option :value="null">Bitte wählen</option><option v-for="plan in lookups.plans" :key="plan.id" :value="plan.id">{{ plan.name.de || plan.code }}</option></select></label><label>Geschäftsvorlage<select v-model.number="tenantForm.variation_id"><option :value="null">Standardvorlage</option><option v-for="variation in lookups.variations" :key="variation.id" :value="variation.id">{{ variation.name.de || variation.code }}</option></select></label><label class="check"><input v-model="tenantForm.complimentary" type="checkbox"> Kostenlos</label><label class="wide">Tätigkeitsbeschreibung<textarea v-model="tenantForm.business_description"></textarea></label><div class="modal-actions wide"><button type="button" class="button ghost" @click="modal = ''">Abbrechen</button><button class="button" :disabled="busy">Kunden anlegen</button></div></form></AdminModal>
<AdminModal v-if="modal === 'plan'" :title="editingPlanId ? 'Tarif bearbeiten' : 'Tarif anlegen'" wide @close="modal = ''"><form class="modal-form form-grid" @submit.prevent="savePlan"><label>Code<input v-model="planForm.code" required></label><label>Monatspreis<input v-model.number="planForm.price_monthly" type="number" required></label><label>Jahrespreis<input v-model.number="planForm.price_yearly" type="number"></label><label>Währung<input v-model="planForm.currency" maxlength="3" required></label><label>Deutscher Name<input v-model="planForm.name.de" required></label><label>Russischer Name<input v-model="planForm.name.ru" required></label><label>Testtage<input v-model.number="planForm.trial_days" type="number"></label><label>Reihenfolge<input v-model.number="planForm.sort_order" type="number"></label><label class="check"><input v-model="planForm.is_active" type="checkbox"> Aktiv</label><label class="check"><input v-model="planForm.is_public" type="checkbox"> Öffentlich</label><label class="wide">Deutsche Beschreibung<textarea v-model="planForm.description.de"></textarea></label><div class="modal-actions wide"><button type="button" class="button ghost" @click="modal = ''">Abbrechen</button><button class="button" :disabled="busy">Speichern</button></div></form></AdminModal>
<AdminModal v-if="modal === 'phrase'" title="Geschäftsbegriff hinzufügen" @close="modal = ''"><form class="modal-form" @submit.prevent="savePhrase"><label>Sprache<select v-model="phraseForm.locale"><option value="de">Deutsch</option><option value="en">Englisch</option><option value="ru">Russisch</option><option value="uk">Ukrainisch</option></select></label><label>Variante<select v-model.number="phraseForm.variation_id" required @change="choosePhraseVariation"><option :value="null">Bitte wählen</option><option v-for="variation in lookups.variations" :key="variation.id" :value="variation.id">{{ variation.name.de || variation.name.ru || variation.code }}</option></select></label><label>Begriff<input v-model="phraseForm.phrase" required></label><label>Gewichtung<input v-model.number="phraseForm.weight" type="number" min="0.1" max="5" step="0.1"></label><div class="modal-actions"><button type="button" class="button ghost" @click="modal = ''">Abbrechen</button><button class="button" :disabled="busy">Hinzufügen</button></div></form></AdminModal>
<AdminModal v-if="modal === 'catalog'" title="Vorlagen-Eintrag anlegen" wide @close="modal = ''"><div class="type-tabs"><button v-for="kind in [['category','Kategorie'],['variation','Variante'],['template','Vorlage']]" :key="kind[0]" :class="{ active: catalogKind === kind[0] }" @click="catalogKind = kind[0]">{{ kind[1] }}</button></div><form class="modal-form form-grid" @submit.prevent="saveCatalog"><template v-if="catalogKind === 'category'"><label>Code<input v-model="categoryForm.code" required></label><label>Reihenfolge<input v-model.number="categoryForm.sort_order" type="number"></label><label>Deutsch<input v-model="categoryForm.name.de" required></label><label>Russisch<input v-model="categoryForm.name.ru" required></label></template><template v-if="catalogKind === 'variation'"><label>Kategorie<select v-model.number="variationForm.category_id" required><option v-for="category in lookups.categories" :key="category.id" :value="category.id">{{ category.name.de || category.code }}</option></select></label><label>Code<input v-model="variationForm.code" required></label><label>Deutsch<input v-model="variationForm.name.de" required></label><label>Russisch<input v-model="variationForm.name.ru" required></label><label>Vorlagen-Code<input v-model="variationForm.template_code"></label><label>Priorität<input v-model.number="variationForm.priority" type="number"></label></template><template v-if="catalogKind === 'template'"><label>Kategorie<select v-model.number="templateForm.category_id"><option :value="null">Keine</option><option v-for="category in lookups.categories" :key="category.id" :value="category.id">{{ category.name.de || category.code }}</option></select></label><label>Variante<select v-model.number="templateForm.variation_id"><option :value="null">Keine</option><option v-for="variation in lookups.variations" :key="variation.id" :value="variation.id">{{ variation.name.de || variation.code }}</option></select></label><label>Code<input v-model="templateForm.code" required></label><label>Übergeordneter Code<input v-model="templateForm.parent_code"></label><label>Deutscher Name<input v-model="templateForm.name.de" required></label><label>Version<input v-model.number="templateForm.version" type="number"></label><label class="wide">Konfiguration (JSON)<textarea v-model="templateForm.configuration" rows="10" required></textarea></label></template><div class="modal-actions wide"><button type="button" class="button ghost" @click="modal = ''">Abbrechen</button><button class="button" :disabled="busy">Anlegen</button></div></form></AdminModal>
<AdminModal v-if="modal === 'page' && selectedPage" title="Inhaltsseite bearbeiten" wide @close="modal = ''"><form class="modal-form" @submit.prevent="savePage"><div class="editor-head"><code>/{{ selectedPage.key }}</code><label class="check"><input v-model="selectedPage.is_published" type="checkbox"> Veröffentlicht</label></div><div class="type-tabs"><button v-for="locale in [['de','Deutsch'],['en','English'],['ru','Русский'],['uk','Українська']]" :key="locale[0]" type="button" :class="{ active: contentLocale === locale[0] }" @click="contentLocale = locale[0]">{{ locale[1] }}</button></div><label>Titel<input v-model="selectedPage.title[contentLocale]"></label><label>Inhalt<RichContentEditor v-model="selectedPage.content[contentLocale]" /></label><div class="modal-actions"><button type="button" class="button ghost" @click="modal = ''">Abbrechen</button><button class="button" :disabled="busy">Speichern</button></div></form></AdminModal>
<AdminModal v-if="modal === 'setting' && selectedSetting" title="Systemeinstellung bearbeiten" @close="modal = ''"><form class="modal-form" @submit.prevent="saveSetting"><label>Schlüssel<input :value="selectedSetting.key" disabled></label><label>Wert<textarea v-model="selectedSetting.serialized" rows="10"></textarea></label><div class="modal-actions"><button type="button" class="button ghost" @click="modal = ''">Abbrechen</button><button class="button" :disabled="busy">Speichern</button></div></form></AdminModal>
</div>
</template>
