<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { api } from '../api';
import { locale, tr } from '../i18n';
const props=defineProps<{pricingOnly?:boolean}>();
const plans=ref<any[]>([]);const categories=ref<any[]>([]);
onMounted(async()=>{const data=await api('/platform');plans.value=data.plans;categories.value=data.categories});
const steps=['step1','step2','step3','step4','step5','step6'];
const faqs={de:[['Müssen Kunden etwas installieren?','Nein. Die App öffnet sich direkt über einen Link und kann optional zum Startbildschirm hinzugefügt werden.'],['Kann ich meine eigene Domain nutzen?','Ja. Jede App startet sofort auf einer LOOKDO Subdomain; eine eigene Domain kann zusätzlich verbunden werden.'],['Berechnet LOOKDO automatisch einen Preis?','Nein. Der Fachbetrieb prüft die Fotos und antwortet persönlich.']],en:[['Do customers install anything?','No. The app opens from a link and can optionally be added to the home screen.'],['Can I use my own domain?','Yes. Every app starts on a LOOKDO subdomain and can also use a custom domain.'],['Does LOOKDO calculate a price?','No. The specialist reviews the photos and responds personally.']],ru:[['Клиенту нужно что-то устанавливать?','Нет. Приложение открывается по ссылке, при желании его можно добавить на главный экран.'],['Можно использовать свой домен?','Да. Сначала приложение работает на поддомене LOOKDO, затем можно подключить собственный домен.'],['LOOKDO рассчитывает цену?','Нет. Мастер лично изучает фотографии и отвечает клиенту.']]};
</script>
<template>
  <div>
    <section v-if="!props.pricingOnly" class="hero section">
      <div class="hero-copy"><p class="eyebrow">{{tr('eyebrow')}}</p><h1><span>LOOK.</span> DO.</h1><h2>{{tr('hero')}}</h2><p class="lead">{{tr('heroText')}}</p><div class="hero-actions"><RouterLink class="button" :to="`/${locale}/register`">{{tr('create')}} →</RouterLink><a class="button ghost" href="#demo">{{tr('demo')}}</a></div><div class="trust-row"><span>✓ {{tr('noInstall')}}</span><span>✓ {{tr('humanAnswer')}}</span><span>✓ {{tr('ownDomain')}}</span></div></div>
      <div id="demo" class="phone-stage"><div class="phone-glow"></div><div class="phone"><img :src="'/brand/leonid-demo.png'" alt="LOOKDO tenant app example"></div><div class="floating-card card-one"><b>4</b><span>{{tr('photoCard')}}</span></div><div class="floating-card card-two"><b>↗</b><span>{{tr('directBusiness')}}</span></div></div>
    </section>
    <section v-if="!props.pricingOnly" class="statement section"><p class="eyebrow">LOOKDO DIFFERENCE</p><h2>{{tr('whyTitle')}}</h2><div class="metric-grid"><article><strong>01</strong><h3>{{tr('noInstall')}}</h3><p>{{tr('linkDomain')}}</p></article><article><strong>02</strong><h3>{{tr('humanAnswer')}}</h3><p>{{tr('noEstimate')}}</p></article><article><strong>03</strong><h3>{{tr('allDevices')}}</h3><p>{{tr('webFuture')}}</p></article></div></section>
    <section v-if="!props.pricingOnly" id="how" class="section muted-section"><div class="section-heading"><p class="eyebrow">{{tr('how')}}</p><h2>{{tr('howTitle')}}</h2></div><div class="steps"><article v-for="(step,index) in steps" :key="step"><span>{{String(index+1).padStart(2,'0')}}</span><h3>{{tr(step)}}</h3></article></div></section>
    <section v-if="!props.pricingOnly" id="audience" class="section"><div class="section-heading"><p class="eyebrow">{{tr('forWhom')}}</p><h2>{{tr('categories')}}</h2></div><div class="category-grid"><article v-for="category in categories" :key="category.id"><span class="category-icon">◎</span><h3>{{category.name}}</h3><p>{{category.variations.map((v:any)=>v.name).join(' · ')}}</p></article><article><span class="category-icon">＋</span><h3>{{tr('moreActivities')}}</h3><p>{{tr('moreActivitiesText')}}</p></article></div></section>
    <section v-if="!props.pricingOnly" id="features" class="section feature-band"><div><p class="eyebrow">{{tr('features')}}</p><h2>{{tr('connectionTitle')}}</h2></div><div class="feature-list"><div><b>01</b><span>{{tr('photosVideos')}}</span></div><div><b>02</b><span>{{tr('requiredPhone')}}</span></div><div><b>03</b><span>{{tr('messagesPush')}}</span></div><div><b>04</b><span>{{tr('beforeAfter')}}</span></div><div><b>05</b><span>{{tr('reviews')}}</span></div><div><b>06</b><span>{{tr('brandDomain')}}</span></div></div></section>
    <section id="pricing" class="section pricing-section"><div class="section-heading centered"><p class="eyebrow">{{tr('pricing')}}</p><h2>{{tr('pricingTitle')}}</h2><p>{{tr('pricingText')}}</p></div><div class="pricing-grid"><article v-for="plan in plans" :key="plan.id" class="price-card" :class="{featured:plan.badge}"><span v-if="plan.badge" class="badge">{{plan.badge}}</span><h3>{{plan.name}}</h3><p>{{plan.description}}</p><div class="price"><strong>{{plan.price_monthly}} €</strong><span>{{tr('perMonth')}}</span></div><ul><li v-for="(value,key) in plan.entitlements" :key="key">✓ {{String(key).replaceAll('_',' ')}}: {{value}}</li></ul><RouterLink class="button full" :to="`/${locale}/register?plan=${plan.id}`">{{tr('create')}}</RouterLink></article></div></section>
    <section v-if="!props.pricingOnly" class="section faq-section"><div class="section-heading"><p class="eyebrow">{{tr('faq')}}</p><h2>{{tr('faqTitle')}}</h2></div><div class="faq-list"><details v-for="item in faqs[locale]" :key="item[0]"><summary>{{item[0]}}<span>＋</span></summary><p>{{item[1]}}</p></details></div></section>
    <section v-if="!props.pricingOnly" class="section final-cta"><p class="eyebrow">LOOK. DO.</p><h2>{{tr('ctaTitle')}}</h2><p>{{tr('ctaText')}}</p><RouterLink class="button light" :to="`/${locale}/register`">{{tr('create')}} →</RouterLink></section>
  </div>
</template>
