<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue';import { useRoute,useRouter } from 'vue-router';import { api } from '../api';import { tr } from '../i18n';
const route=useRoute();const router=useRouter();const me=ref<any>(null);const data=ref<any>(null);const plans=ref<any[]>([]);const busy=ref(false);const error=ref('');const notice=ref('');const section=computed(()=>String(route.params.section||'overview'));const tenantId=computed(()=>me.value?.tenants?.[0]?.id);
const profile=reactive<any>({});const customDomain=ref('');
async function load(){try{me.value=await api('/me');if(!me.value.user)return router.push('/login');if(me.value.user.is_super_admin&&!me.value.impersonating)return router.push('/control');const platform=await api('/platform');plans.value=platform.plans;if(tenantId.value){data.value=await api(`/tenant/${tenantId.value}`);Object.assign(profile,data.value.tenant.profile||{}, {name:data.value.tenant.name});}}catch(e:any){if(String(e.message).includes('Unauthenticated'))router.push('/login');else error.value=e.message}}
onMounted(load);
async function saveProfile(){busy.value=true;error.value='';try{await api(`/tenant/${tenantId.value}/profile`,{method:'PUT',body:JSON.stringify(profile)});notice.value=tr('saved');await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function addDomain(){busy.value=true;error.value='';try{await api(`/tenant/${tenantId.value}/domains`,{method:'POST',body:JSON.stringify({domain:customDomain.value})});customDomain.value='';notice.value=tr('domainAdded');await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function verify(domain:any){busy.value=true;try{await api(`/tenant/${tenantId.value}/domains/${domain.id}/verify`,{method:'POST'});await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function checkout(plan:any){busy.value=true;try{const result=await api(`/tenant/${tenantId.value}/checkout`,{method:'POST',body:JSON.stringify({plan_id:plan.id,cycle:'monthly'})});location.href=result.checkout_url}catch(e:any){error.value=e.message;busy.value=false}}
async function logout(){await api('/logout',{method:'POST'});router.push('/login')}
async function stop(){await api('/impersonation/stop',{method:'POST'});location.href='/control'}
const nav=computed(()=>[['overview','⌂',tr('overview')],['business','◇',tr('business')],['domain','◎',tr('domain')],['billing','€',tr('plan')]]);
</script>
<template><div class="tenant-shell"><aside class="tenant-sidebar"><div class="brand"><span class="brand-mark">L·D</span><span>LOOKDO<small>TENANT</small></span></div><div v-if="data" class="tenant-identity"><div class="tenant-avatar">{{data.tenant.name.slice(0,2).toUpperCase()}}</div><div><b>{{data.tenant.name}}</b><small>{{data.tenant.slug}}.lookdo.app</small></div></div><nav><RouterLink v-for="item in nav" :key="item[0]" :to="`/app/${item[0]}`" :class="{active:section===item[0]}"><span>{{item[1]}}</span>{{item[2]}}</RouterLink></nav><button v-if="me?.impersonating" class="support-exit" @click="stop">← {{tr('returnAdmin')}}</button><button class="sidebar-logout" @click="logout">{{tr('logout')}}</button></aside><main class="tenant-content"><header class="mobile-app-header"><div class="brand"><span class="brand-mark">L·D</span><span>LOOKDO</span></div><button @click="logout">↗</button></header><div v-if="!data" class="loading">LOOKDO…</div><template v-else><div class="content-heading"><div><p class="eyebrow">{{data.tenant.name}}</p><h1>{{nav.find(x=>x[0]===section)?.[2]}}</h1></div><a class="status-pill" :href="data.platform_url" target="_blank"><i></i> {{data.tenant.status}} ↗</a></div><p v-if="error" class="alert error">{{error}}</p><p v-if="notice" class="alert success">{{notice}}</p>
<section v-if="section==='overview'" class="dashboard-grid"><article class="welcome-card"><div><p class="eyebrow">{{tr('yourApp')}}</p><h2>{{data.tenant.onboarding_completed_at?tr('workspaceReady'):tr('finishSetup')}}</h2><p>{{tr('permanentAddress')}}</p><a :href="data.platform_url" target="_blank">{{data.platform_url}} ↗</a></div><div class="progress-ring"><strong>{{data.tenant.onboarding_completed_at?'100':'60'}}%</strong><span>{{tr('setup')}}</span></div></article><article class="dashboard-card"><span class="card-icon">◎</span><h3>{{tr('businessTemplate')}}</h3><b>{{data.tenant.business_profile?.variation?.name?.[data.tenant.locale]||data.tenant.business_profile?.variation?.code}}</b><RouterLink to="/app/business">{{tr('viewDetails')}} →</RouterLink></article><article class="dashboard-card"><span class="card-icon">€</span><h3>{{tr('subscription')}}</h3><b>{{data.tenant.current_subscription?.plan?.name?.[data.tenant.locale]||tr('notActive')}}</b><span>{{data.tenant.current_subscription?.status}}</span><RouterLink to="/app/billing">{{tr('manage')}} →</RouterLink></article><article class="dashboard-card"><span class="card-icon">↗</span><h3>{{tr('customDomain')}}</h3><b>{{data.tenant.primary_domain?.domain}}</b><span>{{data.tenant.primary_domain?.status}}</span><RouterLink to="/app/domain">{{tr('manage')}} →</RouterLink></article><article class="coming-card"><p class="eyebrow">{{tr('nextStage')}}</p><h3>{{tr('nextFeatures')}}</h3><p>{{tr('nextFeaturesText')}}</p></article></section>
<section v-if="section==='business'" class="settings-card"><div class="settings-title"><h2>{{tr('businessProfile')}}</h2><p>{{tr('businessProfileText')}}</p></div><form class="form-grid" @submit.prevent="saveProfile"><label class="wide">{{tr('businessName')}}<input v-model="profile.name" required></label><label>{{tr('contactPerson')}}<input v-model="profile.contact_name"></label><label>{{tr('email')}}<input v-model="profile.email" type="email"></label><label>{{tr('phone')}}<input v-model="profile.phone"></label><label>{{tr('city')}}<input v-model="profile.city"></label><label>{{tr('street')}}<input v-model="profile.street"></label><label>{{tr('postalCode')}}<input v-model="profile.postal_code"></label><label>{{tr('primaryColour')}}<input v-model="profile.primary_color" type="color"></label><label>{{tr('secondaryColour')}}<input v-model="profile.secondary_color" type="color"></label><button class="button" :disabled="busy">{{tr('saveProfile')}}</button></form><div class="template-summary"><p class="eyebrow">{{tr('activeTemplate')}}</p><h3>{{data.tenant.business_profile?.variation?.name?.[data.tenant.locale]}}</h3><code>{{data.tenant.business_profile?.template?.code}}</code><p>{{data.tenant.business_description}}</p></div></section>
<section v-if="section==='domain'" class="settings-card"><div class="settings-title"><h2>{{tr('domains')}}</h2><p>{{tr('domainText')}}</p></div><div class="domain-list"><article v-for="domain in data.tenant.domains" :key="domain.id"><div><b>{{domain.domain}}</b><span>{{domain.type}} · {{domain.status}}<template v-if="domain.ssl_status"> · SSL {{domain.ssl_status}}</template></span></div><button v-if="domain.type==='custom'&&domain.status!=='active'" class="button ghost small" :disabled="busy" @click="verify(domain)">{{tr('checkDns')}}</button><span v-if="domain.is_primary" class="badge">{{tr('primary')}}</span></article></div><form class="inline-form" @submit.prevent="addDomain"><label>{{tr('connectDomain')}}<input v-model="customDomain" placeholder="example.de" required></label><button class="button" :disabled="busy">{{tr('addDomain')}}</button></form><div class="dns-help"><b>{{tr('dnsInstruction')}}</b><p>{{tr('dnsText')}}</p></div></section>
<section v-if="section==='billing'" class="settings-card"><div class="settings-title"><h2>{{tr('planSubscription')}}</h2><p>{{tr('planBackend')}}</p></div><div v-if="data.tenant.current_subscription" class="current-plan"><div><span>{{tr('currentPlan')}}</span><h3>{{data.tenant.current_subscription.plan?.name?.[data.tenant.locale]}}</h3><p>{{data.tenant.current_subscription.status}}<template v-if="data.tenant.current_subscription.complimentary"> · complimentary</template></p></div><strong>{{data.tenant.current_subscription.plan?.price_monthly}} €<small>{{tr('month')}}</small></strong></div><div class="mini-plans"><article v-for="plan in plans" :key="plan.id"><div><h3>{{plan.name}}</h3><p>{{plan.description}}</p></div><strong>{{plan.price_monthly}} €</strong><button class="button small" :disabled="busy" @click="checkout(plan)">{{tr('choose')}}</button></article></div></section>
</template></main><nav class="tenant-mobile-nav"><RouterLink v-for="item in nav" :key="item[0]" :to="`/app/${item[0]}`" :class="{active:section===item[0]}"><span>{{item[1]}}</span><small>{{item[2]}}</small></RouterLink></nav></div></template>
