<script setup lang="ts">
import { computed,onMounted,reactive,ref } from 'vue';import { useRoute,useRouter } from 'vue-router';import { api } from '../api';import { locale,tr } from '../i18n';
const route=useRoute();const router=useRouter();const me=ref<any>(null);const data=ref<any>(null);const plans=ref<any[]>([]);const busy=ref(false);const error=ref('');const notice=ref('');const section=computed(()=>String(route.params.section||'overview'));const tenantId=computed(()=>me.value?.tenants?.[0]?.id);
const profile=reactive<any>({});const customDomain=ref('');const billingCycle=ref<'monthly'|'yearly'>('monthly');const billingCurrency=ref<'EUR'|'RUB'|'UAH'>('EUR');
const subscription=computed(()=>data.value?.tenant?.current_subscription);const paymentRequired=computed(()=>!subscription.value?.complimentary&&['incomplete','past_due'].includes(subscription.value?.status));
const socialImageReady=computed(()=>Boolean(data.value?.tenant?.profile?.social_image_path));const setupPercent=computed(()=>50+(socialImageReady.value?25:0)+(!paymentRequired.value?25:0));
function planName(plan:any){const value=plan?.name;return typeof value==='object'?(value[locale.value]||value.de||Object.values(value)[0]):value}
function planDescription(plan:any){const value=plan?.description;return typeof value==='object'?(value[locale.value]||value.de||Object.values(value)[0]):value}
function planPrice(plan:any){return plan?.prices?.[billingCurrency.value]?.[billingCycle.value]??null}
function money(amount:any,currency=billingCurrency.value){return amount===null||amount===undefined?'—':new Intl.NumberFormat(locale.value,{style:'currency',currency,maximumFractionDigits:2}).format(Number(amount))}
async function load(){try{me.value=await api('/me');if(!me.value.user)return router.push('/login');if(me.value.user.is_super_admin&&!me.value.impersonating)return router.push('/control');const platform=await api('/platform');plans.value=platform.plans;if(tenantId.value){data.value=await api(`/tenant/${tenantId.value}`);Object.assign(profile,data.value.tenant.profile||{}, {name:data.value.tenant.name,locale:data.value.tenant.locale});billingCycle.value=data.value.tenant.current_subscription?.billing_cycle||'monthly';billingCurrency.value=data.value.tenant.current_subscription?.currency||(data.value.tenant.locale==='ru'?'RUB':data.value.tenant.locale==='uk'?'UAH':'EUR');}if(route.query.checkout==='success')notice.value=tr('paymentProcessing');if(route.query.checkout==='cancelled'||route.query.payment==='required')error.value=tr('paymentRequiredText');}catch(e:any){if(String(e.message).includes('Unauthenticated'))router.push('/login');else error.value=e.message}}
onMounted(load);
async function saveProfile(){busy.value=true;error.value='';try{await api(`/tenant/${tenantId.value}/profile`,{method:'PUT',body:JSON.stringify(profile)});notice.value=tr('saved');await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function uploadSocialImage(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;busy.value=true;error.value='';try{const body=new FormData();body.append('image',file);await api('/tenant/'+tenantId.value+'/social-image',{method:'POST',body});notice.value=tr('socialImageUploaded');await load()}catch(e:any){error.value=e.message}finally{busy.value=false;input.value=''}}
async function generateSocialImage(){busy.value=true;error.value='';try{await api('/tenant/'+tenantId.value+'/social-image/generate',{method:'POST'});notice.value=tr('socialImageGenerated');await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function addDomain(){busy.value=true;error.value='';try{await api(`/tenant/${tenantId.value}/domains`,{method:'POST',body:JSON.stringify({domain:customDomain.value})});customDomain.value='';notice.value=tr('domainAdded');await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function verify(domain:any){busy.value=true;try{await api(`/tenant/${tenantId.value}/domains/${domain.id}/verify`,{method:'POST'});await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function checkout(plan:any=subscription.value?.plan){if(!plan)return;busy.value=true;error.value='';try{const result=await api<any>(`/tenant/${tenantId.value}/checkout`,{method:'POST',body:JSON.stringify({plan_id:plan.id,cycle:billingCycle.value,currency:billingCurrency.value})});if(result.checkout_url)location.href=result.checkout_url;else error.value=tr('checkoutUnavailable')}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function logout(){await api('/logout',{method:'POST'});router.push('/login')}
async function stop(){await api('/impersonation/stop',{method:'POST'});location.href='/control'}
const nav=computed(()=>[['overview','⌂',tr('overview')],['business','◇',tr('business')],['domain','◎',tr('domain')],['billing','€',tr('plan')]]);
</script>
<template><div class="tenant-shell"><aside class="tenant-sidebar"><div class="brand"><span class="tenant-wordmark"><b>LOOK</b><i>DO</i><small>APP</small></span></div><div v-if="data" class="tenant-identity"><div class="tenant-avatar">{{data.tenant.name.slice(0,2).toUpperCase()}}</div><div><b>{{data.tenant.name}}</b><small>{{data.tenant.slug}}.lookdo.app</small></div></div><nav><RouterLink v-for="item in nav" :key="item[0]" :to="`/app/${item[0]}`" :class="{active:section===item[0]}"><span>{{item[1]}}</span>{{item[2]}}</RouterLink></nav><button v-if="me?.impersonating" class="support-exit" @click="stop">← {{tr('returnAdmin')}}</button><button class="sidebar-logout" @click="logout">{{tr('logout')}}</button></aside><main class="tenant-content"><header class="mobile-app-header"><div class="brand"><span class="tenant-wordmark"><b>LOOK</b><i>DO</i><small>APP</small></span></div><div class="tenant-header-actions"><a v-if="data" :href="data.platform_url" target="_blank">↗</a><button @click="logout">⎋</button></div></header><div v-if="!data" class="loading">LOOKDO…</div><template v-else><div class="content-heading"><div><p class="eyebrow">{{data.tenant.name}}</p><h1>{{nav.find(x=>x[0]===section)?.[2]}}</h1></div><RouterLink class="status-pill" :class="{unpaid:paymentRequired}" :to="paymentRequired?'/app/billing':'/app/overview'"><i></i>{{paymentRequired?tr('unpaid'):tr('active')}}</RouterLink></div><div v-if="paymentRequired" class="tenant-payment-alert"><div><b>{{tr('paymentRequired')}}</b><span>{{tr('paymentRequiredText')}}</span></div><button class="button small" :disabled="busy" @click="checkout()">{{tr('payNow')}}</button></div><p v-if="error" class="alert error">{{error}}</p><p v-if="notice" class="alert success">{{notice}}</p>
<section v-if="section==='overview'" class="dashboard-grid">
<article class="welcome-card"><div><p class="eyebrow">{{tr('yourApp')}}</p><h2>{{paymentRequired?tr('paymentRequired'):tr('workspaceReady')}}</h2><p>{{tr('permanentAddress')}}</p><a class="tenant-open-app" :href="data.platform_url" target="_blank">{{tr('openApp')}} ↗</a></div><div class="progress-compact"><strong>{{setupPercent}}%</strong><span>{{tr('setup')}}</span></div></article>
<article class="tenant-next-steps"><p class="eyebrow">{{tr('setupNext')}}</p><div><RouterLink class="tenant-step done" to="/app/business"><span>✓</span><b>{{tr('profileStep')}}</b><small>{{tr('done')}}</small></RouterLink><RouterLink class="tenant-step" :class="{done:socialImageReady}" to="/app/business"><span>{{socialImageReady?'✓':'2'}}</span><b>{{tr('socialImageStep')}}</b><small>{{socialImageReady?tr('done'):'→'}}</small></RouterLink><RouterLink class="tenant-step done" to="/app/domain"><span>✓</span><b>{{tr('domainStep')}}</b><small>{{tr('done')}}</small></RouterLink><RouterLink class="tenant-step" :class="{done:!paymentRequired}" to="/app/billing"><span>{{paymentRequired?'4':'✓'}}</span><b>{{tr('paymentStep')}}</b><small>{{paymentRequired?'→':tr('done')}}</small></RouterLink></div></article>
<article class="dashboard-card"><span class="card-icon">◎</span><h3>{{tr('businessTemplate')}}</h3><b>{{data.tenant.business_profile?.variation?.name?.[data.tenant.locale]||data.tenant.business_profile?.variation?.code}}</b><RouterLink to="/app/business">{{tr('viewDetails')}} →</RouterLink></article>
<article class="dashboard-card" :class="{'card-unpaid':paymentRequired}"><span class="card-icon">€</span><h3>{{tr('subscription')}}</h3><b>{{planName(subscription?.plan)||tr('notActive')}}</b><span>{{paymentRequired?tr('unpaid'):(subscription?.status||tr('notActive'))}}</span><RouterLink to="/app/billing">{{paymentRequired?tr('payNow'):tr('manage')}} →</RouterLink></article>
<article class="dashboard-card"><span class="card-icon">↗</span><h3>{{tr('appAddress')}}</h3><b>{{data.tenant.slug}}.lookdo.app</b><a :href="data.platform_url" target="_blank">{{tr('openApp')}} →</a></article>
<article class="coming-card"><p class="eyebrow">{{tr('nextStage')}}</p><h3>{{tr('nextFeatures')}}</h3><p>{{tr('nextFeaturesText')}}</p></article></section>
<section v-if="section==='business'" class="settings-card"><div class="settings-title"><h2>{{tr('businessProfile')}}</h2><p>{{tr('businessProfileText')}}</p></div><form class="form-grid" @submit.prevent="saveProfile"><label class="wide">{{tr('businessName')}}<input v-model="profile.name" required></label><label>{{tr('language')}}<select v-model="profile.locale"><option value="ru">Русский</option><option value="de">Deutsch</option><option value="en">English</option><option value="uk">Українська</option></select></label><label>{{tr('contactPerson')}}<input v-model="profile.contact_name"></label><label>{{tr('email')}}<input v-model="profile.email" type="email"></label><label>{{tr('phone')}}<input v-model="profile.phone"></label><label>{{tr('city')}}<input v-model="profile.city"></label><label>{{tr('street')}}<input v-model="profile.street"></label><label>{{tr('postalCode')}}<input v-model="profile.postal_code"></label><label>{{tr('primaryColour')}}<input v-model="profile.primary_color" type="color"></label><label>{{tr('secondaryColour')}}<input v-model="profile.secondary_color" type="color"></label><button class="button" :disabled="busy">{{tr('saveProfile')}}</button></form><section class="social-image-settings" :class="{missing:!socialImageReady}"><div><p class="eyebrow">{{tr('socialImageEyebrow')}}</p><h3>{{tr('socialImageTitle')}}</h3><p>{{tr('socialImageText')}}</p><small>{{tr('socialImageFormat')}}</small></div><img v-if="data.tenant.profile?.social_image_url" :src="data.tenant.profile.social_image_url" :alt="tr('socialImageTitle')"><div v-else class="social-image-placeholder">LOOKDO<br><span>{{tr('socialImageMissing')}}</span></div><div class="social-image-actions"><label class="button ghost small"><input type="file" accept="image/jpeg,image/png,image/webp" :disabled="busy" @change="uploadSocialImage">{{tr('uploadImage')}}</label><button type="button" class="button small" :disabled="busy" @click="generateSocialImage">{{busy?tr('pleaseWait'):tr('generateImage')}}</button></div></section><div class="template-summary"><p class="eyebrow">{{tr('activeTemplate')}}</p><h3>{{data.tenant.business_profile?.variation?.name?.[data.tenant.locale]}}</h3><code>{{data.tenant.business_profile?.template?.code}}</code><p>{{data.tenant.business_description}}</p></div></section>
<section v-if="section==='domain'" class="settings-card"><div class="settings-title"><h2>{{tr('domains')}}</h2><p>{{tr('domainText')}}</p></div><div class="domain-list"><article v-for="domain in data.tenant.domains" :key="domain.id"><div><b>{{domain.domain}}</b><span>{{domain.type}} · {{domain.status}}<template v-if="domain.ssl_status"> · SSL {{domain.ssl_status}}</template></span></div><button v-if="domain.type==='custom'&&domain.status!=='active'" class="button ghost small" :disabled="busy" @click="verify(domain)">{{tr('checkDns')}}</button><span v-if="domain.is_primary" class="badge">{{tr('primary')}}</span></article></div><form class="inline-form" @submit.prevent="addDomain"><label>{{tr('connectDomain')}}<input v-model="customDomain" placeholder="example.de" required></label><button class="button" :disabled="busy">{{tr('addDomain')}}</button></form><div class="dns-help"><b>{{tr('dnsInstruction')}}</b><p>{{tr('dnsText')}}</p></div></section>
<section v-if="section==='billing'" class="settings-card billing-card"><div class="settings-title"><h2>{{tr('planSubscription')}}</h2><p>{{tr('planBackend')}}</p></div>
<div v-if="subscription" class="current-plan" :class="{unpaid:paymentRequired}"><div><span>{{tr('currentPlan')}}</span><h3>{{planName(subscription.plan)}}</h3><p>{{paymentRequired?tr('unpaid'):(subscription.complimentary?tr('complimentaryStatus'):subscription.status)}}</p></div><strong>{{money(subscription.unit_amount,subscription.currency)}}<small>{{subscription.billing_cycle==='yearly'?tr('perYear'):tr('month')}}</small></strong><button v-if="paymentRequired" class="button" :disabled="busy" @click="checkout()">{{tr('payNow')}}</button></div>
<div class="billing-controls tenant-billing-controls"><label>{{tr('currency')}}<select v-model="billingCurrency"><option value="EUR">EUR — €</option><option value="RUB">RUB — ₽</option><option value="UAH">UAH — ₴</option></select></label><div class="cycle"><button type="button" :class="{active:billingCycle==='monthly'}" @click="billingCycle='monthly'">{{tr('monthly')}}</button><button type="button" :class="{active:billingCycle==='yearly'}" @click="billingCycle='yearly'">{{tr('yearly')}}</button></div></div>
<div class="mini-plans"><article v-for="plan in plans" :key="plan.id"><div><h3>{{planName(plan)}}</h3><p>{{planDescription(plan)}}</p></div><strong>{{money(planPrice(plan))}}<small>{{billingCycle==='yearly'?tr('perYear'):tr('month')}}</small></strong><button class="button small" :disabled="busy||planPrice(plan)===null" @click="checkout(plan)">{{paymentRequired&&plan.id===subscription?.plan_id?tr('payNow'):tr('choose')}}</button></article></div>
<div v-if="subscription?.payments?.length" class="admin-table-wrap"><table><thead><tr><th>{{tr('date')}}</th><th>{{tr('amount')}}</th><th>{{tr('status')}}</th><th>{{tr('payment')}}</th></tr></thead><tbody><tr v-for="payment in subscription.payments" :key="payment.id"><td>{{payment.paid_at||payment.created_at}}</td><td>{{payment.amount}} {{payment.currency}}</td><td>{{payment.status}}</td><td>{{payment.provider_payment_id}}</td></tr></tbody></table></div></section>
</template></main><nav class="tenant-mobile-nav"><RouterLink v-for="item in nav" :key="item[0]" :to="`/app/${item[0]}`" :class="{active:section===item[0]}"><span>{{item[1]}}</span><small>{{item[2]}}</small></RouterLink></nav></div></template>
