<?php

return [
    'presets' => [
        'leonid-steering' => [
            'template' => 'automotive.steering-wheel-upholstery',
            'tenant' => [
                'name' => 'Перетяжка рулей',
                'locale' => 'ru',
                'business_description' => 'Профессиональная перетяжка автомобильных рулей. Мастер может принять руль в мастерской или приехать к клиенту, аккуратно демонтировать его, забрать в работу, затем привезти и установить.',
            ],
            'profile' => [
                'primary_color' => '#d9a84e',
                'secondary_color' => '#07090a',
                'logo_path' => '/brand/tenants/leonid-steering/avtorul-app-icon.png',
                'enabled_locales' => ['ru', 'de', 'en', 'uk'],
                'branding' => [
                    'horizontal_logo_path' => '/brand/tenants/leonid-steering/avtorul-wide-logo.png',
                    'hero_image_path' => '/brand/tenants/leonid-steering/hero-v2.png',
                    'confirmed_at' => 'preset',
                    'services' => 'Перетяжка автомобильных рулей, восстановление поверхности и швов. Возможны приём в мастерской, самостоятельная доставка или выезд мастера для демонтажа, доставки и последующей установки руля.',
                    'customers' => 'Автовладельцы, которым нужна аккуратная перетяжка руля с понятным согласованием работы по фотографиям.',
                    'style' => 'Тёмный премиальный интерфейс с золотыми акцентами и реальными фотографиями работ.',
                    'avoid' => 'Чужие работы, придуманные марки автомобилей, неподтверждённые цены, сроки и гарантии.',
                    'service_modes' => ['workshop', 'on_site'],
                    'description_translations' => [
                        'ru' => 'Профессиональная перетяжка автомобильных рулей. Привезите руль сами или закажите выезд мастера: он аккуратно демонтирует руль, заберёт в мастерскую, а после работы привезёт и установит обратно.',
                        'de' => 'Professionelle Lenkradaufbereitung. Bringen Sie das Lenkrad selbst vorbei oder buchen Sie den mobilen Service: Der Fachmann baut es sorgfältig aus, nimmt es mit in die Werkstatt und montiert es nach der Arbeit wieder.',
                        'en' => 'Professional steering-wheel upholstery. Bring the wheel to the workshop or book the mobile service: the specialist removes it carefully, takes it to the workshop, then returns and reinstalls it.',
                        'uk' => 'Професійна перетяжка автомобільного керма. Привезіть кермо самостійно або замовте виїзд майстра: він акуратно демонтує кермо, забере до майстерні, а після роботи привезе й встановить назад.',
                    ],
                    'tagline_translations' => [
                        'ru' => 'Ручная работа · Премиальные материалы · Аккуратный результат',
                        'de' => 'Handarbeit · Hochwertige Materialien · Sauberes Ergebnis',
                        'en' => 'Handcrafted · Premium materials · Refined finish',
                        'uk' => 'Ручна робота · Преміальні матеріали · Акуратний результат',
                    ],
                ],
            ],
            'configuration' => [
                'locales' => ['ru', 'de', 'en', 'uk'],
                'navigation' => ['home', 'works', 'action', 'activity', 'reviews'],
                'theme' => ['primary' => '#d9a84e', 'secondary' => '#07090a', 'surface' => '#111315', 'text' => '#f7f4ed'],
                'hero' => [
                    'image' => '/brand/tenants/leonid-steering/hero-v2.png',
                    'eyebrow' => ['ru' => 'ПЕРЕТЯЖКА АВТОМОБИЛЬНЫХ РУЛЕЙ', 'de' => 'PROFESSIONELLER LENKRADBEZUG', 'en' => 'PROFESSIONAL STEERING WHEEL UPHOLSTERY', 'uk' => 'ПЕРЕТЯЖКА АВТОМОБІЛЬНИХ КЕРМ'],
                    'title' => ['ru' => 'Ручная работа · Премиальные материалы · Аккуратный результат', 'de' => 'Handarbeit · Hochwertige Materialien · Sauberes Ergebnis', 'en' => 'Handcrafted · Premium materials · Refined finish', 'uk' => 'Ручна робота · Преміальні матеріали · Акуратний результат'],
                    'text' => ['ru' => 'Пришлите фотографии для оценки. Руль можно привезти самостоятельно или заказать выезд мастера с демонтажом и установкой.', 'de' => 'Senden Sie Fotos zur Einschätzung. Sie können das Lenkrad selbst bringen oder den mobilen Aus- und Einbauservice buchen.', 'en' => 'Send photos for an assessment. Bring the wheel yourself or book mobile removal and reinstallation.', 'uk' => 'Надішліть фотографії для оцінки. Кермо можна привезти самостійно або замовити виїзд майстра з демонтажем і встановленням.'],
                    'action' => ['ru' => 'Оценить мой руль', 'de' => 'Lenkrad bewerten', 'en' => 'Assess my steering wheel', 'uk' => 'Оцінити моє кермо'],
                ],
                'trust' => [
                    ['icon' => 'shield', 'label' => ['ru' => 'Реальные работы', 'de' => 'Echte Arbeiten', 'en' => 'Real work', 'uk' => 'Реальні роботи']],
                    ['icon' => 'tool', 'label' => ['ru' => 'Аккуратный демонтаж', 'de' => 'Sorgfältiger Ausbau', 'en' => 'Careful removal', 'uk' => 'Акуратний демонтаж']],
                    ['icon' => 'location', 'label' => ['ru' => 'Мастерская или выезд', 'de' => 'Werkstatt oder mobil', 'en' => 'Workshop or mobile', 'uk' => 'Майстерня або виїзд']],
                    ['icon' => 'clock', 'label' => ['ru' => 'Ответ после оценки', 'de' => 'Antwort nach Prüfung', 'en' => 'Reply after assessment', 'uk' => 'Відповідь після оцінки']],
                ],
                'starter_services' => [
                    ['duration' => 60, 'image' => '/brand/tenants/leonid-steering/kia-finished.webp', 'name' => ['ru' => 'Перетяжка руля', 'de' => 'Lenkrad neu beziehen', 'en' => 'Steering-wheel upholstery', 'uk' => 'Перетяжка керма'], 'description' => ['ru' => 'Оценка состояния и согласование материала по фотографиям', 'de' => 'Zustand prüfen und Material anhand von Fotos abstimmen', 'en' => 'Condition assessment and material selection from photos', 'uk' => 'Оцінка стану та узгодження матеріалу за фотографіями']],
                    ['duration' => 60, 'image' => '/brand/tenants/leonid-steering/ford-finished.webp', 'name' => ['ru' => 'Выезд, демонтаж и установка', 'de' => 'Mobiler Aus- und Einbau', 'en' => 'Mobile removal and installation', 'uk' => 'Виїзд, демонтаж і встановлення'], 'description' => ['ru' => 'Мастер снимает руль, забирает в мастерскую и устанавливает после готовности', 'de' => 'Der Fachmann baut das Lenkrad aus, nimmt es mit und montiert es nach Fertigstellung wieder', 'en' => 'The specialist removes the wheel, takes it to the workshop and reinstalls it when ready', 'uk' => 'Майстер знімає кермо, забирає до майстерні та встановлює після готовності']],
                ],
                'obsolete_portfolio_images' => ['/brand/leonid-demo.webp'],
                'starter_portfolio' => [
                    ['title' => ['ru' => 'Chevrolet — восстановление обода', 'de' => 'Chevrolet – Lenkradkranz erneuert', 'en' => 'Chevrolet — rim restoration', 'uk' => 'Chevrolet — відновлення обода'], 'description' => ['ru' => 'Повреждённая поверхность до работы и аккуратный результат после перетяжки.', 'de' => 'Beschädigte Oberfläche vor der Arbeit und das saubere Ergebnis danach.', 'en' => 'The damaged surface before the work and the clean upholstered result.', 'uk' => 'Пошкоджена поверхня до роботи та акуратний результат після перетяжки.'], 'image' => '/brand/tenants/leonid-steering/chevrolet-after.webp', 'before_image' => '/brand/tenants/leonid-steering/chevrolet-before.webp', 'after_image' => '/brand/tenants/leonid-steering/chevrolet-after.webp', 'featured' => true],
                    ['title' => ['ru' => 'Hyundai — перетяжка руля', 'de' => 'Hyundai – Lenkrad neu bezogen', 'en' => 'Hyundai — steering-wheel upholstery', 'uk' => 'Hyundai — перетяжка керма'], 'description' => ['ru' => 'Состояние руля до работы и новая отделка после.', 'de' => 'Der Zustand vorher und die neue Oberfläche danach.', 'en' => 'The wheel before the work and its new finish afterwards.', 'uk' => 'Стан керма до роботи та нове оздоблення після.'], 'image' => '/brand/tenants/leonid-steering/hyundai-after.webp', 'before_image' => '/brand/tenants/leonid-steering/hyundai-before.webp', 'after_image' => '/brand/tenants/leonid-steering/hyundai-after.webp', 'featured' => true],
                    ['title' => ['ru' => 'Toyota — обновление покрытия', 'de' => 'Toyota – Oberfläche erneuert', 'en' => 'Toyota — surface renewal', 'uk' => 'Toyota — оновлення покриття'], 'description' => ['ru' => 'Изношенная зона до ремонта и ровная новая отделка после.', 'de' => 'Die abgenutzte Stelle vorher und die gleichmäßige neue Oberfläche danach.', 'en' => 'The worn area before repair and the even new finish afterwards.', 'uk' => 'Зношена ділянка до ремонту та рівне нове оздоблення після.'], 'image' => '/brand/tenants/leonid-steering/toyota-after.webp', 'before_image' => '/brand/tenants/leonid-steering/toyota-before.webp', 'after_image' => '/brand/tenants/leonid-steering/toyota-after.webp'],
                    ['title' => ['ru' => 'Kia — восстановление повреждённой кожи', 'de' => 'Kia – beschädigtes Leder erneuert', 'en' => 'Kia — damaged leather restored', 'uk' => 'Kia — відновлення пошкодженої шкіри'], 'description' => ['ru' => 'Сильный износ до работы и новая перетяжка после.', 'de' => 'Starker Verschleiß vorher und der neue Bezug danach.', 'en' => 'Heavy wear before the work and the new upholstery afterwards.', 'uk' => 'Сильний знос до роботи та нова перетяжка після.'], 'image' => '/brand/tenants/leonid-steering/kia-after.webp', 'before_image' => '/brand/tenants/leonid-steering/kia-before.webp', 'after_image' => '/brand/tenants/leonid-steering/kia-after.webp'],
                    ['title' => ['ru' => 'Ford — полное обновление руля', 'de' => 'Ford – Lenkrad vollständig erneuert', 'en' => 'Ford — complete steering-wheel renewal', 'uk' => 'Ford — повне оновлення керма'], 'description' => ['ru' => 'Изношенный руль до работы и готовый результат после перетяжки.', 'de' => 'Das abgenutzte Lenkrad vorher und das fertige Ergebnis danach.', 'en' => 'The worn wheel before the work and the finished upholstered result.', 'uk' => 'Зношене кермо до роботи та готовий результат після перетяжки.'], 'image' => '/brand/tenants/leonid-steering/ford-after.webp', 'before_image' => '/brand/tenants/leonid-steering/ford-before.webp', 'after_image' => '/brand/tenants/leonid-steering/ford-after.webp'],
                    ['title' => ['ru' => 'MAN — руль грузового автомобиля', 'de' => 'MAN – Lkw-Lenkrad erneuert', 'en' => 'MAN — truck steering wheel', 'uk' => 'MAN — кермо вантажного автомобіля'], 'description' => ['ru' => 'Руль в автомобиле до работы и результат после восстановления.', 'de' => 'Das Lenkrad im Fahrzeug vorher und das Ergebnis nach der Aufbereitung.', 'en' => 'The wheel in the vehicle before the work and the restored result.', 'uk' => 'Кермо в автомобілі до роботи та результат після відновлення.'], 'image' => '/brand/tenants/leonid-steering/man-after.webp', 'before_image' => '/brand/tenants/leonid-steering/man-before.webp', 'after_image' => '/brand/tenants/leonid-steering/man-after.webp'],
                    ['title' => ['ru' => 'Renault — готовая работа', 'de' => 'Renault – fertige Arbeit', 'en' => 'Renault — completed work', 'uk' => 'Renault — готова робота'], 'image' => '/brand/tenants/leonid-steering/renault-finished.webp'],
                    ['title' => ['ru' => 'Peugeot — готовая работа', 'de' => 'Peugeot – fertige Arbeit', 'en' => 'Peugeot — completed work', 'uk' => 'Peugeot — готова робота'], 'image' => '/brand/tenants/leonid-steering/peugeot-finished.webp'],
                    ['title' => ['ru' => 'Kia — перфорация и ровный шов', 'de' => 'Kia – Perforation und saubere Naht', 'en' => 'Kia — perforation and clean stitching', 'uk' => 'Kia — перфорація та рівний шов'], 'image' => '/brand/tenants/leonid-steering/kia-finished.webp'],
                    ['title' => ['ru' => 'Ford — готовая перетяжка', 'de' => 'Ford – neuer Lenkradbezug', 'en' => 'Ford — finished upholstery', 'uk' => 'Ford — готова перетяжка'], 'image' => '/brand/tenants/leonid-steering/ford-finished.webp'],
                ],
                'starter_reviews' => [
                    ['author_name' => 'Александр', 'received_at' => '2026-07-07 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Хороший мастер сделал все хорошо', 'master_reply' => 'Спасибо за заказ и высокую оценку'],
                    ['author_name' => 'Сергей', 'received_at' => '2026-07-04 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Оперативно и качественно. Советую.', 'master_reply' => 'Спасибо за высокую оценку'],
                    ['author_name' => 'частник', 'received_at' => '2026-03-16 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Сделал быстро и качественно. Все аккуратно. На ощупь очень приятный и цвет кожи красивый. Поеду ставить. Рекомендую продовца 🤝', 'master_reply' => 'Спасибо за высокую оценку'],
                    ['author_name' => 'Карина', 'received_at' => '2026-01-06 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Нужна была перетяжка руля (подарок сыну). Т.к. еще праздники, Леонид вошел в положение и перетянул его. Малой рад). Материал плотный, качественный, швы ровные, красные под цвет машины. Все четко! Цену не завысил. Рекомендую!', 'master_reply' => 'Спасибо за высокую оценку напоминаю что у вас есть гарантия на работу'],
                    ['author_name' => 'Кирилл', 'received_at' => '2026-01-03 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Все отлично спасибо', 'master_reply' => 'Спасибо за заказ'],
                    ['author_name' => 'Zz', 'received_at' => '2025-12-18 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Быстро и качественно! Мне понравилось!'],
                    ['author_name' => 'Оксана К', 'received_at' => '2025-11-21 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Работой довольна)', 'master_reply' => 'Спасибо'],
                    ['author_name' => 'Алексей', 'received_at' => '2025-10-22 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Работа выполнена качественно и в кратчайшие сроки. Рекомендую.', 'master_reply' => 'Спасибо'],
                    ['author_name' => 'Артур', 'received_at' => '2025-09-05 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Быстро и качественно. Рекомендую 👍', 'master_reply' => 'Спасибо'],
                    ['author_name' => 'Дмитрий', 'received_at' => '2025-08-13 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Все сделали быстро красиво аккуратно сам приехал снял забрал приехал поставил всем рекомендую по ценнику тоже всё отлично', 'master_reply' => 'Спасибо за высокую оценку'],
                    ['author_name' => 'Александр', 'received_at' => '2025-07-23 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Перетянули руль, работа делана хорошо!'],
                    ['author_name' => 'Хусейн А', 'received_at' => '2025-07-21 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Все быстро качественно в срок рекомендую'],
                    ['author_name' => 'Александр', 'received_at' => '2025-05-18 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Всем кто задался таким вопросом рекомендую ! Работа выполнена качественно даже раньше обговоренного срока 👍🏻причём цена осталась неизменной договорённости ! Приехали показали материал ,образец как на руле будет демонтировали перешили установили обратно !!!'],
                    ['author_name' => 'Иван Иванов', 'received_at' => '2025-05-15 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'По срокам работы обговоренных 2 дня уложился за сутки, цена одыкватная, и подход индивидуальный, приятно иметь дело с сознательными людьми.', 'master_reply' => 'Спасибо за высокую оценку !!!'],
                    ['author_name' => 'Сергей', 'received_at' => '2025-05-14 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Очень рекомендую! Приемлемая цена и отличное качество! Для перетяжки руля использовался качественный материал, швы ровные, не расползаются!', 'master_reply' => 'Спасибо за отзыв'],
                    ['author_name' => 'ПА', 'received_at' => '2025-05-13 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Рекомендую. Адекватная цена, скорость выполнения, качественные материалы. Видно, что опытный спец: и понял пожелания, и дал реальные советы и рекомендации. Спасибо огромное', 'master_reply' => 'Спасибо за высокую оценку'],
                    ['author_name' => 'Пользователь', 'received_at' => '2025-05-11 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Работа была сделана качественно,быстрее оговоренного срока,все аккуратно,до мелочей,все пожелания были тщательно выполненны,порадовало,что сами сняли и установили руль на место..спасибо,за оказанную услугу,очень вежливому персоналу!!!', 'master_reply' => 'Спасибо огромное'],
                    ['author_name' => 'Андрей', 'received_at' => '2025-05-10 12:00:00 Europe/Moscow', 'rating' => 5, 'body' => 'Все супер! 👍 Швы ровные, отличный материал, приятно держать в руках. После того как показали что данная кожа не прожигается сигаретой и не рвется, есть уверенность что руль проживет долго. Работа выполнена быстро и по приятной цене. Однозначно рекомендую!'],
                ],
            ],
        ],
        'ivanna-brows' => [
            'template' => 'beauty.brows',
            'tenant' => [
                'name' => 'Ivanna Brows',
                'locale' => 'uk',
                'business_description' => 'Догляд, оформлення, корекція, фарбування та ламінування брів і вій у Темпліні — у студії або з виїздом до клієнта.',
            ],
            'profile' => [
                'contact_name' => 'Ivanna Pasteliak',
                'phone' => '+49 174 4812109',
                'street' => 'Ringstr. 12',
                'postal_code' => '17268',
                'city' => 'Templin',
                'primary_color' => '#f47a28',
                'secondary_color' => '#fff3e8',
                'logo_path' => '/brand/tenants/ivanna-brows/logo.webp',
                'enabled_locales' => ['uk', 'ru', 'de'],
                'branding' => [
                    'horizontal_logo_path' => '/brand/tenants/ivanna-brows/logo-horizontal.webp',
                    'hero_image_path' => '/brand/service-brows.webp',
                    'confirmed_at' => 'preset',
                    'services' => 'Корекція, оформлення, фарбування та ламінування брів і вій. Робота у студії та з виїздом до клієнта.',
                    'customers' => 'Клієнти у Темпліні та околицях, яким потрібен професійний догляд за бровами та віями.',
                    'style' => 'Світлий, теплий, кремово-помаранчевий, жіночний та професійний.',
                    'avoid' => 'Чужі логотипи, неприродна ретуш, медичні обіцянки та результати, яких немає у портфоліо.',
                    'service_modes' => ['workshop', 'on_site'],
                    'description_translations' => [
                        'uk' => 'Догляд, оформлення, корекція, фарбування та ламінування брів і вій у Темпліні — у студії або з виїздом до клієнта.',
                        'ru' => 'Уход, оформление, коррекция, окрашивание и ламинирование бровей и ресниц в Темплине — в студии или с выездом к клиенту.',
                        'de' => 'Kosmetische Behandlungen, Gestaltung und Pflege von Augenbrauen und Wimpern in Templin – im Studio oder mobil bei Kundinnen und Kunden.',
                    ],
                    'tagline_translations' => [
                        'uk' => 'Брови, які підкреслюють вашу красу',
                        'ru' => 'Брови, которые подчёркивают вашу красоту',
                        'de' => 'Augenbrauen, die Ihre natürliche Schönheit betonen',
                    ],
                ],
            ],
            'configuration' => [
                'replace_services' => true,
                'replace_portfolio' => true,
                'locales' => ['uk', 'ru', 'de'],
                'theme' => ['primary' => '#f47a28', 'secondary' => '#fff3e8', 'surface' => '#fffaf6', 'text' => '#321a12'],
                'hero' => [
                    'eyebrow' => ['uk' => 'IVANNA BROWS', 'ru' => 'IVANNA BROWS', 'de' => 'IVANNA BROWS'],
                    'title' => ['uk' => 'Брови, які підкреслюють вашу красу', 'ru' => 'Брови, которые подчёркивают вашу красоту', 'de' => 'Augenbrauen, die Ihre natürliche Schönheit betonen'],
                    'text' => ['uk' => 'Оберіть послугу та зручний час. Прийом у студії або з виїздом до вас.', 'ru' => 'Выберите услугу и удобное время. Приём в студии или с выездом к вам.', 'de' => 'Wählen Sie eine Leistung und einen passenden Termin – im Studio oder mobil bei Ihnen.'],
                    'action' => ['uk' => 'Записатися', 'ru' => 'Записаться', 'de' => 'Termin buchen'],
                ],
                'trust' => [
                    ['icon' => 'star', 'label' => ['uk' => 'Індивідуальна форма', 'ru' => 'Индивидуальная форма', 'de' => 'Individuelle Form']],
                    ['icon' => 'shield', 'label' => ['uk' => 'Дбайлива робота', 'ru' => 'Бережная работа', 'de' => 'Sorgfältige Arbeit']],
                    ['icon' => 'location', 'label' => ['uk' => 'Студія або виїзд', 'ru' => 'Студия или выезд', 'de' => 'Studio oder mobil']],
                    ['icon' => 'clock', 'label' => ['uk' => 'Онлайн-запис', 'ru' => 'Онлайн-запись', 'de' => 'Online-Termin']],
                ],
                'starter_services' => [
                    [
                        'duration' => 50, 'price' => 20, 'currency' => 'EUR', 'repeat_interval_days' => 28, 'image' => '/brand/service-brows.webp',
                        'name' => ['uk' => 'Корекція та фарбування брів', 'ru' => 'Коррекция и окрашивание бровей', 'de' => 'Augenbrauenkorrektur und Färben'],
                        'description' => ['uk' => "Що входить: Створення ідеальної архітектури та форми брів за допомогою воску/пінцета, підбір індивідуального відтінку та фарбування професійною фарбою Zola.\n\nРезультат: Чітка форма, виразний та природний колір, який тримається на шкірі до 7–10 днів, а на волосках — до 4 тижнів. Фарба Zola не лише надає багатий колір, але й доглядає за волосками завдяки доглядовим компонентам.\n\nТривалість: 40–50 хв.\n\nРекомендуємо повторювати процедуру кожні 3–4 тижні для підтримання чіткої форми та насиченого кольору брів."],
                    ],
                    [
                        'duration' => 40, 'price' => 15, 'currency' => 'EUR', 'repeat_interval_days' => 56, 'image' => '/brand/service-brows.webp',
                        'name' => ['uk' => 'Ламінування (довготривала укладка) брів', 'ru' => 'Ламинирование (долговременная укладка) бровей', 'de' => 'Brow-Laminierung (langanhaltendes Styling)'],
                        'description' => ['uk' => "Що входить: Моделювання та надання потрібного напрямку волоскам за допомогою складів Zola Lash & Brow Lamination. Ідеально для жорстких, неслухняних або кучерявих брів.\n\nРезультат: Слухняні, м’які та візуально густіші брови, які легко укладаються щіточкою за 5 секунд щоранку. Ефект тримається 1,5–2 місяці. Процедура без фарбування.\n\nТривалість: 30–40 хв.\n\nПовторне ламінування проводиться через 1,5–2 місяці, коли волоски повністю оновляться. Для підтримання кольору між ламінуваннями можна прийти на легке фарбування через 3–4 тижні."],
                    ],
                    [
                        'duration' => 70, 'price' => 35, 'currency' => 'EUR', 'repeat_interval_days' => 56, 'image' => '/brand/service-brows.webp',
                        'name' => ['uk' => 'Комплекс «Ламінування + фарбування брів»', 'ru' => 'Комплекс «Ламинирование + окрашивание бровей»', 'de' => 'Komplettbehandlung „Laminierung + Färben“'],
                        'description' => ['uk' => "Хіт продажів. Ботокс у подарунок 🎁\n\nЩо входить: Повний цикл догляду — надання форми (корекція воском/пінцетом), довготривала укладка складами Zola, фарбування фарбою Zola та відновлювальна процедура Zola Botx у подарунок.\n\nРезультат: Максимально доглянутий, соковитий та водночас природний вигляд. Ботокс насичує волоски кератином, амінокислотами та оліями, закриває лусочки після хімічного впливу, роблячи брови шовковистими, блискучими та міцними.\n\nТривалість: 60–70 хв.\n\nПовторне ламінування рекомендується через 1,5–2 місяці."],
                    ],
                    [
                        'duration' => 15, 'price' => 5, 'currency' => 'EUR', 'repeat_interval_days' => 21, 'image' => '/brand/service-brows.webp',
                        'name' => ['uk' => 'Ботокс для брів (Zola Botx)', 'ru' => 'Ботокс для бровей (Zola Botx)', 'de' => 'Augenbrauen-Botox (Zola Botx)'],
                        'description' => ['uk' => "Що входить: Глибока доглядова та відновлювальна маска для волосків. Може додаватися до будь-якої процедури.\n\nРезультат: Інтенсивне зволоження, стимуляція росту нових волосків та відновлення структури після фарбування чи ламінування.\n\nТривалість: 10–15 хв.\n\nМає накопичувальний відновлювальний ефект. Можна робити кожні 2–3 тижні для глибокого живлення та активного росту брів."],
                    ],
                    [
                        'duration' => 30, 'price' => 10, 'currency' => 'EUR', 'repeat_interval_days' => 21, 'image' => '/brand/service-brows.webp',
                        'name' => ['uk' => 'Корекція брів (без фарбування)', 'ru' => 'Коррекция бровей (без окрашивания)', 'de' => 'Augenbrauenkorrektur (ohne Färben)'],
                        'description' => ['uk' => "Що входить: Побудова анатомічної форми брів та видалення зайвих волосків воском чи пінцетом, нанесення заспокійливого лосьйону Zola.\n\nРезультат: Чиста, охайна та симетрична форма брів.\n\nТривалість: 20–30 хв.\n\nОновлювати форму рекомендується кожні 2–3 тижні в міру відростання волосків."],
                    ],
                    [
                        'duration' => 10, 'price' => 5, 'currency' => 'EUR', 'repeat_interval_days' => 21, 'image' => '/brand/service-brows.webp',
                        'name' => ['uk' => 'Видалення волосків з додаткової зони воском', 'ru' => 'Удаление волосков с дополнительной зоны воском', 'de' => 'Waxing einer zusätzlichen Gesichtspartie'],
                        'description' => ['uk' => "Що входить: Делікатне видалення небажаного пушкового волосся воском Zola. Зони: над верхньою губою, підборіддя або скроні.\n\nРезультат: Ідеально гладенька шкіра без подразнень завдяки гіпоалергенному воску.\n\nТривалість: близько 10 хв.\n\nПовторювати рекомендується кожні 2–3 тижні в міру відростання волосків."],
                    ],
                ],
                'starter_portfolio' => [
                    ['image' => '/brand/tenants/ivanna-brows/portfolio/ivanna-work-photo-01.png', 'featured' => true, 'title' => ['uk' => 'Робота Ivanna Brows — брови 1', 'ru' => 'Работа Ivanna Brows — брови 1', 'de' => 'Arbeit von Ivanna Brows — Augenbrauen 1']],
                    ['image' => '/brand/tenants/ivanna-brows/portfolio/ivanna-work-photo-02.png', 'featured' => true, 'title' => ['uk' => 'Робота Ivanna Brows — брови 2', 'ru' => 'Работа Ivanna Brows — брови 2', 'de' => 'Arbeit von Ivanna Brows — Augenbrauen 2']],
                    ['image' => '/brand/tenants/ivanna-brows/portfolio/ivanna-work-photo-03.png', 'featured' => true, 'title' => ['uk' => 'Робота Ivanna Brows — брови 3', 'ru' => 'Работа Ivanna Brows — брови 3', 'de' => 'Arbeit von Ivanna Brows — Augenbrauen 3']],
                    ['image' => '/brand/tenants/ivanna-brows/portfolio/ivanna-work-photo-04.png', 'featured' => true, 'title' => ['uk' => 'Робота Ivanna Brows — брови 4', 'ru' => 'Работа Ivanna Brows — брови 4', 'de' => 'Arbeit von Ivanna Brows — Augenbrauen 4']],
                    ['image' => '/brand/tenants/ivanna-brows/portfolio/ivanna-work-photo-05.png', 'featured' => true, 'title' => ['uk' => 'Робота Ivanna Brows — брови 5', 'ru' => 'Работа Ivanna Brows — брови 5', 'de' => 'Arbeit von Ivanna Brows — Augenbrauen 5']],
                    ['image' => '/brand/tenants/ivanna-brows/portfolio/ivanna-work-photo-06.png', 'featured' => true, 'title' => ['uk' => 'Робота Ivanna Brows — брови 6', 'ru' => 'Работа Ivanna Brows — брови 6', 'de' => 'Arbeit von Ivanna Brows — Augenbrauen 6']],
                    ['image' => '/brand/tenants/ivanna-brows/portfolio/ivanna-work-photo-07.png', 'featured' => true, 'title' => ['uk' => 'Робота Ivanna Brows — брови 7', 'ru' => 'Работа Ivanna Brows — брови 7', 'de' => 'Arbeit von Ivanna Brows — Augenbrauen 7']],
                    ['video' => '/brand/tenants/ivanna-brows/portfolio/ivanna-work-video-01.mp4', 'featured' => true, 'title' => ['uk' => 'Робота Ivanna Brows — відео 1', 'ru' => 'Работа Ivanna Brows — видео 1', 'de' => 'Arbeit von Ivanna Brows — Video 1']],
                    ['video' => '/brand/tenants/ivanna-brows/portfolio/ivanna-work-video-02.mp4', 'featured' => true, 'title' => ['uk' => 'Робота Ivanna Brows — відео 2', 'ru' => 'Работа Ivanna Brows — видео 2', 'de' => 'Arbeit von Ivanna Brows — Video 2']],
                    ['video' => '/brand/tenants/ivanna-brows/portfolio/ivanna-work-video-03.mp4', 'featured' => true, 'title' => ['uk' => 'Робота Ivanna Brows — відео 3', 'ru' => 'Работа Ivanna Brows — видео 3', 'de' => 'Arbeit von Ivanna Brows — Video 3']],
                    ['video' => '/brand/tenants/ivanna-brows/portfolio/ivanna-work-video-04.mp4', 'featured' => true, 'title' => ['uk' => 'Робота Ivanna Brows — відео 4', 'ru' => 'Работа Ivanna Brows — видео 4', 'de' => 'Arbeit von Ivanna Brows — Video 4']],
                    ['video' => '/brand/tenants/ivanna-brows/portfolio/ivanna-work-video-05.mp4', 'featured' => true, 'title' => ['uk' => 'Робота Ivanna Brows — відео 5', 'ru' => 'Работа Ivanna Brows — видео 5', 'de' => 'Arbeit von Ivanna Brows — Video 5']],
                    ['video' => '/brand/tenants/ivanna-brows/portfolio/ivanna-work-video-06.mp4', 'featured' => true, 'title' => ['uk' => 'Робота Ivanna Brows — відео 6', 'ru' => 'Работа Ivanna Brows — видео 6', 'de' => 'Arbeit von Ivanna Brows — Video 6']],
                ],
            ],
        ],
    ],
];
