import { brandingServiceText } from "./copy-branding";

export type MasterLocale = "de" | "en" | "ru" | "uk";
const copy: Record<MasterLocale, Record<string, string>> = {
    de: {
        socialAccounts: "Verbundene Konten",
        socialConnected: "Verbunden",
        socialNotConnected: "Noch nicht verbunden",
        socialProviderUnavailable:
            "Der Kanal ist in LOOKDO noch nicht konfiguriert.",
        socialConnectRequired: "Verbinden Sie zuerst das Konto dieses Kanals.",
        socialPublished: "Die Veröffentlichung wurde über die API gesendet.",
        socialDisconnectConfirm: "Dieses Social-Media-Konto trennen?",
        connect: "Verbinden",
        disconnect: "Trennen",
        publishDirect: "Jetzt direkt veröffentlichen",
        telegramTarget: "Telegram-Kanal",
        telegramTargetPlaceholder:
            "@kanal — Bot vorher als Administrator hinzufügen",
        today: "Heute",
        requests: "Anfragen",
        calendar: "Kalender",
        messages: "Nachrichten",
        more: "Mehr",
        customers: "Kunden",
        works: "Arbeiten",
        services: "Leistungen",
        settings: "Einstellungen",
        account: "Konto",
        logout: "Abmelden",
        openApp: "App öffnen",
        todayTitle: "Heute im Betrieb",
        todayText: "Termine, neue Anfragen und freie Zeiten auf einen Blick.",
        appointmentsToday: "Termine heute",
        newRequests: "Neue Anfragen",
        unreadMessages: "Ungelesen",
        freeWindows: "Freie Zeiten",
        nextCustomer: "Nächster Kunde",
        noAppointment: "Heute ist noch kein Termin geplant.",
        repeatCandidates: "Wiederbesuch fällig",
        unpublishedWorks: "Unveröffentlichte Arbeiten",
        viewAll: "Alle anzeigen",
        search: "Suchen…",
        allStatuses: "Alle Status",
        new: "Neu",
        viewed: "Gesehen",
        in_progress: "In Arbeit",
        waiting: "Wartet",
        completed: "Erledigt",
        cancelled: "Storniert",
        no_show: "Nicht erschienen",
        reply: "Antworten",
        send: "Senden",
        internalNote: "Interne Notiz",
        requestDetails: "Anfragedaten",
        showAllDetails: "Alle Daten anzeigen",
        hideDetails: "Weniger anzeigen",
        closePreview: "Vorschau schließen",
        aiConditionAssessment: "KI-Zustandseinschätzung",
        notFilled: "Nicht ausgefüllt",
        save: "Speichern",
        customer: "Kunde",
        possibleDuplicate: "Möglicher Doppelkontakt",
        merge: "Nach Prüfung zusammenführen",
        notes: "Notizen",
        tags: "Segmente / Tags",
        marketingConsent: "Marketing-Einwilligung",
        publicationConsent: "Veröffentlichung erlaubt",
        workingHours: "Arbeitszeiten",
        contacts: "Kontakte im Kunden-App",
        contactsHint:
            "Nur ausgefüllte Kontaktwege werden den Kunden angezeigt.",
        website: "Website",
        blocks: "Blockierungen",
        addBlock: "Zeit blockieren",
        vacation: "Urlaub",
        personal: "Privat",
        blocked: "Blockiert",
        exception: "Ausnahme",
        from: "Von",
        to: "Bis",
        reason: "Grund",
        add: "Hinzufügen",
        service: "Leistung",
        duration: "Dauer (Min.)",
        bufferBefore: "Puffer davor",
        bufferAfter: "Puffer danach",
        repeatDays: "Wiederholung nach Tagen",
        price: "Preis",
        booking: "Online buchbar",
        media: "Foto/Video erlaubt",
        active: "Aktiv",
        addService: "Leistung anlegen",
        appointment: "Termin",
        addAppointment: "Termin anlegen",
        serviceLocation: "Ort der Leistung",
        workshop: "Im Studio / in der Werkstatt",
        on_site: "Beim Kunden vor Ort",
        serviceAddress: "Einsatzadresse",
        serviceAddressHint: "Adresse für den Vor-Ort-Termin",
        reminder: "Erinnerung",
        addReminder: "Erinnerung planen",
        portfolio: "Portfolio / Vorher-Nachher",
        reviews: "Bewertungen",
        social: "Social Content",
        addWork: "Arbeit hinzufügen",
        title: "Titel",
        description: "Beschreibung",
        whatIncluded: "Was ist enthalten?",
        serviceResult: "Ergebnis",
        published: "Veröffentlicht",
        featured: "Hervorgehoben",
        before: "Vorher",
        after: "Nachher",
        image: "Bild",
        video: "Video",
        portfolioVideoHint:
            "MP4, WebM oder MOV. Die maximale Größe richtet sich nach Ihrem Tarif.",
        removeVideo: "Vorhandenes Video entfernen",
        rating: "Bewertung",
        masterReply: "Antwort des Betriebs",
        caption: "Text",
        channel: "Kanal",
        format: "Format",
        aiAssist: "Mit KI vorbereiten",
        translateService: "Erneut automatisch übersetzen",
        serviceTranslating: "KI übersetzt…",
        serviceTranslated: "Übersetzungen wurden aktualisiert.",
        serviceTranslationHint:
            "Beim Speichern werden Name und Beschreibung automatisch aus der aktuellen Verwaltungssprache übersetzt.",
        aiReply: "Antwort vorschlagen",
        aiSocial: "Social-Text erstellen",
        aiReminder: "Erinnerung schreiben",
        consentRequired:
            "Vor Veröffentlichung muss die Zustimmung bestätigt werden.",
        trialFull: "Testphase: alle Funktionen sind freigeschaltet.",
        billing: "Tarif & Zahlung",
        domain: "Domain",
        business: "Betriebsprofil",
        team: "Team",
        languages: "Standardsprache",
        enabledLanguages: "Sprachen der öffentlichen App",
        notifications: "Benachrichtigungen",
        smsLog: "SMS-Protokoll",
        loading: "Wird geladen…",
        error: "Etwas ist schiefgelaufen.",
        noItems: "Noch keine Einträge.",
        status: "Status",
        date: "Datum",
        time: "Zeit",
        contact: "Kontakt",
        profile: "Profil",
        activity: "Aktivität",
        close: "Schließen",
        confirmMerge:
            "Diese Kontakte erst nach Identitätsprüfung zusammenführen?",
        done: "Erledigt",
        scheduled: "Geplant",
        reminders: "Erinnerungen",
        communication: "Kanäle",
        share: "Teilen",
        edit: "Bearbeiten",
        delete: "Löschen",
        weekdays: "Mo,Di,Mi,Do,Fr,Sa,So",
    },
    en: {
        socialAccounts: "Connected accounts",
        socialConnected: "Connected",
        socialNotConnected: "Not connected yet",
        socialProviderUnavailable:
            "This channel is not configured in LOOKDO yet.",
        socialConnectRequired: "Connect this channel account first.",
        socialPublished: "The post was published through the API.",
        socialDisconnectConfirm: "Disconnect this social account?",
        connect: "Connect",
        disconnect: "Disconnect",
        publishDirect: "Publish directly now",
        telegramTarget: "Telegram channel",
        telegramTargetPlaceholder:
            "@channel — add the bot as an administrator first",
        today: "Today",
        requests: "Requests",
        calendar: "Calendar",
        messages: "Messages",
        more: "More",
        customers: "Customers",
        works: "Work",
        services: "Services",
        settings: "Settings",
        account: "Account",
        logout: "Log out",
        openApp: "Open app",
        todayTitle: "Today at work",
        todayText: "Appointments, requests and free time at a glance.",
        appointmentsToday: "Appointments today",
        newRequests: "New requests",
        unreadMessages: "Unread",
        freeWindows: "Free slots",
        nextCustomer: "Next customer",
        noAppointment: "No appointment is planned today.",
        repeatCandidates: "Repeat visits due",
        unpublishedWorks: "Unpublished work",
        viewAll: "View all",
        search: "Search…",
        allStatuses: "All statuses",
        new: "New",
        viewed: "Viewed",
        in_progress: "In progress",
        waiting: "Waiting",
        completed: "Completed",
        cancelled: "Cancelled",
        no_show: "No show",
        reply: "Reply",
        send: "Send",
        internalNote: "Internal note",
        requestDetails: "Request details",
        showAllDetails: "Show all details",
        hideDetails: "Show less",
        closePreview: "Close preview",
        aiConditionAssessment: "AI condition assessment",
        notFilled: "Not provided",
        save: "Save",
        customer: "Customer",
        possibleDuplicate: "Possible duplicate",
        merge: "Merge after verification",
        notes: "Notes",
        tags: "Segments / tags",
        marketingConsent: "Marketing consent",
        publicationConsent: "Publication allowed",
        workingHours: "Working hours",
        contacts: "Contacts in the customer app",
        contactsHint: "Customers only see the contact methods you fill in.",
        website: "Website",
        blocks: "Blocks",
        addBlock: "Block time",
        vacation: "Vacation",
        personal: "Personal",
        blocked: "Blocked",
        exception: "Exception",
        from: "From",
        to: "To",
        reason: "Reason",
        add: "Add",
        service: "Service",
        duration: "Duration (min.)",
        bufferBefore: "Buffer before",
        bufferAfter: "Buffer after",
        repeatDays: "Repeat after days",
        price: "Price",
        booking: "Bookable online",
        media: "Photo/video allowed",
        active: "Active",
        addService: "Add service",
        appointment: "Appointment",
        addAppointment: "Add appointment",
        serviceLocation: "Service location",
        workshop: "At the studio / workshop",
        on_site: "At the customer's location",
        serviceAddress: "Service address",
        serviceAddressHint: "Address for the on-site appointment",
        reminder: "Reminder",
        addReminder: "Schedule reminder",
        portfolio: "Portfolio / Before-After",
        reviews: "Reviews",
        social: "Social content",
        addWork: "Add work",
        title: "Title",
        description: "Description",
        whatIncluded: "What's included?",
        serviceResult: "Result",
        published: "Published",
        featured: "Featured",
        before: "Before",
        after: "After",
        image: "Image",
        video: "Video",
        portfolioVideoHint:
            "MP4, WebM or MOV. The maximum size depends on your plan.",
        removeVideo: "Remove existing video",
        rating: "Rating",
        masterReply: "Reply from the business",
        caption: "Caption",
        channel: "Channel",
        format: "Format",
        aiAssist: "Prepare with AI",
        translateService: "Translate again automatically",
        serviceTranslating: "AI is translating…",
        serviceTranslated: "Translations have been updated.",
        serviceTranslationHint:
            "On save, the name and description are translated automatically from the current admin language.",
        aiReply: "Suggest reply",
        aiSocial: "Create social caption",
        aiReminder: "Write reminder",
        consentRequired: "Consent must be confirmed before publishing.",
        trialFull: "Trial: every feature is unlocked.",
        billing: "Plan & payment",
        domain: "Domain",
        business: "Business profile",
        team: "Team",
        languages: "Default language",
        enabledLanguages: "Public app languages",
        notifications: "Notifications",
        smsLog: "SMS log",
        loading: "Loading…",
        error: "Something went wrong.",
        noItems: "No entries yet.",
        status: "Status",
        date: "Date",
        time: "Time",
        contact: "Contact",
        profile: "Profile",
        activity: "Activity",
        close: "Close",
        confirmMerge: "Merge only after verifying this is the same person?",
        done: "Done",
        scheduled: "Scheduled",
        reminders: "Reminders",
        communication: "Channels",
        share: "Share",
        edit: "Edit",
        delete: "Delete",
        weekdays: "Mon,Tue,Wed,Thu,Fri,Sat,Sun",
    },
    ru: {
        socialAccounts: "Подключённые аккаунты",
        socialConnected: "Подключено",
        socialNotConnected: "Ещё не подключено",
        socialProviderUnavailable: "Этот канал ещё не настроен в LOOKDO.",
        socialConnectRequired: "Сначала подключите аккаунт этого канала.",
        socialPublished: "Публикация отправлена через API.",
        socialDisconnectConfirm: "Отключить этот аккаунт социальной сети?",
        connect: "Подключить",
        disconnect: "Отключить",
        publishDirect: "Опубликовать сейчас",
        telegramTarget: "Канал Telegram",
        telegramTargetPlaceholder:
            "@канал — сначала добавьте бота администратором",
        today: "Сегодня",
        requests: "Заявки",
        calendar: "Календарь",
        messages: "Сообщения",
        more: "Ещё",
        customers: "Клиенты",
        works: "Работы",
        services: "Услуги",
        settings: "Настройки",
        account: "Аккаунт",
        logout: "Выйти",
        openApp: "Открыть приложение",
        todayTitle: "Сегодня у мастера",
        todayText: "Записи, новые заявки и свободные окна в одном месте.",
        appointmentsToday: "Записи на сегодня",
        newRequests: "Новые заявки",
        unreadMessages: "Непрочитанные",
        freeWindows: "Свободные окна",
        nextCustomer: "Следующий клиент",
        noAppointment: "На сегодня записей пока нет.",
        repeatCandidates: "Пора пригласить повторно",
        unpublishedWorks: "Неопубликованные работы",
        viewAll: "Показать все",
        search: "Поиск…",
        allStatuses: "Все статусы",
        new: "Новая",
        viewed: "Просмотрена",
        in_progress: "В работе",
        waiting: "Ожидает",
        completed: "Завершена",
        cancelled: "Отменена",
        no_show: "Не пришёл",
        reply: "Ответить",
        send: "Отправить",
        internalNote: "Внутренняя заметка",
        requestDetails: "Данные заявки",
        showAllDetails: "Показать все данные",
        hideDetails: "Свернуть",
        closePreview: "Закрыть просмотр",
        aiConditionAssessment: "Оценка состояния от ИИ",
        notFilled: "Не заполнено",
        save: "Сохранить",
        customer: "Клиент",
        possibleDuplicate: "Возможный дубликат",
        merge: "Объединить после проверки",
        notes: "Заметки",
        tags: "Сегменты / метки",
        marketingConsent: "Согласие на маркетинг",
        publicationConsent: "Разрешена публикация",
        workingHours: "Рабочее время",
        contacts: "Контакты в приложении клиента",
        contactsHint:
            "Клиент увидит только те способы связи, которые вы заполните.",
        website: "Сайт",
        blocks: "Блокировки",
        addBlock: "Заблокировать время",
        vacation: "Отпуск",
        personal: "Личное",
        blocked: "Занято",
        exception: "Исключение",
        from: "С",
        to: "До",
        reason: "Причина",
        add: "Добавить",
        service: "Услуга",
        duration: "Длительность (мин.)",
        bufferBefore: "Буфер до",
        bufferAfter: "Буфер после",
        repeatDays: "Повтор через дней",
        price: "Цена",
        booking: "Доступна онлайн-запись",
        media: "Разрешены фото/видео",
        active: "Активна",
        addService: "Добавить услугу",
        appointment: "Запись",
        addAppointment: "Добавить запись",
        serviceLocation: "Место оказания услуги",
        workshop: "В студии / мастерской",
        on_site: "С выездом к клиенту",
        serviceAddress: "Адрес выезда",
        serviceAddressHint: "Адрес для выездной записи",
        reminder: "Напоминание",
        addReminder: "Запланировать напоминание",
        portfolio: "Портфолио / До и После",
        reviews: "Отзывы",
        social: "Контент для соцсетей",
        addWork: "Добавить работу",
        title: "Заголовок",
        description: "Описание",
        whatIncluded: "Что входит?",
        serviceResult: "Результат",
        published: "Опубликовано",
        featured: "Выделить",
        before: "До",
        after: "После",
        image: "Изображение",
        video: "Видео",
        portfolioVideoHint:
            "MP4, WebM или MOV. Максимальный размер зависит от тарифа.",
        removeVideo: "Удалить загруженное видео",
        rating: "Оценка",
        masterReply: "Ответ мастера",
        caption: "Текст публикации",
        channel: "Канал",
        format: "Формат",
        aiAssist: "Подготовить с ИИ",
        translateService: "Перевести заново автоматически",
        serviceTranslating: "ИИ переводит…",
        serviceTranslated: "Переводы обновлены.",
        serviceTranslationHint:
            "При сохранении название и описание автоматически переводятся с текущего языка админки.",
        aiReply: "Предложить ответ",
        aiSocial: "Создать текст публикации",
        aiReminder: "Написать напоминание",
        consentRequired:
            "Перед публикацией нужно подтвердить согласие клиента.",
        trialFull: "Пробный период: доступны все функции.",
        billing: "Тариф и оплата",
        domain: "Домен",
        business: "Профиль бизнеса",
        team: "Команда",
        languages: "Основной язык",
        enabledLanguages: "Языки публичного приложения",
        notifications: "Уведомления",
        smsLog: "Журнал SMS",
        loading: "Загрузка…",
        error: "Что-то пошло не так.",
        noItems: "Пока ничего нет.",
        status: "Статус",
        date: "Дата",
        time: "Время",
        contact: "Контакт",
        profile: "Профиль",
        activity: "Активность",
        close: "Закрыть",
        confirmMerge: "Объединить контакты только после проверки личности?",
        done: "Готово",
        scheduled: "Запланировано",
        reminders: "Напоминания",
        communication: "Каналы связи",
        share: "Поделиться",
        edit: "Изменить",
        delete: "Удалить",
        weekdays: "Пн,Вт,Ср,Чт,Пт,Сб,Вс",
    },
    uk: {
        socialAccounts: "Підключені акаунти",
        socialConnected: "Підключено",
        socialNotConnected: "Ще не підключено",
        socialProviderUnavailable: "Цей канал ще не налаштований у LOOKDO.",
        socialConnectRequired: "Спочатку підключіть акаунт цього каналу.",
        socialPublished: "Публікацію надіслано через API.",
        socialDisconnectConfirm: "Відключити цей акаунт соціальної мережі?",
        connect: "Підключити",
        disconnect: "Відключити",
        publishDirect: "Опублікувати зараз",
        telegramTarget: "Канал Telegram",
        telegramTargetPlaceholder:
            "@канал — спочатку додайте бота адміністратором",
        today: "Сьогодні",
        requests: "Заявки",
        calendar: "Календар",
        messages: "Повідомлення",
        more: "Ще",
        customers: "Клієнти",
        works: "Роботи",
        services: "Послуги",
        settings: "Налаштування",
        account: "Акаунт",
        logout: "Вийти",
        openApp: "Відкрити застосунок",
        todayTitle: "Сьогодні у майстра",
        todayText: "Записи, нові заявки та вільні вікна в одному місці.",
        appointmentsToday: "Записи на сьогодні",
        newRequests: "Нові заявки",
        unreadMessages: "Непрочитані",
        freeWindows: "Вільні вікна",
        nextCustomer: "Наступний клієнт",
        noAppointment: "На сьогодні записів поки немає.",
        repeatCandidates: "Час запросити повторно",
        unpublishedWorks: "Неопубліковані роботи",
        viewAll: "Показати всі",
        search: "Пошук…",
        allStatuses: "Усі статуси",
        new: "Нова",
        viewed: "Переглянута",
        in_progress: "У роботі",
        waiting: "Очікує",
        completed: "Завершена",
        cancelled: "Скасована",
        no_show: "Не прийшов",
        reply: "Відповісти",
        send: "Надіслати",
        internalNote: "Внутрішня нотатка",
        requestDetails: "Дані заявки",
        showAllDetails: "Показати всі дані",
        hideDetails: "Згорнути",
        closePreview: "Закрити перегляд",
        aiConditionAssessment: "Оцінка стану від ШІ",
        notFilled: "Не заповнено",
        save: "Зберегти",
        customer: "Клієнт",
        possibleDuplicate: "Можливий дублікат",
        merge: "Об’єднати після перевірки",
        notes: "Нотатки",
        tags: "Сегменти / мітки",
        marketingConsent: "Згода на маркетинг",
        publicationConsent: "Дозволена публікація",
        workingHours: "Робочий час",
        contacts: "Контакти в застосунку клієнта",
        contactsHint:
            "Клієнт побачить лише ті способи зв’язку, які ви заповните.",
        website: "Сайт",
        blocks: "Блокування",
        addBlock: "Заблокувати час",
        vacation: "Відпустка",
        personal: "Особисте",
        blocked: "Зайнято",
        exception: "Виняток",
        from: "З",
        to: "До",
        reason: "Причина",
        add: "Додати",
        service: "Послуга",
        duration: "Тривалість (хв.)",
        bufferBefore: "Буфер до",
        bufferAfter: "Буфер після",
        repeatDays: "Повтор через днів",
        price: "Ціна",
        booking: "Доступний онлайн-запис",
        media: "Дозволені фото/відео",
        active: "Активна",
        addService: "Додати послугу",
        appointment: "Запис",
        addAppointment: "Додати запис",
        serviceLocation: "Місце надання послуги",
        workshop: "У студії / майстерні",
        on_site: "З виїздом до клієнта",
        serviceAddress: "Адреса виїзду",
        serviceAddressHint: "Адреса для виїзного запису",
        reminder: "Нагадування",
        addReminder: "Запланувати нагадування",
        portfolio: "Портфоліо / До і Після",
        reviews: "Відгуки",
        social: "Контент для соцмереж",
        addWork: "Додати роботу",
        title: "Заголовок",
        description: "Опис",
        whatIncluded: "Що входить?",
        serviceResult: "Результат",
        published: "Опубліковано",
        featured: "Виділити",
        before: "До",
        after: "Після",
        image: "Зображення",
        video: "Відео",
        portfolioVideoHint:
            "MP4, WebM або MOV. Максимальний розмір залежить від тарифу.",
        removeVideo: "Видалити завантажене відео",
        rating: "Оцінка",
        masterReply: "Відповідь майстра",
        caption: "Текст публікації",
        channel: "Канал",
        format: "Формат",
        aiAssist: "Підготувати з ШІ",
        translateService: "Перекласти заново автоматично",
        serviceTranslating: "ШІ перекладає…",
        serviceTranslated: "Переклади оновлено.",
        serviceTranslationHint:
            "Під час збереження назва й опис автоматично перекладаються з поточної мови адмінки.",
        aiReply: "Запропонувати відповідь",
        aiSocial: "Створити текст публікації",
        aiReminder: "Написати нагадування",
        consentRequired: "Перед публікацією треба підтвердити згоду клієнта.",
        trialFull: "Пробний період: доступні всі функції.",
        billing: "Тариф і оплата",
        domain: "Домен",
        business: "Профіль бізнесу",
        team: "Команда",
        languages: "Основна мова",
        enabledLanguages: "Мови публічного застосунку",
        notifications: "Сповіщення",
        smsLog: "Журнал SMS",
        loading: "Завантаження…",
        error: "Щось пішло не так.",
        noItems: "Поки нічого немає.",
        status: "Статус",
        date: "Дата",
        time: "Час",
        contact: "Контакт",
        profile: "Профіль",
        activity: "Активність",
        close: "Закрити",
        confirmMerge: "Об’єднати контакти лише після перевірки особи?",
        done: "Готово",
        scheduled: "Заплановано",
        reminders: "Нагадування",
        communication: "Канали зв’язку",
        share: "Поділитися",
        edit: "Змінити",
        delete: "Видалити",
        weekdays: "Пн,Вт,Ср,Чт,Пт,Сб,Нд",
    },
};
const extra: Record<MasterLocale, Record<string, string>> = {
    de: {
        email: "E-Mail",
        accountIntro:
            "Hier ändern Sie Ihre persönlichen Anmeldedaten. Die öffentlichen Firmendaten bleiben davon getrennt.",
        ownerName: "Name des Kontoinhabers",
        loginEmail: "E-Mail für die Anmeldung",
        changePassword: "Passwort ändern (optional)",
        currentPassword: "Aktuelles Passwort",
        newPassword: "Neues Passwort",
        confirmNewPassword: "Neues Passwort bestätigen",
        accountSaved: "Kontodaten wurden gespeichert.",
        appAddress: "App-Adresse",
        country: "Land",
        timezone: "Zeitzone",
        manageSubscription: "Abo, Zahlungsmethode und Rechnungen verwalten",
        selectedAtRegistration: "Bei der Registrierung gewählt",
        paymentCurrency: "Zahlungswährung",
        paymentPeriod: "Zahlungszeitraum",
        choosePlan: "Tarife",
        choosePlanTitle: "Passenden Tarif auswählen und bezahlen",
        choosePlanIntro:
            "Ihre bisherige Auswahl ist markiert. Vergleichen Sie Leistungen und wechseln Sie bei Bedarf zu Pro oder Business.",
        yourSelection: "Ihre Auswahl",
        currentPlan: "Aktueller Tarif",
        paySelectedPlan: "Ausgewählten Tarif bezahlen",
        chooseAndPay: "Auswählen und bezahlen",
        perMonth: "pro Monat",
        perYear: "pro Jahr",
        priceUnavailable: "Preis nicht verfügbar",
        paymentHistory: "Zahlungsverlauf",
        invoiceHistory: "Rechnungen",
        openInvoice: "Rechnung öffnen",
        openReceipt: "Beleg öffnen",
        noInvoices: "Noch keine Rechnung vorhanden.",
        invoice_open: "Offen",
        invoice_paid: "Bezahlt",
        invoice_void: "Storniert",
        invoice_overdue: "Überfällig",
        activeAccess: "Zugang aktiv",
        newSetupLink: "Neuen Einrichtungslink",
        emailConfirmationSent:
            "Bestätigungslink wurde an die neue E-Mail-Adresse gesendet.",
        pendingEmail: "Bestätigung ausstehend",
        yourData: "Ihre Daten",
        exportIntro:
            "Laden Sie Kunden, Anfragen, Arbeiten, Termine, Bewertungen und Zahlungen als Archiv herunter.",
        exportData: "Alle Daten exportieren",
        deleteAccount: "App und Konto löschen",
        deleteAccountIntro:
            "Stripe-Abonnements werden beendet und die App mit allen lokalen Daten dauerhaft gelöscht.",
        typeBusinessName: "Firmenname zur Bestätigung eingeben",
        deleteAccountWarning:
            "App, Daten und gegebenenfalls das letzte Benutzerkonto wirklich dauerhaft löschen?",
        phone: "Telefon",
        city: "Stadt",
        street: "Straße",
        postalCode: "Postleitzahl",
        primaryColor: "Primärfarbe",
        secondaryColor: "Sekundärfarbe",
        primary: "Primär",
        minutes: "Min.",
        days: "Tage",
        monthly: "Monatlich",
        yearly: "Jährlich",
        domainUnavailable:
            "Eine eigene Domain ist in diesem Tarif nicht enthalten.",
        domainActive: "Domain und SSL sind aktiv",
        domainDnsPending: "Wartet auf DNS",
        domainProvisioning: "Wird in Plesk eingerichtet",
        domainSslPending: "DNS bestätigt, SSL wird eingerichtet",
        domainFailed: "Einrichtung fehlgeschlagen",
        domainDisabled: "Domain deaktiviert",
        domainConfigurationRequired:
            "Plesk-Verbindung muss eingerichtet werden",
        domainVerify: "DNS und SSL prüfen",
        domainDnsHint:
            "Richten Sie DNS auf LOOKDO und starten Sie danach die Prüfung. Domain und SSL werden automatisch in Plesk eingerichtet.",
        featureUnavailable:
            "Diese Funktion ist in Ihrem Tarif nicht enthalten.",
        name: "Name",
        role: "Rolle",
        owner: "Inhaber",
        staff: "Mitarbeiter",
        room: "Arbeitsplatz / Raum",
        manager: "Manager",
        addMember: "Mitarbeiter hinzufügen",
        removeMember: "Zugang entfernen",
        teamUsage: "Verwendete Zugänge",
        setupLink: "Einmaliger Einrichtungslink",
        copyLink: "Link kopieren",
        copied: "Kopiert",
        notificationIntro:
            "Legen Sie fest, über welche Kanäle Sie betriebliche Hinweise erhalten.",
        push: "Push",
        sms: "SMS",
        emailChannel: "E-Mail",
        feed: "Beitrag",
        story: "Story",
        draft: "Entwurf",
        ready: "Bereit",
        processing: "Wird verarbeitet",
        sent: "Gesendet",
        queued: "Warteschlange",
        manual: "Manuell senden",
        skipped: "Übersprungen",
        failed: "Fehlgeschlagen",
        phoneChannel: "Telefon",
        whatsapp: "WhatsApp",
        scheduleUnavailable:
            "Diese Funktion ist in Ihrem Tarif nicht enthalten.",
        customerRequired: "Bitte wählen Sie einen Kunden.",
        deleteAppointment: "Termin löschen",
        confirmDelete: "Diesen Eintrag wirklich löschen?",
        calendarEmpty: "Dieser Zeitraum ist frei.",
        breakTime: "Pause",
        editService: "Leistung bearbeiten",
        phoneVerified: "Telefon bestätigt",
        emailVerified: "E-Mail bestätigt",
        yes: "Ja",
        no: "Nein",
        customerHistory: "Verlauf",
        noHistory: "Noch kein Verlauf.",
        selectCustomer: "Kunden auswählen, um das Profil zu öffnen.",
        request: "Anfrage",
        team: "Team",
        pending: "Ausstehend",
        confirmed: "Bestätigt",
        complimentary: "Manuell freigeschaltet",
        trialing: "Testphase",
        unpaid: "Nicht bezahlt",
        paid: "Bezahlt",
        expired: "Abgelaufen",
        pushEnabled: "Push-Benachrichtigungen sind aktiviert.",
        pushDisabled: "Push-Benachrichtigungen sind deaktiviert.",
        pushDenied: "Der Browser hat Benachrichtigungen nicht erlaubt.",
        pushUnsupported: "Push wird von diesem Browser nicht unterstützt.",
        resources: "Ressourcen",
        resource: "Mitarbeiter / Ressource",
        resourcesHint:
            "Mitarbeiter, Arbeitsplätze und Geräte erhalten getrennte Termine.",
        anyResource: "Automatisch zuweisen",
        allResources: "Für alle Ressourcen",
        noResources: "Noch keine Ressource vorhanden.",
        addResource: "Ressource hinzufügen",
        editResource: "Ressource bearbeiten",
        resourceType: "Ressourcentyp",
        person: "Mitarbeiter",
        place: "Arbeitsplatz",
        equipment: "Gerät",
        color: "Farbe",
        sortOrder: "Reihenfolge",
        segments: "Kundensegmente",
        segmentsHint:
            "Ordnen Sie Kunden in eigene Gruppen ein; dynamische Gruppen werden automatisch berechnet.",
        segmentName: "Segmentname",
        segment_new: "Neu in 30 Tagen",
        segment_inactive: "Länger inaktiv",
        segment_marketing: "Marketing erlaubt",
        segment_repeat_due: "Wiederbesuch fällig",
    },
    en: {
        email: "Email",
        accountIntro:
            "Change your personal sign-in details here. Public business details are managed separately.",
        ownerName: "Account owner name",
        loginEmail: "Sign-in email",
        changePassword: "Change password (optional)",
        currentPassword: "Current password",
        newPassword: "New password",
        confirmNewPassword: "Confirm new password",
        accountSaved: "Account details have been saved.",
        appAddress: "App address",
        country: "Country",
        timezone: "Time zone",
        manageSubscription: "Manage subscription, payment method and invoices",
        selectedAtRegistration: "Selected during registration",
        paymentCurrency: "Payment currency",
        paymentPeriod: "Billing period",
        choosePlan: "Plans",
        choosePlanTitle: "Choose and pay for the right plan",
        choosePlanIntro:
            "Your previous selection is highlighted. Compare the included features and upgrade to Pro or Business when needed.",
        yourSelection: "Your selection",
        currentPlan: "Current plan",
        paySelectedPlan: "Pay for selected plan",
        chooseAndPay: "Choose and pay",
        perMonth: "per month",
        perYear: "per year",
        priceUnavailable: "Price unavailable",
        paymentHistory: "Payment history",
        invoiceHistory: "Invoices",
        openInvoice: "Open invoice",
        openReceipt: "Open receipt",
        noInvoices: "No invoice yet.",
        invoice_open: "Open",
        invoice_paid: "Paid",
        invoice_void: "Void",
        invoice_overdue: "Overdue",
        activeAccess: "Access active",
        newSetupLink: "New setup link",
        emailConfirmationSent:
            "A confirmation link was sent to the new email address.",
        pendingEmail: "Confirmation pending",
        yourData: "Your data",
        exportIntro:
            "Download customers, requests, work, appointments, reviews and payments as an archive.",
        exportData: "Export all data",
        deleteAccount: "Delete app and account",
        deleteAccountIntro:
            "Stripe subscriptions will be cancelled and the app with all local data will be permanently deleted.",
        typeBusinessName: "Enter the business name to confirm",
        deleteAccountWarning:
            "Permanently delete the app, its data and, if applicable, the last user account?",
        phone: "Phone",
        city: "City",
        street: "Street",
        postalCode: "Postal code",
        primaryColor: "Primary color",
        secondaryColor: "Secondary color",
        primary: "Primary",
        minutes: "min.",
        days: "days",
        monthly: "Monthly",
        yearly: "Yearly",
        domainUnavailable: "A custom domain is not included in this plan.",
        domainActive: "Domain and SSL are active",
        domainDnsPending: "Waiting for DNS",
        domainProvisioning: "Being provisioned in Plesk",
        domainSslPending: "DNS confirmed, SSL is being issued",
        domainFailed: "Provisioning failed",
        domainDisabled: "Domain disabled",
        domainConfigurationRequired: "The Plesk connection must be configured",
        domainVerify: "Check DNS and SSL",
        domainDnsHint:
            "Point DNS to LOOKDO, then start the check. The domain and SSL are provisioned automatically in Plesk.",
        featureUnavailable: "This feature is not included in your plan.",
        name: "Name",
        role: "Role",
        owner: "Owner",
        staff: "Staff",
        room: "Workstation / room",
        manager: "Manager",
        addMember: "Add team member",
        removeMember: "Remove access",
        teamUsage: "Seats used",
        setupLink: "One-time setup link",
        copyLink: "Copy link",
        copied: "Copied",
        notificationIntro: "Choose the channels for operational notifications.",
        push: "Push",
        sms: "SMS",
        emailChannel: "Email",
        feed: "Feed",
        story: "Story",
        draft: "Draft",
        ready: "Ready",
        processing: "Processing",
        sent: "Sent",
        queued: "Queued",
        manual: "Send manually",
        skipped: "Skipped",
        failed: "Failed",
        phoneChannel: "Phone",
        whatsapp: "WhatsApp",
        scheduleUnavailable: "This feature is not included in your plan.",
        customerRequired: "Please select a customer.",
        deleteAppointment: "Delete appointment",
        confirmDelete: "Delete this item?",
        calendarEmpty: "This time is free.",
        breakTime: "Break",
        editService: "Edit service",
        phoneVerified: "Phone verified",
        emailVerified: "Email verified",
        yes: "Yes",
        no: "No",
        customerHistory: "History",
        noHistory: "No history yet.",
        selectCustomer: "Select a customer to open the profile.",
        request: "Request",
        team: "Team",
        pending: "Pending",
        confirmed: "Confirmed",
        complimentary: "Manually enabled",
        trialing: "Trial",
        unpaid: "Unpaid",
        paid: "Paid",
        expired: "Expired",
        pushEnabled: "Push notifications are enabled.",
        pushDisabled: "Push notifications are disabled.",
        pushDenied: "The browser did not allow notifications.",
        pushUnsupported: "Push is not supported by this browser.",
        resources: "Resources",
        resource: "Staff / resource",
        resourcesHint:
            "Keep appointments separate for staff, workstations and equipment.",
        anyResource: "Assign automatically",
        allResources: "All resources",
        noResources: "No resource yet.",
        addResource: "Add resource",
        editResource: "Edit resource",
        resourceType: "Resource type",
        person: "Staff member",
        place: "Workstation",
        equipment: "Equipment",
        color: "Color",
        sortOrder: "Order",
        segments: "Customer segments",
        segmentsHint:
            "Organize customers in custom groups; smart groups are calculated automatically.",
        segmentName: "Segment name",
        segment_new: "New in 30 days",
        segment_inactive: "Long inactive",
        segment_marketing: "Marketing allowed",
        segment_repeat_due: "Repeat visit due",
    },
    ru: {
        email: "Электронная почта",
        accountIntro:
            "Здесь изменяются личные данные для входа. Публичные данные фирмы настраиваются отдельно.",
        ownerName: "Имя владельца аккаунта",
        loginEmail: "Email для входа",
        changePassword: "Изменить пароль (необязательно)",
        currentPassword: "Текущий пароль",
        newPassword: "Новый пароль",
        confirmNewPassword: "Повторите новый пароль",
        accountSaved: "Данные аккаунта сохранены.",
        appAddress: "Адрес приложения",
        country: "Страна",
        timezone: "Часовой пояс",
        manageSubscription: "Управлять подпиской, картой и счетами",
        selectedAtRegistration: "Выбрано при регистрации",
        paymentCurrency: "Валюта оплаты",
        paymentPeriod: "Период оплаты",
        choosePlan: "Тарифы",
        choosePlanTitle: "Выберите и оплатите подходящий тариф",
        choosePlanIntro:
            "Ваш первоначальный выбор выделен. Сравните возможности и при необходимости выберите Pro или Business.",
        yourSelection: "Ваш выбор",
        currentPlan: "Текущий тариф",
        paySelectedPlan: "Оплатить выбранный тариф",
        chooseAndPay: "Выбрать и оплатить",
        perMonth: "в месяц",
        perYear: "в год",
        priceUnavailable: "Цена не настроена",
        paymentHistory: "История платежей",
        invoiceHistory: "Счета",
        openInvoice: "Открыть счёт",
        openReceipt: "Открыть квитанцию",
        noInvoices: "Счетов пока нет.",
        invoice_open: "Открыт",
        invoice_paid: "Оплачен",
        invoice_void: "Аннулирован",
        invoice_overdue: "Просрочен",
        activeAccess: "Доступ активен",
        newSetupLink: "Новая ссылка для пароля",
        emailConfirmationSent:
            "На новый email отправлена ссылка для подтверждения.",
        pendingEmail: "Ожидает подтверждения",
        yourData: "Ваши данные",
        exportIntro:
            "Скачайте клиентов, заявки, работы, записи, отзывы и платежи одним архивом.",
        exportData: "Экспортировать все данные",
        deleteAccount: "Удалить приложение и аккаунт",
        deleteAccountIntro:
            "Подписка Stripe будет отменена, приложение и все локальные данные будут удалены безвозвратно.",
        typeBusinessName: "Для подтверждения введите название фирмы",
        deleteAccountWarning:
            "Безвозвратно удалить приложение, данные и, если это последний доступ, аккаунт пользователя?",
        phone: "Телефон",
        city: "Город",
        street: "Улица",
        postalCode: "Индекс",
        primaryColor: "Основной цвет",
        secondaryColor: "Дополнительный цвет",
        primary: "Основной",
        minutes: "мин.",
        days: "дней",
        monthly: "Ежемесячно",
        yearly: "Ежегодно",
        domainUnavailable: "Собственный домен не входит в этот тариф.",
        domainActive: "Домен и SSL активны",
        domainDnsPending: "Ожидается настройка DNS",
        domainProvisioning: "Домен создаётся в Plesk",
        domainSslPending: "DNS подтверждён, выпускается SSL",
        domainFailed: "Не удалось подключить домен",
        domainDisabled: "Домен отключён",
        domainConfigurationRequired: "Нужно настроить подключение к Plesk",
        domainVerify: "Проверить DNS и SSL",
        domainDnsHint:
            "Направьте DNS на LOOKDO и запустите проверку. Домен и SSL будут автоматически созданы в Plesk.",
        featureUnavailable: "Эта функция не входит в ваш тариф.",
        name: "Имя",
        role: "Роль",
        owner: "Владелец",
        staff: "Сотрудник",
        room: "Рабочее место / кабинет",
        manager: "Управляющий",
        addMember: "Добавить сотрудника",
        removeMember: "Закрыть доступ",
        teamUsage: "Использовано мест",
        setupLink: "Одноразовая ссылка для входа",
        copyLink: "Копировать ссылку",
        copied: "Скопировано",
        notificationIntro: "Выберите каналы служебных уведомлений.",
        push: "Push",
        sms: "SMS",
        emailChannel: "Электронная почта",
        feed: "Публикация",
        story: "История",
        draft: "Черновик",
        ready: "Готово",
        processing: "Обрабатывается",
        sent: "Отправлено",
        queued: "В очереди",
        manual: "Отправить вручную",
        skipped: "Пропущено",
        failed: "Ошибка",
        phoneChannel: "Телефон",
        whatsapp: "WhatsApp",
        scheduleUnavailable: "Эта функция не входит в ваш тариф.",
        customerRequired: "Выберите клиента.",
        deleteAppointment: "Удалить запись",
        confirmDelete: "Точно удалить эту запись?",
        calendarEmpty: "Это время свободно.",
        breakTime: "Перерыв",
        editService: "Изменить услугу",
        phoneVerified: "Телефон подтверждён",
        emailVerified: "Почта подтверждена",
        yes: "Да",
        no: "Нет",
        customerHistory: "История клиента",
        noHistory: "История пока пуста.",
        selectCustomer: "Выберите клиента, чтобы открыть его карточку.",
        request: "Заявка",
        team: "Команда",
        pending: "Ожидает",
        confirmed: "Подтверждена",
        complimentary: "Открыт вручную",
        trialing: "Пробный период",
        unpaid: "Не оплачено",
        paid: "Оплачено",
        expired: "Истёк",
        pushEnabled: "Push-уведомления включены.",
        pushDisabled: "Push-уведомления выключены.",
        pushDenied: "Браузер не разрешил уведомления.",
        pushUnsupported: "Этот браузер не поддерживает push-уведомления.",
        resources: "Ресурсы",
        resource: "Мастер / ресурс",
        resourcesHint:
            "Записи мастеров, рабочих мест и оборудования ведутся раздельно.",
        anyResource: "Назначить автоматически",
        allResources: "Для всех ресурсов",
        noResources: "Ресурсов пока нет.",
        addResource: "Добавить ресурс",
        editResource: "Изменить ресурс",
        resourceType: "Тип ресурса",
        person: "Сотрудник",
        place: "Рабочее место",
        equipment: "Оборудование",
        color: "Цвет",
        sortOrder: "Порядок",
        segments: "Сегменты клиентов",
        segmentsHint:
            "Объединяйте клиентов в свои группы; умные группы рассчитываются автоматически.",
        segmentName: "Название сегмента",
        segment_new: "Новые за 30 дней",
        segment_inactive: "Давно не обращались",
        segment_marketing: "Разрешён маркетинг",
        segment_repeat_due: "Пора пригласить повторно",
    },
    uk: {
        email: "Електронна пошта",
        accountIntro:
            "Тут змінюються особисті дані для входу. Публічні дані компанії налаштовуються окремо.",
        ownerName: "Ім’я власника акаунта",
        loginEmail: "Email для входу",
        changePassword: "Змінити пароль (необов’язково)",
        currentPassword: "Поточний пароль",
        newPassword: "Новий пароль",
        confirmNewPassword: "Повторіть новий пароль",
        accountSaved: "Дані акаунта збережено.",
        appAddress: "Адреса застосунку",
        country: "Країна",
        timezone: "Часовий пояс",
        manageSubscription: "Керувати підпискою, карткою та рахунками",
        selectedAtRegistration: "Обрано під час реєстрації",
        paymentCurrency: "Валюта оплати",
        paymentPeriod: "Період оплати",
        choosePlan: "Тарифи",
        choosePlanTitle: "Оберіть і сплатіть відповідний тариф",
        choosePlanIntro:
            "Ваш початковий вибір виділено. Порівняйте можливості та за потреби оберіть Pro або Business.",
        yourSelection: "Ваш вибір",
        currentPlan: "Поточний тариф",
        paySelectedPlan: "Сплатити обраний тариф",
        chooseAndPay: "Обрати й сплатити",
        perMonth: "на місяць",
        perYear: "на рік",
        priceUnavailable: "Ціну не налаштовано",
        paymentHistory: "Історія платежів",
        invoiceHistory: "Рахунки",
        openInvoice: "Відкрити рахунок",
        openReceipt: "Відкрити квитанцію",
        noInvoices: "Рахунків поки немає.",
        invoice_open: "Відкритий",
        invoice_paid: "Сплачений",
        invoice_void: "Анульований",
        invoice_overdue: "Прострочений",
        activeAccess: "Доступ активний",
        newSetupLink: "Нове посилання для пароля",
        emailConfirmationSent:
            "На новий email надіслано посилання для підтвердження.",
        pendingEmail: "Очікує підтвердження",
        yourData: "Ваші дані",
        exportIntro:
            "Завантажте клієнтів, заявки, роботи, записи, відгуки та платежі одним архівом.",
        exportData: "Експортувати всі дані",
        deleteAccount: "Видалити застосунок і акаунт",
        deleteAccountIntro:
            "Підписку Stripe буде скасовано, застосунок і всі локальні дані буде видалено назавжди.",
        typeBusinessName: "Для підтвердження введіть назву компанії",
        deleteAccountWarning:
            "Назавжди видалити застосунок, дані та, якщо це останній доступ, акаунт користувача?",
        phone: "Телефон",
        city: "Місто",
        street: "Вулиця",
        postalCode: "Індекс",
        primaryColor: "Основний колір",
        secondaryColor: "Додатковий колір",
        primary: "Основний",
        minutes: "хв.",
        days: "днів",
        monthly: "Щомісяця",
        yearly: "Щороку",
        domainUnavailable: "Власний домен не входить до цього тарифу.",
        domainActive: "Домен і SSL активні",
        domainDnsPending: "Очікується налаштування DNS",
        domainProvisioning: "Домен створюється у Plesk",
        domainSslPending: "DNS підтверджено, випускається SSL",
        domainFailed: "Не вдалося підключити домен",
        domainDisabled: "Домен вимкнено",
        domainConfigurationRequired:
            "Потрібно налаштувати підключення до Plesk",
        domainVerify: "Перевірити DNS і SSL",
        domainDnsHint:
            "Спрямуйте DNS на LOOKDO і запустіть перевірку. Домен і SSL будуть автоматично створені у Plesk.",
        featureUnavailable: "Ця функція не входить до вашого тарифу.",
        name: "Ім’я",
        role: "Роль",
        owner: "Власник",
        staff: "Співробітник",
        room: "Робоче місце / кабінет",
        manager: "Керівник",
        addMember: "Додати співробітника",
        removeMember: "Закрити доступ",
        teamUsage: "Використано місць",
        setupLink: "Одноразове посилання для входу",
        copyLink: "Копіювати посилання",
        copied: "Скопійовано",
        notificationIntro: "Оберіть канали службових сповіщень.",
        push: "Push",
        sms: "SMS",
        emailChannel: "Електронна пошта",
        feed: "Публікація",
        story: "Історія",
        draft: "Чернетка",
        ready: "Готово",
        processing: "Обробляється",
        sent: "Надіслано",
        queued: "У черзі",
        manual: "Надіслати вручну",
        skipped: "Пропущено",
        failed: "Помилка",
        phoneChannel: "Телефон",
        whatsapp: "WhatsApp",
        scheduleUnavailable: "Ця функція не входить до вашого тарифу.",
        customerRequired: "Оберіть клієнта.",
        deleteAppointment: "Видалити запис",
        confirmDelete: "Справді видалити цей запис?",
        calendarEmpty: "Цей час вільний.",
        breakTime: "Перерва",
        editService: "Змінити послугу",
        phoneVerified: "Телефон підтверджено",
        emailVerified: "Пошту підтверджено",
        yes: "Так",
        no: "Ні",
        customerHistory: "Історія клієнта",
        noHistory: "Історія поки порожня.",
        selectCustomer: "Оберіть клієнта, щоб відкрити його картку.",
        request: "Заявка",
        team: "Команда",
        pending: "Очікує",
        confirmed: "Підтверджено",
        complimentary: "Відкрито вручну",
        trialing: "Пробний період",
        unpaid: "Не сплачено",
        paid: "Сплачено",
        expired: "Завершено",
        pushEnabled: "Push-сповіщення увімкнено.",
        pushDisabled: "Push-сповіщення вимкнено.",
        pushDenied: "Браузер не дозволив сповіщення.",
        pushUnsupported: "Цей браузер не підтримує push-сповіщення.",
        resources: "Ресурси",
        resource: "Майстер / ресурс",
        resourcesHint:
            "Записи майстрів, робочих місць і обладнання ведуться окремо.",
        anyResource: "Призначити автоматично",
        allResources: "Для всіх ресурсів",
        noResources: "Ресурсів поки немає.",
        addResource: "Додати ресурс",
        editResource: "Змінити ресурс",
        resourceType: "Тип ресурсу",
        person: "Співробітник",
        place: "Робоче місце",
        equipment: "Обладнання",
        color: "Колір",
        sortOrder: "Порядок",
        segments: "Сегменти клієнтів",
        segmentsHint:
            "Об’єднуйте клієнтів у власні групи; розумні групи обчислюються автоматично.",
        segmentName: "Назва сегмента",
        segment_new: "Нові за 30 днів",
        segment_inactive: "Давно не зверталися",
        segment_marketing: "Дозволено маркетинг",
        segment_repeat_due: "Час запросити повторно",
    },
};
const workExtra: Record<MasterLocale, Record<string, string>> = {
    de: {
        socialSaved: "Entwurf gespeichert.",
        socialReady:
            "Inhalt ist vorbereitet. Text und Link wurden, soweit möglich, an den gewählten Kanal übergeben.",
        editWork: "Arbeit bearbeiten",
        beforeAfterHint:
            "Laden Sie zwei echte Aufnahmen hoch. Besucher können den Trenner später selbst nach links und rechts bewegen.",
        socialHint:
            "Text, Bild und Buchungslink für die Veröffentlichung vorbereiten.",
        downloadQr: "QR-Code herunterladen",
        socialComposer: "Veröffentlichung vorbereiten",
        socialImage: "Bild der Veröffentlichung",
        bookingLink: "Buchungs- oder App-Link",
        saveDraft: "Entwurf speichern",
        publishNow: "Teilen / veröffentlichen",
        drafts: "Gespeicherte Entwürfe",
        instagram: "Instagram",
        telegram: "Telegram",
        viber: "Viber",
        vk: "VK",
        facebook: "Facebook",
        linkedin: "LinkedIn",
        x: "X",
        status: "Status",
        configure: "Einrichten",
        socialProviderNeedsSetup:
            "Öffnen Sie die Einrichtung und tragen Sie Ihre Zugangsdaten ein.",
        socialProviderSetup: "Kanal einrichten",
        socialProviderSaved:
            "Die Kanaleinstellungen wurden sicher gespeichert.",
        socialProviderHelpTitle: "So erhalten Sie die Zugangsdaten",
        openOfficialInstructions: "Offizielle Anleitung öffnen",
        applicationId: "App-ID / Client-ID",
        applicationSecret: "App-Geheimnis / sicherer Schlüssel",
        telegramBotToken: "Bot-Token von BotFather",
        callbackUrl: "Callback-URL",
        callbackUrlHint:
            "Fügen Sie diese URL in den OAuth-Einstellungen der App als zulässige Weiterleitungs-URL ein.",
        secretStorageHint:
            "Geheimnisse werden verschlüsselt und gelten nur für diesen Betrieb.",
        saveAndConnect: "Speichern und verbinden",
        socialProviderHelp_instagram_1:
            "Öffnen Sie Meta for Developers und erstellen Sie eine Business-App.",
        socialProviderHelp_instagram_2:
            "Fügen Sie Instagram Graph API hinzu und kopieren Sie App-ID und App-Geheimnis.",
        socialProviderHelp_instagram_3:
            "Tragen Sie die unten angezeigte Callback-URL bei den gültigen OAuth-URLs ein.",
        socialProviderHelp_facebook_1:
            "Öffnen Sie Meta for Developers und erstellen Sie eine Business-App.",
        socialProviderHelp_facebook_2:
            "Fügen Sie Facebook Login hinzu und kopieren Sie App-ID und App-Geheimnis.",
        socialProviderHelp_facebook_3:
            "Tragen Sie die unten angezeigte Callback-URL bei den gültigen OAuth-URLs ein.",
        socialProviderHelp_vk_1: "Erstellen Sie in VK ID eine neue Anwendung.",
        socialProviderHelp_vk_2:
            "Kopieren Sie die Anwendungs-ID und den geschützten Schlüssel.",
        socialProviderHelp_vk_3:
            "Tragen Sie die unten angezeigte Callback-URL in den App-Einstellungen ein.",
        socialProviderHelp_telegram_1:
            "Öffnen Sie @BotFather in Telegram und senden Sie /newbot.",
        socialProviderHelp_telegram_2:
            "Folgen Sie den Schritten und kopieren Sie den ausgegebenen Bot-Token.",
        socialProviderHelp_telegram_3:
            "Fügen Sie den Bot als Administrator zu Ihrem Kanal hinzu und tragen Sie danach @kanal ein.",
    },
    en: {
        socialSaved: "Draft saved.",
        socialReady:
            "Content is ready. The text and link were passed to the selected channel where supported.",
        editWork: "Edit work",
        beforeAfterHint:
            "Upload two real photos. Visitors can drag the divider left and right.",
        socialHint:
            "Prepare the caption, image and booking link for publication.",
        downloadQr: "Download QR code",
        socialComposer: "Prepare publication",
        socialImage: "Publication image",
        bookingLink: "Booking or app link",
        saveDraft: "Save draft",
        publishNow: "Share / publish",
        drafts: "Saved drafts",
        instagram: "Instagram",
        telegram: "Telegram",
        viber: "Viber",
        vk: "VK",
        facebook: "Facebook",
        linkedin: "LinkedIn",
        x: "X",
        status: "Status",
        configure: "Set up",
        socialProviderNeedsSetup:
            "Open setup and enter the credentials for this channel.",
        socialProviderSetup: "Set up channel",
        socialProviderSaved: "Channel settings were stored securely.",
        socialProviderHelpTitle: "How to get the credentials",
        openOfficialInstructions: "Open official instructions",
        applicationId: "App ID / Client ID",
        applicationSecret: "App secret / secure key",
        telegramBotToken: "Bot token from BotFather",
        callbackUrl: "Callback URL",
        callbackUrlHint:
            "Add this URL to the app's allowed OAuth redirect URLs.",
        secretStorageHint:
            "Secrets are encrypted and apply only to this business.",
        saveAndConnect: "Save and connect",
        socialProviderHelp_instagram_1:
            "Open Meta for Developers and create a Business app.",
        socialProviderHelp_instagram_2:
            "Add Instagram Graph API and copy the App ID and App Secret.",
        socialProviderHelp_instagram_3:
            "Add the callback URL shown below to the valid OAuth redirect URLs.",
        socialProviderHelp_facebook_1:
            "Open Meta for Developers and create a Business app.",
        socialProviderHelp_facebook_2:
            "Add Facebook Login and copy the App ID and App Secret.",
        socialProviderHelp_facebook_3:
            "Add the callback URL shown below to the valid OAuth redirect URLs.",
        socialProviderHelp_vk_1: "Create a new application in VK ID.",
        socialProviderHelp_vk_2: "Copy the application ID and secure key.",
        socialProviderHelp_vk_3:
            "Add the callback URL shown below in the application settings.",
        socialProviderHelp_telegram_1:
            "Open @BotFather in Telegram and send /newbot.",
        socialProviderHelp_telegram_2:
            "Follow the prompts and copy the bot token it gives you.",
        socialProviderHelp_telegram_3:
            "Add the bot to your channel as an administrator, then enter @channel.",
    },
    ru: {
        socialSaved: "Черновик сохранён.",
        socialReady:
            "Материал подготовлен. Текст и ссылка переданы в выбранный канал там, где это поддерживается.",
        editWork: "Изменить работу",
        beforeAfterHint:
            "Загрузите два настоящих снимка. Посетитель сможет пальцем двигать границу влево и вправо.",
        socialHint:
            "Подготовьте текст, изображение и ссылку на запись для публикации.",
        downloadQr: "Скачать QR-код",
        socialComposer: "Подготовить публикацию",
        socialImage: "Изображение публикации",
        bookingLink: "Ссылка на запись или приложение",
        saveDraft: "Сохранить черновик",
        publishNow: "Поделиться / опубликовать",
        drafts: "Сохранённые черновики",
        instagram: "Instagram",
        telegram: "Telegram",
        viber: "Viber",
        vk: "VK",
        facebook: "Facebook",
        linkedin: "LinkedIn",
        x: "X",
        status: "Статус",
        configure: "Настроить",
        socialProviderNeedsSetup:
            "Откройте настройку и добавьте данные этого канала.",
        socialProviderSetup: "Настройка канала",
        socialProviderSaved: "Настройки канала защищённо сохранены.",
        socialProviderHelpTitle: "Как получить необходимые данные",
        openOfficialInstructions: "Открыть официальную инструкцию",
        applicationId: "ID приложения / Client ID",
        applicationSecret: "Секрет приложения / защищённый ключ",
        telegramBotToken: "Токен бота от BotFather",
        callbackUrl: "Адрес возврата (Callback URL)",
        callbackUrlHint:
            "Добавьте этот адрес в разрешённые OAuth Redirect URL в настройках приложения.",
        secretStorageHint:
            "Секреты хранятся в зашифрованном виде и относятся только к этому мастеру.",
        saveAndConnect: "Сохранить и подключить",
        socialProviderHelp_instagram_1:
            "Откройте Meta for Developers и создайте приложение типа Business.",
        socialProviderHelp_instagram_2:
            "Добавьте Instagram Graph API и скопируйте ID и секрет приложения.",
        socialProviderHelp_instagram_3:
            "Добавьте указанный ниже Callback URL в список разрешённых OAuth-адресов.",
        socialProviderHelp_facebook_1:
            "Откройте Meta for Developers и создайте приложение типа Business.",
        socialProviderHelp_facebook_2:
            "Добавьте Facebook Login и скопируйте ID и секрет приложения.",
        socialProviderHelp_facebook_3:
            "Добавьте указанный ниже Callback URL в список разрешённых OAuth-адресов.",
        socialProviderHelp_vk_1: "Создайте новое приложение в кабинете VK ID.",
        socialProviderHelp_vk_2: "Скопируйте ID приложения и защищённый ключ.",
        socialProviderHelp_vk_3:
            "Добавьте указанный ниже Callback URL в настройках приложения.",
        socialProviderHelp_telegram_1:
            "Откройте @BotFather в Telegram и отправьте команду /newbot.",
        socialProviderHelp_telegram_2:
            "Выполните его подсказки и скопируйте выданный токен бота.",
        socialProviderHelp_telegram_3:
            "Добавьте бота администратором канала, затем укажите @имя_канала.",
    },
    uk: {
        socialSaved: "Чернетку збережено.",
        socialReady:
            "Матеріал підготовлено. Текст і посилання передано до обраного каналу там, де це підтримується.",
        editWork: "Змінити роботу",
        beforeAfterHint:
            "Завантажте два справжні знімки. Відвідувач зможе пальцем рухати межу ліворуч і праворуч.",
        socialHint:
            "Підготуйте текст, зображення та посилання на запис для публікації.",
        downloadQr: "Завантажити QR-код",
        socialComposer: "Підготувати публікацію",
        socialImage: "Зображення публікації",
        bookingLink: "Посилання на запис або застосунок",
        saveDraft: "Зберегти чернетку",
        publishNow: "Поділитися / опублікувати",
        drafts: "Збережені чернетки",
        instagram: "Instagram",
        telegram: "Telegram",
        viber: "Viber",
        vk: "VK",
        facebook: "Facebook",
        linkedin: "LinkedIn",
        x: "X",
        status: "Статус",
        configure: "Налаштувати",
        socialProviderNeedsSetup:
            "Відкрийте налаштування та додайте дані цього каналу.",
        socialProviderSetup: "Налаштування каналу",
        socialProviderSaved: "Налаштування каналу захищено збережено.",
        socialProviderHelpTitle: "Як отримати необхідні дані",
        openOfficialInstructions: "Відкрити офіційну інструкцію",
        applicationId: "ID застосунку / Client ID",
        applicationSecret: "Секрет застосунку / захищений ключ",
        telegramBotToken: "Токен бота від BotFather",
        callbackUrl: "Адреса повернення (Callback URL)",
        callbackUrlHint:
            "Додайте цю адресу до дозволених OAuth Redirect URL у налаштуваннях застосунку.",
        secretStorageHint:
            "Секрети зберігаються зашифрованими й належать лише цьому майстру.",
        saveAndConnect: "Зберегти й підключити",
        socialProviderHelp_instagram_1:
            "Відкрийте Meta for Developers і створіть застосунок типу Business.",
        socialProviderHelp_instagram_2:
            "Додайте Instagram Graph API та скопіюйте ID і секрет застосунку.",
        socialProviderHelp_instagram_3:
            "Додайте Callback URL нижче до списку дозволених OAuth-адрес.",
        socialProviderHelp_facebook_1:
            "Відкрийте Meta for Developers і створіть застосунок типу Business.",
        socialProviderHelp_facebook_2:
            "Додайте Facebook Login та скопіюйте ID і секрет застосунку.",
        socialProviderHelp_facebook_3:
            "Додайте Callback URL нижче до списку дозволених OAuth-адрес.",
        socialProviderHelp_vk_1: "Створіть новий застосунок у кабінеті VK ID.",
        socialProviderHelp_vk_2: "Скопіюйте ID застосунку та захищений ключ.",
        socialProviderHelp_vk_3:
            "Додайте Callback URL нижче в налаштуваннях застосунку.",
        socialProviderHelp_telegram_1:
            "Відкрийте @BotFather у Telegram і надішліть команду /newbot.",
        socialProviderHelp_telegram_2:
            "Виконайте його підказки та скопіюйте виданий токен бота.",
        socialProviderHelp_telegram_3:
            "Додайте бота адміністратором каналу, потім укажіть @назву_каналу.",
    },
};
export const masterText = (locale: string, key: string) =>
    brandingServiceText(
        (locale in copy ? locale : "de") as MasterLocale,
        key,
    ) ||
    workExtra[(locale in copy ? locale : "de") as MasterLocale]?.[key] ||
    extra[(locale in copy ? locale : "de") as MasterLocale]?.[key] ||
    copy[(locale in copy ? locale : "de") as MasterLocale]?.[key] ||
    copy.de[key] ||
    key;
