import { brandingServiceText } from "./copy-branding";

export type MasterLocale = "de" | "en" | "ru" | "uk";
const copy: Record<MasterLocale, Record<string, string>> = {
    de: {
        socialAccounts: "Verbundene Konten",
        socialConnected: "Verbunden",
        socialNotConnected: "Noch nicht verbunden",
        socialProviderUnavailable: "Der Kanal ist in LOOKDO noch nicht konfiguriert.",
        socialConnectRequired: "Verbinden Sie zuerst das Konto dieses Kanals.",
        socialPublished: "Die Veröffentlichung wurde über die API gesendet.",
        socialDisconnectConfirm: "Dieses Social-Media-Konto trennen?",
        connect: "Verbinden",
        disconnect: "Trennen",
        publishDirect: "Jetzt direkt veröffentlichen",
        telegramTarget: "Telegram-Kanal",
        telegramTargetPlaceholder: "@kanal — Bot vorher als Administrator hinzufügen",
        today: "Heute",
        requests: "Anfragen",
        calendar: "Kalender",
        messages: "Nachrichten",
        more: "Mehr",
        customers: "Kunden",
        works: "Arbeiten",
        services: "Leistungen",
        settings: "Einstellungen",
        account: "Konto",
        logout: "Abmelden",
        openApp: "App öffnen",
        todayTitle: "Heute im Betrieb",
        todayText: "Termine, neue Anfragen und freie Zeiten auf einen Blick.",
        appointmentsToday: "Termine heute",
        newRequests: "Neue Anfragen",
        unreadMessages: "Ungelesen",
        freeWindows: "Freie Zeiten",
        nextCustomer: "Nächster Kunde",
        noAppointment: "Heute ist noch kein Termin geplant.",
        repeatCandidates: "Wiederbesuch fällig",
        unpublishedWorks: "Unveröffentlichte Arbeiten",
        viewAll: "Alle anzeigen",
        search: "Suchen…",
        allStatuses: "Alle Status",
        new: "Neu",
        viewed: "Gesehen",
        in_progress: "In Arbeit",
        waiting: "Wartet",
        completed: "Erledigt",
        cancelled: "Storniert",
        no_show: "Nicht erschienen",
        reply: "Antworten",
        send: "Senden",
        internalNote: "Interne Notiz",
        save: "Speichern",
        customer: "Kunde",
        possibleDuplicate: "Möglicher Doppelkontakt",
        merge: "Nach Prüfung zusammenführen",
        notes: "Notizen",
        tags: "Segmente / Tags",
        marketingConsent: "Marketing-Einwilligung",
        publicationConsent: "Veröffentlichung erlaubt",
        workingHours: "Arbeitszeiten",
        blocks: "Blockierungen",
        addBlock: "Zeit blockieren",
        vacation: "Urlaub",
        personal: "Privat",
        blocked: "Blockiert",
        exception: "Ausnahme",
        from: "Von",
        to: "Bis",
        reason: "Grund",
        add: "Hinzufügen",
        service: "Leistung",
        duration: "Dauer (Min.)",
        bufferBefore: "Puffer davor",
        bufferAfter: "Puffer danach",
        repeatDays: "Wiederholung nach Tagen",
        price: "Preis",
        booking: "Online buchbar",
        media: "Foto/Video erlaubt",
        active: "Aktiv",
        addService: "Leistung anlegen",
        appointment: "Termin",
        addAppointment: "Termin anlegen",
        reminder: "Erinnerung",
        addReminder: "Erinnerung planen",
        portfolio: "Portfolio / Vorher-Nachher",
        reviews: "Bewertungen",
        social: "Social Content",
        addWork: "Arbeit hinzufügen",
        title: "Titel",
        description: "Beschreibung",
        published: "Veröffentlicht",
        featured: "Hervorgehoben",
        before: "Vorher",
        after: "Nachher",
        image: "Bild",
        rating: "Bewertung",
        masterReply: "Antwort des Betriebs",
        caption: "Text",
        channel: "Kanal",
        format: "Format",
        aiAssist: "Mit KI vorbereiten",
        aiReply: "Antwort vorschlagen",
        aiSocial: "Social-Text erstellen",
        aiReminder: "Erinnerung schreiben",
        consentRequired:
            "Vor Veröffentlichung muss die Zustimmung bestätigt werden.",
        trialFull: "Testphase: alle Funktionen sind freigeschaltet.",
        billing: "Tarif & Zahlung",
        domain: "Domain",
        business: "Betriebsprofil",
        team: "Team",
        languages: "Sprachen",
        notifications: "Benachrichtigungen",
        smsLog: "SMS-Protokoll",
        loading: "Wird geladen…",
        error: "Etwas ist schiefgelaufen.",
        noItems: "Noch keine Einträge.",
        status: "Status",
        date: "Datum",
        time: "Zeit",
        contact: "Kontakt",
        profile: "Profil",
        activity: "Aktivität",
        close: "Schließen",
        confirmMerge:
            "Diese Kontakte erst nach Identitätsprüfung zusammenführen?",
        done: "Erledigt",
        scheduled: "Geplant",
        reminders: "Erinnerungen",
        communication: "Kanäle",
        share: "Teilen",
        edit: "Bearbeiten",
        delete: "Löschen",
        weekdays: "Mo,Di,Mi,Do,Fr,Sa,So",
    },
    en: {
        socialAccounts: "Connected accounts",
        socialConnected: "Connected",
        socialNotConnected: "Not connected yet",
        socialProviderUnavailable: "This channel is not configured in LOOKDO yet.",
        socialConnectRequired: "Connect this channel account first.",
        socialPublished: "The post was published through the API.",
        socialDisconnectConfirm: "Disconnect this social account?",
        connect: "Connect",
        disconnect: "Disconnect",
        publishDirect: "Publish directly now",
        telegramTarget: "Telegram channel",
        telegramTargetPlaceholder: "@channel — add the bot as an administrator first",
        today: "Today",
        requests: "Requests",
        calendar: "Calendar",
        messages: "Messages",
        more: "More",
        customers: "Customers",
        works: "Work",
        services: "Services",
        settings: "Settings",
        account: "Account",
        logout: "Log out",
        openApp: "Open app",
        todayTitle: "Today at work",
        todayText: "Appointments, requests and free time at a glance.",
        appointmentsToday: "Appointments today",
        newRequests: "New requests",
        unreadMessages: "Unread",
        freeWindows: "Free slots",
        nextCustomer: "Next customer",
        noAppointment: "No appointment is planned today.",
        repeatCandidates: "Repeat visits due",
        unpublishedWorks: "Unpublished work",
        viewAll: "View all",
        search: "Search…",
        allStatuses: "All statuses",
        new: "New",
        viewed: "Viewed",
        in_progress: "In progress",
        waiting: "Waiting",
        completed: "Completed",
        cancelled: "Cancelled",
        no_show: "No show",
        reply: "Reply",
        send: "Send",
        internalNote: "Internal note",
        save: "Save",
        customer: "Customer",
        possibleDuplicate: "Possible duplicate",
        merge: "Merge after verification",
        notes: "Notes",
        tags: "Segments / tags",
        marketingConsent: "Marketing consent",
        publicationConsent: "Publication allowed",
        workingHours: "Working hours",
        blocks: "Blocks",
        addBlock: "Block time",
        vacation: "Vacation",
        personal: "Personal",
        blocked: "Blocked",
        exception: "Exception",
        from: "From",
        to: "To",
        reason: "Reason",
        add: "Add",
        service: "Service",
        duration: "Duration (min.)",
        bufferBefore: "Buffer before",
        bufferAfter: "Buffer after",
        repeatDays: "Repeat after days",
        price: "Price",
        booking: "Bookable online",
        media: "Photo/video allowed",
        active: "Active",
        addService: "Add service",
        appointment: "Appointment",
        addAppointment: "Add appointment",
        reminder: "Reminder",
        addReminder: "Schedule reminder",
        portfolio: "Portfolio / Before-After",
        reviews: "Reviews",
        social: "Social content",
        addWork: "Add work",
        title: "Title",
        description: "Description",
        published: "Published",
        featured: "Featured",
        before: "Before",
        after: "After",
        image: "Image",
        rating: "Rating",
        masterReply: "Reply from the business",
        caption: "Caption",
        channel: "Channel",
        format: "Format",
        aiAssist: "Prepare with AI",
        aiReply: "Suggest reply",
        aiSocial: "Create social caption",
        aiReminder: "Write reminder",
        consentRequired: "Consent must be confirmed before publishing.",
        trialFull: "Trial: every feature is unlocked.",
        billing: "Plan & payment",
        domain: "Domain",
        business: "Business profile",
        team: "Team",
        languages: "Languages",
        notifications: "Notifications",
        smsLog: "SMS log",
        loading: "Loading…",
        error: "Something went wrong.",
        noItems: "No entries yet.",
        status: "Status",
        date: "Date",
        time: "Time",
        contact: "Contact",
        profile: "Profile",
        activity: "Activity",
        close: "Close",
        confirmMerge: "Merge only after verifying this is the same person?",
        done: "Done",
        scheduled: "Scheduled",
        reminders: "Reminders",
        communication: "Channels",
        share: "Share",
        edit: "Edit",
        delete: "Delete",
        weekdays: "Mon,Tue,Wed,Thu,Fri,Sat,Sun",
    },
    ru: {
        socialAccounts: "Подключённые аккаунты",
        socialConnected: "Подключено",
        socialNotConnected: "Ещё не подключено",
        socialProviderUnavailable: "Этот канал ещё не настроен в LOOKDO.",
        socialConnectRequired: "Сначала подключите аккаунт этого канала.",
        socialPublished: "Публикация отправлена через API.",
        socialDisconnectConfirm: "Отключить этот аккаунт социальной сети?",
        connect: "Подключить",
        disconnect: "Отключить",
        publishDirect: "Опубликовать сейчас",
        telegramTarget: "Канал Telegram",
        telegramTargetPlaceholder: "@канал — сначала добавьте бота администратором",
        today: "Сегодня",
        requests: "Заявки",
        calendar: "Календарь",
        messages: "Сообщения",
        more: "Ещё",
        customers: "Клиенты",
        works: "Работы",
        services: "Услуги",
        settings: "Настройки",
        account: "Аккаунт",
        logout: "Выйти",
        openApp: "Открыть приложение",
        todayTitle: "Сегодня у мастера",
        todayText: "Записи, новые заявки и свободные окна в одном месте.",
        appointmentsToday: "Записи на сегодня",
        newRequests: "Новые заявки",
        unreadMessages: "Непрочитанные",
        freeWindows: "Свободные окна",
        nextCustomer: "Следующий клиент",
        noAppointment: "На сегодня записей пока нет.",
        repeatCandidates: "Пора пригласить повторно",
        unpublishedWorks: "Неопубликованные работы",
        viewAll: "Показать все",
        search: "Поиск…",
        allStatuses: "Все статусы",
        new: "Новая",
        viewed: "Просмотрена",
        in_progress: "В работе",
        waiting: "Ожидает",
        completed: "Завершена",
        cancelled: "Отменена",
        no_show: "Не пришёл",
        reply: "Ответить",
        send: "Отправить",
        internalNote: "Внутренняя заметка",
        save: "Сохранить",
        customer: "Клиент",
        possibleDuplicate: "Возможный дубликат",
        merge: "Объединить после проверки",
        notes: "Заметки",
        tags: "Сегменты / метки",
        marketingConsent: "Согласие на маркетинг",
        publicationConsent: "Разрешена публикация",
        workingHours: "Рабочее время",
        blocks: "Блокировки",
        addBlock: "Заблокировать время",
        vacation: "Отпуск",
        personal: "Личное",
        blocked: "Занято",
        exception: "Исключение",
        from: "С",
        to: "До",
        reason: "Причина",
        add: "Добавить",
        service: "Услуга",
        duration: "Длительность (мин.)",
        bufferBefore: "Буфер до",
        bufferAfter: "Буфер после",
        repeatDays: "Повтор через дней",
        price: "Цена",
        booking: "Доступна онлайн-запись",
        media: "Разрешены фото/видео",
        active: "Активна",
        addService: "Добавить услугу",
        appointment: "Запись",
        addAppointment: "Добавить запись",
        reminder: "Напоминание",
        addReminder: "Запланировать напоминание",
        portfolio: "Портфолио / До и После",
        reviews: "Отзывы",
        social: "Контент для соцсетей",
        addWork: "Добавить работу",
        title: "Заголовок",
        description: "Описание",
        published: "Опубликовано",
        featured: "Выделить",
        before: "До",
        after: "После",
        image: "Изображение",
        rating: "Оценка",
        masterReply: "Ответ мастера",
        caption: "Текст публикации",
        channel: "Канал",
        format: "Формат",
        aiAssist: "Подготовить с ИИ",
        aiReply: "Предложить ответ",
        aiSocial: "Создать текст публикации",
        aiReminder: "Написать напоминание",
        consentRequired:
            "Перед публикацией нужно подтвердить согласие клиента.",
        trialFull: "Пробный период: доступны все функции.",
        billing: "Тариф и оплата",
        domain: "Домен",
        business: "Профиль бизнеса",
        team: "Команда",
        languages: "Языки",
        notifications: "Уведомления",
        smsLog: "Журнал SMS",
        loading: "Загрузка…",
        error: "Что-то пошло не так.",
        noItems: "Пока ничего нет.",
        status: "Статус",
        date: "Дата",
        time: "Время",
        contact: "Контакт",
        profile: "Профиль",
        activity: "Активность",
        close: "Закрыть",
        confirmMerge: "Объединить контакты только после проверки личности?",
        done: "Готово",
        scheduled: "Запланировано",
        reminders: "Напоминания",
        communication: "Каналы связи",
        share: "Поделиться",
        edit: "Изменить",
        delete: "Удалить",
        weekdays: "Пн,Вт,Ср,Чт,Пт,Сб,Вс",
    },
    uk: {
        socialAccounts: "Підключені акаунти",
        socialConnected: "Підключено",
        socialNotConnected: "Ще не підключено",
        socialProviderUnavailable: "Цей канал ще не налаштований у LOOKDO.",
        socialConnectRequired: "Спочатку підключіть акаунт цього каналу.",
        socialPublished: "Публікацію надіслано через API.",
        socialDisconnectConfirm: "Відключити цей акаунт соціальної мережі?",
        connect: "Підключити",
        disconnect: "Відключити",
        publishDirect: "Опублікувати зараз",
        telegramTarget: "Канал Telegram",
        telegramTargetPlaceholder: "@канал — спочатку додайте бота адміністратором",
        today: "Сьогодні",
        requests: "Заявки",
        calendar: "Календар",
        messages: "Повідомлення",
        more: "Ще",
        customers: "Клієнти",
        works: "Роботи",
        services: "Послуги",
        settings: "Налаштування",
        account: "Акаунт",
        logout: "Вийти",
        openApp: "Відкрити застосунок",
        todayTitle: "Сьогодні у майстра",
        todayText: "Записи, нові заявки та вільні вікна в одному місці.",
        appointmentsToday: "Записи на сьогодні",
        newRequests: "Нові заявки",
        unreadMessages: "Непрочитані",
        freeWindows: "Вільні вікна",
        nextCustomer: "Наступний клієнт",
        noAppointment: "На сьогодні записів поки немає.",
        repeatCandidates: "Час запросити повторно",
        unpublishedWorks: "Неопубліковані роботи",
        viewAll: "Показати всі",
        search: "Пошук…",
        allStatuses: "Усі статуси",
        new: "Нова",
        viewed: "Переглянута",
        in_progress: "У роботі",
        waiting: "Очікує",
        completed: "Завершена",
        cancelled: "Скасована",
        no_show: "Не прийшов",
        reply: "Відповісти",
        send: "Надіслати",
        internalNote: "Внутрішня нотатка",
        save: "Зберегти",
        customer: "Клієнт",
        possibleDuplicate: "Можливий дублікат",
        merge: "Об’єднати після перевірки",
        notes: "Нотатки",
        tags: "Сегменти / мітки",
        marketingConsent: "Згода на маркетинг",
        publicationConsent: "Дозволена публікація",
        workingHours: "Робочий час",
        blocks: "Блокування",
        addBlock: "Заблокувати час",
        vacation: "Відпустка",
        personal: "Особисте",
        blocked: "Зайнято",
        exception: "Виняток",
        from: "З",
        to: "До",
        reason: "Причина",
        add: "Додати",
        service: "Послуга",
        duration: "Тривалість (хв.)",
        bufferBefore: "Буфер до",
        bufferAfter: "Буфер після",
        repeatDays: "Повтор через днів",
        price: "Ціна",
        booking: "Доступний онлайн-запис",
        media: "Дозволені фото/відео",
        active: "Активна",
        addService: "Додати послугу",
        appointment: "Запис",
        addAppointment: "Додати запис",
        reminder: "Нагадування",
        addReminder: "Запланувати нагадування",
        portfolio: "Портфоліо / До і Після",
        reviews: "Відгуки",
        social: "Контент для соцмереж",
        addWork: "Додати роботу",
        title: "Заголовок",
        description: "Опис",
        published: "Опубліковано",
        featured: "Виділити",
        before: "До",
        after: "Після",
        image: "Зображення",
        rating: "Оцінка",
        masterReply: "Відповідь майстра",
        caption: "Текст публікації",
        channel: "Канал",
        format: "Формат",
        aiAssist: "Підготувати з ШІ",
        aiReply: "Запропонувати відповідь",
        aiSocial: "Створити текст публікації",
        aiReminder: "Написати нагадування",
        consentRequired: "Перед публікацією треба підтвердити згоду клієнта.",
        trialFull: "Пробний період: доступні всі функції.",
        billing: "Тариф і оплата",
        domain: "Домен",
        business: "Профіль бізнесу",
        team: "Команда",
        languages: "Мови",
        notifications: "Сповіщення",
        smsLog: "Журнал SMS",
        loading: "Завантаження…",
        error: "Щось пішло не так.",
        noItems: "Поки нічого немає.",
        status: "Статус",
        date: "Дата",
        time: "Час",
        contact: "Контакт",
        profile: "Профіль",
        activity: "Активність",
        close: "Закрити",
        confirmMerge: "Об’єднати контакти лише після перевірки особи?",
        done: "Готово",
        scheduled: "Заплановано",
        reminders: "Нагадування",
        communication: "Канали зв’язку",
        share: "Поділитися",
        edit: "Змінити",
        delete: "Видалити",
        weekdays: "Пн,Вт,Ср,Чт,Пт,Сб,Нд",
    },
};
const extra: Record<MasterLocale, Record<string, string>> = {
    de: {
        email: "E-Mail",
        phone: "Telefon",
        city: "Stadt",
        street: "Straße",
        postalCode: "Postleitzahl",
        primaryColor: "Primärfarbe",
        secondaryColor: "Sekundärfarbe",
        primary: "Primär",
        minutes: "Min.",
        days: "Tage",
        monthly: "Monatlich",
        yearly: "Jährlich",
        domainUnavailable:
            "Eine eigene Domain ist in diesem Tarif nicht enthalten.",
        domainActive: "Domain und SSL sind aktiv",
        domainDnsPending: "Wartet auf DNS",
        domainProvisioning: "Wird in Plesk eingerichtet",
        domainSslPending: "DNS bestätigt, SSL wird eingerichtet",
        domainFailed: "Einrichtung fehlgeschlagen",
        domainDisabled: "Domain deaktiviert",
        domainConfigurationRequired: "Plesk-Verbindung muss eingerichtet werden",
        domainVerify: "DNS und SSL prüfen",
        domainDnsHint: "Richten Sie DNS auf LOOKDO und starten Sie danach die Prüfung. Domain und SSL werden automatisch in Plesk eingerichtet.",
        featureUnavailable:
            "Diese Funktion ist in Ihrem Tarif nicht enthalten.",
        name: "Name",
        role: "Rolle",
        owner: "Inhaber",
        staff: "Mitarbeiter",
        room: "Arbeitsplatz / Raum",
        manager: "Manager",
        addMember: "Mitarbeiter hinzufügen",
        removeMember: "Zugang entfernen",
        teamUsage: "Verwendete Zugänge",
        setupLink: "Einmaliger Einrichtungslink",
        copyLink: "Link kopieren",
        copied: "Kopiert",
        notificationIntro:
            "Legen Sie fest, über welche Kanäle Sie betriebliche Hinweise erhalten.",
        push: "Push",
        sms: "SMS",
        emailChannel: "E-Mail",
        feed: "Beitrag",
        story: "Story",
        draft: "Entwurf",
        ready: "Bereit",
        processing: "Wird verarbeitet",
        sent: "Gesendet",
        queued: "Warteschlange",
        manual: "Manuell senden",
        skipped: "Übersprungen",
        failed: "Fehlgeschlagen",
        phoneChannel: "Telefon",
        whatsapp: "WhatsApp",
        scheduleUnavailable:
            "Diese Funktion ist in Ihrem Tarif nicht enthalten.",
        customerRequired: "Bitte wählen Sie einen Kunden.",
        deleteAppointment: "Termin löschen",
        confirmDelete: "Diesen Eintrag wirklich löschen?",
        calendarEmpty: "Dieser Zeitraum ist frei.",
        breakTime: "Pause",
        editService: "Leistung bearbeiten",
        phoneVerified: "Telefon bestätigt",
        emailVerified: "E-Mail bestätigt",
        yes: "Ja",
        no: "Nein",
        customerHistory: "Verlauf",
        noHistory: "Noch kein Verlauf.",
        selectCustomer: "Kunden auswählen, um das Profil zu öffnen.",
        request: "Anfrage",
        team: "Team",
        pending: "Ausstehend",
        confirmed: "Bestätigt",
        complimentary: "Manuell freigeschaltet",
        trialing: "Testphase",
        unpaid: "Nicht bezahlt",
        paid: "Bezahlt",
        expired: "Abgelaufen",
        pushEnabled: "Push-Benachrichtigungen sind aktiviert.",
        pushDisabled: "Push-Benachrichtigungen sind deaktiviert.",
        pushDenied: "Der Browser hat Benachrichtigungen nicht erlaubt.",
        pushUnsupported: "Push wird von diesem Browser nicht unterstützt.",
        resources: "Ressourcen",
        resource: "Mitarbeiter / Ressource",
        resourcesHint:
            "Mitarbeiter, Arbeitsplätze und Geräte erhalten getrennte Termine.",
        anyResource: "Automatisch zuweisen",
        allResources: "Für alle Ressourcen",
        noResources: "Noch keine Ressource vorhanden.",
        addResource: "Ressource hinzufügen",
        editResource: "Ressource bearbeiten",
        resourceType: "Ressourcentyp",
        person: "Mitarbeiter",
        place: "Arbeitsplatz",
        equipment: "Gerät",
        color: "Farbe",
        sortOrder: "Reihenfolge",
        segments: "Kundensegmente",
        segmentsHint:
            "Ordnen Sie Kunden in eigene Gruppen ein; dynamische Gruppen werden automatisch berechnet.",
        segmentName: "Segmentname",
        segment_new: "Neu in 30 Tagen",
        segment_inactive: "Länger inaktiv",
        segment_marketing: "Marketing erlaubt",
        segment_repeat_due: "Wiederbesuch fällig",
    },
    en: {
        email: "Email",
        phone: "Phone",
        city: "City",
        street: "Street",
        postalCode: "Postal code",
        primaryColor: "Primary color",
        secondaryColor: "Secondary color",
        primary: "Primary",
        minutes: "min.",
        days: "days",
        monthly: "Monthly",
        yearly: "Yearly",
        domainUnavailable: "A custom domain is not included in this plan.",
        domainActive: "Domain and SSL are active",
        domainDnsPending: "Waiting for DNS",
        domainProvisioning: "Being provisioned in Plesk",
        domainSslPending: "DNS confirmed, SSL is being issued",
        domainFailed: "Provisioning failed",
        domainDisabled: "Domain disabled",
        domainConfigurationRequired: "The Plesk connection must be configured",
        domainVerify: "Check DNS and SSL",
        domainDnsHint: "Point DNS to LOOKDO, then start the check. The domain and SSL are provisioned automatically in Plesk.",
        featureUnavailable: "This feature is not included in your plan.",
        name: "Name",
        role: "Role",
        owner: "Owner",
        staff: "Staff",
        room: "Workstation / room",
        manager: "Manager",
        addMember: "Add team member",
        removeMember: "Remove access",
        teamUsage: "Seats used",
        setupLink: "One-time setup link",
        copyLink: "Copy link",
        copied: "Copied",
        notificationIntro: "Choose the channels for operational notifications.",
        push: "Push",
        sms: "SMS",
        emailChannel: "Email",
        feed: "Feed",
        story: "Story",
        draft: "Draft",
        ready: "Ready",
        processing: "Processing",
        sent: "Sent",
        queued: "Queued",
        manual: "Send manually",
        skipped: "Skipped",
        failed: "Failed",
        phoneChannel: "Phone",
        whatsapp: "WhatsApp",
        scheduleUnavailable: "This feature is not included in your plan.",
        customerRequired: "Please select a customer.",
        deleteAppointment: "Delete appointment",
        confirmDelete: "Delete this item?",
        calendarEmpty: "This time is free.",
        breakTime: "Break",
        editService: "Edit service",
        phoneVerified: "Phone verified",
        emailVerified: "Email verified",
        yes: "Yes",
        no: "No",
        customerHistory: "History",
        noHistory: "No history yet.",
        selectCustomer: "Select a customer to open the profile.",
        request: "Request",
        team: "Team",
        pending: "Pending",
        confirmed: "Confirmed",
        complimentary: "Manually enabled",
        trialing: "Trial",
        unpaid: "Unpaid",
        paid: "Paid",
        expired: "Expired",
        pushEnabled: "Push notifications are enabled.",
        pushDisabled: "Push notifications are disabled.",
        pushDenied: "The browser did not allow notifications.",
        pushUnsupported: "Push is not supported by this browser.",
        resources: "Resources",
        resource: "Staff / resource",
        resourcesHint:
            "Keep appointments separate for staff, workstations and equipment.",
        anyResource: "Assign automatically",
        allResources: "All resources",
        noResources: "No resource yet.",
        addResource: "Add resource",
        editResource: "Edit resource",
        resourceType: "Resource type",
        person: "Staff member",
        place: "Workstation",
        equipment: "Equipment",
        color: "Color",
        sortOrder: "Order",
        segments: "Customer segments",
        segmentsHint:
            "Organize customers in custom groups; smart groups are calculated automatically.",
        segmentName: "Segment name",
        segment_new: "New in 30 days",
        segment_inactive: "Long inactive",
        segment_marketing: "Marketing allowed",
        segment_repeat_due: "Repeat visit due",
    },
    ru: {
        email: "Электронная почта",
        phone: "Телефон",
        city: "Город",
        street: "Улица",
        postalCode: "Индекс",
        primaryColor: "Основной цвет",
        secondaryColor: "Дополнительный цвет",
        primary: "Основной",
        minutes: "мин.",
        days: "дней",
        monthly: "Ежемесячно",
        yearly: "Ежегодно",
        domainUnavailable: "Собственный домен не входит в этот тариф.",
        domainActive: "Домен и SSL активны",
        domainDnsPending: "Ожидается настройка DNS",
        domainProvisioning: "Домен создаётся в Plesk",
        domainSslPending: "DNS подтверждён, выпускается SSL",
        domainFailed: "Не удалось подключить домен",
        domainDisabled: "Домен отключён",
        domainConfigurationRequired: "Нужно настроить подключение к Plesk",
        domainVerify: "Проверить DNS и SSL",
        domainDnsHint: "Направьте DNS на LOOKDO и запустите проверку. Домен и SSL будут автоматически созданы в Plesk.",
        featureUnavailable: "Эта функция не входит в ваш тариф.",
        name: "Имя",
        role: "Роль",
        owner: "Владелец",
        staff: "Сотрудник",
        room: "Рабочее место / кабинет",
        manager: "Управляющий",
        addMember: "Добавить сотрудника",
        removeMember: "Закрыть доступ",
        teamUsage: "Использовано мест",
        setupLink: "Одноразовая ссылка для входа",
        copyLink: "Копировать ссылку",
        copied: "Скопировано",
        notificationIntro: "Выберите каналы служебных уведомлений.",
        push: "Push",
        sms: "SMS",
        emailChannel: "Электронная почта",
        feed: "Публикация",
        story: "История",
        draft: "Черновик",
        ready: "Готово",
        processing: "Обрабатывается",
        sent: "Отправлено",
        queued: "В очереди",
        manual: "Отправить вручную",
        skipped: "Пропущено",
        failed: "Ошибка",
        phoneChannel: "Телефон",
        whatsapp: "WhatsApp",
        scheduleUnavailable: "Эта функция не входит в ваш тариф.",
        customerRequired: "Выберите клиента.",
        deleteAppointment: "Удалить запись",
        confirmDelete: "Точно удалить эту запись?",
        calendarEmpty: "Это время свободно.",
        breakTime: "Перерыв",
        editService: "Изменить услугу",
        phoneVerified: "Телефон подтверждён",
        emailVerified: "Почта подтверждена",
        yes: "Да",
        no: "Нет",
        customerHistory: "История клиента",
        noHistory: "История пока пуста.",
        selectCustomer: "Выберите клиента, чтобы открыть его карточку.",
        request: "Заявка",
        team: "Команда",
        pending: "Ожидает",
        confirmed: "Подтверждена",
        complimentary: "Открыт вручную",
        trialing: "Пробный период",
        unpaid: "Не оплачено",
        paid: "Оплачено",
        expired: "Истёк",
        pushEnabled: "Push-уведомления включены.",
        pushDisabled: "Push-уведомления выключены.",
        pushDenied: "Браузер не разрешил уведомления.",
        pushUnsupported: "Этот браузер не поддерживает push-уведомления.",
        resources: "Ресурсы",
        resource: "Мастер / ресурс",
        resourcesHint:
            "Записи мастеров, рабочих мест и оборудования ведутся раздельно.",
        anyResource: "Назначить автоматически",
        allResources: "Для всех ресурсов",
        noResources: "Ресурсов пока нет.",
        addResource: "Добавить ресурс",
        editResource: "Изменить ресурс",
        resourceType: "Тип ресурса",
        person: "Сотрудник",
        place: "Рабочее место",
        equipment: "Оборудование",
        color: "Цвет",
        sortOrder: "Порядок",
        segments: "Сегменты клиентов",
        segmentsHint:
            "Объединяйте клиентов в свои группы; умные группы рассчитываются автоматически.",
        segmentName: "Название сегмента",
        segment_new: "Новые за 30 дней",
        segment_inactive: "Давно не обращались",
        segment_marketing: "Разрешён маркетинг",
        segment_repeat_due: "Пора пригласить повторно",
    },
    uk: {
        email: "Електронна пошта",
        phone: "Телефон",
        city: "Місто",
        street: "Вулиця",
        postalCode: "Індекс",
        primaryColor: "Основний колір",
        secondaryColor: "Додатковий колір",
        primary: "Основний",
        minutes: "хв.",
        days: "днів",
        monthly: "Щомісяця",
        yearly: "Щороку",
        domainUnavailable: "Власний домен не входить до цього тарифу.",
        domainActive: "Домен і SSL активні",
        domainDnsPending: "Очікується налаштування DNS",
        domainProvisioning: "Домен створюється у Plesk",
        domainSslPending: "DNS підтверджено, випускається SSL",
        domainFailed: "Не вдалося підключити домен",
        domainDisabled: "Домен вимкнено",
        domainConfigurationRequired: "Потрібно налаштувати підключення до Plesk",
        domainVerify: "Перевірити DNS і SSL",
        domainDnsHint: "Спрямуйте DNS на LOOKDO і запустіть перевірку. Домен і SSL будуть автоматично створені у Plesk.",
        featureUnavailable: "Ця функція не входить до вашого тарифу.",
        name: "Ім’я",
        role: "Роль",
        owner: "Власник",
        staff: "Співробітник",
        room: "Робоче місце / кабінет",
        manager: "Керівник",
        addMember: "Додати співробітника",
        removeMember: "Закрити доступ",
        teamUsage: "Використано місць",
        setupLink: "Одноразове посилання для входу",
        copyLink: "Копіювати посилання",
        copied: "Скопійовано",
        notificationIntro: "Оберіть канали службових сповіщень.",
        push: "Push",
        sms: "SMS",
        emailChannel: "Електронна пошта",
        feed: "Публікація",
        story: "Історія",
        draft: "Чернетка",
        ready: "Готово",
        processing: "Обробляється",
        sent: "Надіслано",
        queued: "У черзі",
        manual: "Надіслати вручну",
        skipped: "Пропущено",
        failed: "Помилка",
        phoneChannel: "Телефон",
        whatsapp: "WhatsApp",
        scheduleUnavailable: "Ця функція не входить до вашого тарифу.",
        customerRequired: "Оберіть клієнта.",
        deleteAppointment: "Видалити запис",
        confirmDelete: "Справді видалити цей запис?",
        calendarEmpty: "Цей час вільний.",
        breakTime: "Перерва",
        editService: "Змінити послугу",
        phoneVerified: "Телефон підтверджено",
        emailVerified: "Пошту підтверджено",
        yes: "Так",
        no: "Ні",
        customerHistory: "Історія клієнта",
        noHistory: "Історія поки порожня.",
        selectCustomer: "Оберіть клієнта, щоб відкрити його картку.",
        request: "Заявка",
        team: "Команда",
        pending: "Очікує",
        confirmed: "Підтверджено",
        complimentary: "Відкрито вручну",
        trialing: "Пробний період",
        unpaid: "Не сплачено",
        paid: "Сплачено",
        expired: "Завершено",
        pushEnabled: "Push-сповіщення увімкнено.",
        pushDisabled: "Push-сповіщення вимкнено.",
        pushDenied: "Браузер не дозволив сповіщення.",
        pushUnsupported: "Цей браузер не підтримує push-сповіщення.",
        resources: "Ресурси",
        resource: "Майстер / ресурс",
        resourcesHint:
            "Записи майстрів, робочих місць і обладнання ведуться окремо.",
        anyResource: "Призначити автоматично",
        allResources: "Для всіх ресурсів",
        noResources: "Ресурсів поки немає.",
        addResource: "Додати ресурс",
        editResource: "Змінити ресурс",
        resourceType: "Тип ресурсу",
        person: "Співробітник",
        place: "Робоче місце",
        equipment: "Обладнання",
        color: "Колір",
        sortOrder: "Порядок",
        segments: "Сегменти клієнтів",
        segmentsHint:
            "Об’єднуйте клієнтів у власні групи; розумні групи обчислюються автоматично.",
        segmentName: "Назва сегмента",
        segment_new: "Нові за 30 днів",
        segment_inactive: "Давно не зверталися",
        segment_marketing: "Дозволено маркетинг",
        segment_repeat_due: "Час запросити повторно",
    },
};
const workExtra: Record<MasterLocale, Record<string, string>> = {
    de: {
        socialSaved: "Entwurf gespeichert.",
        socialReady:
            "Inhalt ist vorbereitet. Text und Link wurden, soweit möglich, an den gewählten Kanal übergeben.",
        editWork: "Arbeit bearbeiten",
        beforeAfterHint:
            "Laden Sie zwei echte Aufnahmen hoch. Besucher können den Trenner später selbst nach links und rechts bewegen.",
        socialHint:
            "Text, Bild und Buchungslink für die Veröffentlichung vorbereiten.",
        downloadQr: "QR-Code herunterladen",
        socialComposer: "Veröffentlichung vorbereiten",
        socialImage: "Bild der Veröffentlichung",
        bookingLink: "Buchungs- oder App-Link",
        saveDraft: "Entwurf speichern",
        publishNow: "Teilen / veröffentlichen",
        drafts: "Gespeicherte Entwürfe",
        instagram: "Instagram",
        telegram: "Telegram",
        viber: "Viber",
        vk: "VK",
        facebook: "Facebook",
        linkedin: "LinkedIn",
        x: "X",
        status: "Status",
    },
    en: {
        socialSaved: "Draft saved.",
        socialReady:
            "Content is ready. The text and link were passed to the selected channel where supported.",
        editWork: "Edit work",
        beforeAfterHint:
            "Upload two real photos. Visitors can drag the divider left and right.",
        socialHint:
            "Prepare the caption, image and booking link for publication.",
        downloadQr: "Download QR code",
        socialComposer: "Prepare publication",
        socialImage: "Publication image",
        bookingLink: "Booking or app link",
        saveDraft: "Save draft",
        publishNow: "Share / publish",
        drafts: "Saved drafts",
        instagram: "Instagram",
        telegram: "Telegram",
        viber: "Viber",
        vk: "VK",
        facebook: "Facebook",
        linkedin: "LinkedIn",
        x: "X",
        status: "Status",
    },
    ru: {
        socialSaved: "Черновик сохранён.",
        socialReady:
            "Материал подготовлен. Текст и ссылка переданы в выбранный канал там, где это поддерживается.",
        editWork: "Изменить работу",
        beforeAfterHint:
            "Загрузите два настоящих снимка. Посетитель сможет пальцем двигать границу влево и вправо.",
        socialHint:
            "Подготовьте текст, изображение и ссылку на запись для публикации.",
        downloadQr: "Скачать QR-код",
        socialComposer: "Подготовить публикацию",
        socialImage: "Изображение публикации",
        bookingLink: "Ссылка на запись или приложение",
        saveDraft: "Сохранить черновик",
        publishNow: "Поделиться / опубликовать",
        drafts: "Сохранённые черновики",
        instagram: "Instagram",
        telegram: "Telegram",
        viber: "Viber",
        vk: "VK",
        facebook: "Facebook",
        linkedin: "LinkedIn",
        x: "X",
        status: "Статус",
    },
    uk: {
        socialSaved: "Чернетку збережено.",
        socialReady:
            "Матеріал підготовлено. Текст і посилання передано до обраного каналу там, де це підтримується.",
        editWork: "Змінити роботу",
        beforeAfterHint:
            "Завантажте два справжні знімки. Відвідувач зможе пальцем рухати межу ліворуч і праворуч.",
        socialHint:
            "Підготуйте текст, зображення та посилання на запис для публікації.",
        downloadQr: "Завантажити QR-код",
        socialComposer: "Підготувати публікацію",
        socialImage: "Зображення публікації",
        bookingLink: "Посилання на запис або застосунок",
        saveDraft: "Зберегти чернетку",
        publishNow: "Поділитися / опублікувати",
        drafts: "Збережені чернетки",
        instagram: "Instagram",
        telegram: "Telegram",
        viber: "Viber",
        vk: "VK",
        facebook: "Facebook",
        linkedin: "LinkedIn",
        x: "X",
        status: "Статус",
    },
};
export const masterText = (locale: string, key: string) =>
    brandingServiceText(
        (locale in copy ? locale : "de") as MasterLocale,
        key,
    ) ||
    workExtra[(locale in copy ? locale : "de") as MasterLocale]?.[key] ||
    extra[(locale in copy ? locale : "de") as MasterLocale]?.[key] ||
    copy[(locale in copy ? locale : "de") as MasterLocale]?.[key] ||
    copy.de[key] ||
    key;
