<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue';
import {api} from '../api';
const props=defineProps<{tenantId:number;locale:string;t:(key:string)=>string}>();
const data=ref<any>({portfolio:[],reviews:[],social:[],entitlements:{}}),tab=ref('portfolio'),busy=ref(false),error=ref(''),aiContext=ref(''),aiResult=ref('');
const work=reactive<any>({title:'',description:'',featured:false,published:false,publication_confirmed:false,image:null,before:null,after:null});
const review=reactive<any>({rating:5,author_name:'',body:'',published:false,publication_confirmed:false});
const social=reactive<any>({portfolio_item_id:'',format:'feed',channel:'share',locale:props.locale,caption:'',image_path:'',booking_url:'',status:'draft'});
const enabled=(key:string)=>String(data.value.entitlements?.[key]||'0')==='1';
const hasBeforeAfter=computed(()=>enabled('before_after_enabled')),hasSocial=computed(()=>enabled('social_content_enabled')),hasAi=computed(()=>enabled('ai_communication_enabled'));
const tabs=computed(()=>['portfolio','reviews',...(hasSocial.value?['social']:[]),...(hasAi.value?['aiAssist']:[])]);
async function load(){busy.value=true;error.value='';try{data.value=await api(`/tenant/${props.tenantId}/content-workspace`);if(!tabs.value.includes(tab.value))tab.value='portfolio'}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function saveWork(){const f=new FormData();f.append(`title[${props.locale}]`,work.title);f.append(`description[${props.locale}]`,work.description);for(const x of ['featured','published','publication_confirmed'])f.append(x,work[x]?'1':'0');for(const x of ['image','before','after'])if(work[x])f.append(x,work[x]);busy.value=true;try{await api(`/tenant/${props.tenantId}/portfolio`,{method:'POST',body:f});Object.assign(work,{title:'',description:'',featured:false,published:false,publication_confirmed:false,image:null,before:null,after:null});await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function saveReview(){busy.value=true;try{await api(`/tenant/${props.tenantId}/reviews`,{method:'POST',body:JSON.stringify(review)});Object.assign(review,{rating:5,author_name:'',body:'',published:false,publication_confirmed:false});await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function saveSocial(){busy.value=true;try{await api(`/tenant/${props.tenantId}/social-drafts`,{method:'POST',body:JSON.stringify({...social,portfolio_item_id:social.portfolio_item_id||null,booking_url:social.booking_url||null})});Object.assign(social,{portfolio_item_id:'',format:'feed',channel:'share',locale:props.locale,caption:'',image_path:'',booking_url:'',status:'draft'});await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function remove(kind:string,id:number){if(!confirm(props.t('confirmDelete')))return;const url=kind==='portfolio'?`/tenant/${props.tenantId}/portfolio/${id}`:kind==='reviews'?`/tenant/${props.tenantId}/reviews/${id}`:`/tenant/${props.tenantId}/social-drafts/${id}`;await api(url,{method:'DELETE'});await load()}
async function ai(task:string){if(!aiContext.value.trim())return;busy.value=true;try{const r:any=await api(`/tenant/${props.tenantId}/workspace/ai`,{method:'POST',body:JSON.stringify({task,locale:props.locale,context:aiContext.value})});aiResult.value=r.text;if(task==='social')social.caption=r.text}catch(e:any){error.value=e.message}finally{busy.value=false}}
const localized=(x:any)=>x?.[props.locale]||x?.de||Object.values(x||{})[0]||'';
onMounted(load);
</script>
<template><section class="mw-stack"><header class="mw-page-head"><div><p class="mw-kicker">LOOKDO</p><h1>{{t('works')}}</h1></div></header><nav class="mw-tabs"><button v-for="x in tabs" :key="x" :class="{active:tab===x}" @click="tab=x">{{t(x)}}</button></nav><p v-if="error" class="mw-error">{{error}}</p>
<div v-if="tab==='portfolio'" class="mw-two"><div class="mw-work-grid"><article v-for="item in data.portfolio" :key="item.id"><img v-if="item.after_image_url||item.image_url||item.before_image_url" :src="item.after_image_url||item.image_url||item.before_image_url"><span><b>{{localized(item.title)||t('works')}}</b><small>{{item.published?t('published'):t('scheduled')}}</small></span><button class="mw-danger-link" @click="remove('portfolio',item.id)">{{t('delete')}}</button></article><p v-if="!data.portfolio.length" class="mw-empty">{{t('noItems')}}</p></div><form class="mw-panel mw-form" @submit.prevent="saveWork"><h2>{{t('addWork')}}</h2><label>{{t('title')}}<input v-model="work.title" required></label><label>{{t('description')}}<textarea v-model="work.description"></textarea></label><label>{{t('image')}}<input type="file" accept="image/*" @change="work.image=($event.target as HTMLInputElement).files?.[0]"></label><template v-if="hasBeforeAfter"><label>{{t('before')}}<input type="file" accept="image/*" @change="work.before=($event.target as HTMLInputElement).files?.[0]"></label><label>{{t('after')}}<input type="file" accept="image/*" @change="work.after=($event.target as HTMLInputElement).files?.[0]"></label></template><label class="mw-check"><input v-model="work.featured" type="checkbox">{{t('featured')}}</label><label class="mw-check"><input v-model="work.published" type="checkbox">{{t('published')}}</label><label v-if="work.published" class="mw-check mw-warning"><input v-model="work.publication_confirmed" type="checkbox">{{t('consentRequired')}}</label><button class="mw-primary">{{t('save')}}</button></form></div>
<div v-if="tab==='reviews'" class="mw-two"><div class="mw-panel"><article v-for="item in data.reviews" :key="item.id" class="mw-review"><strong>{{'★'.repeat(item.rating)}}{{'☆'.repeat(5-item.rating)}}</strong><b>{{item.author_name}}</b><p>{{item.body}}</p><small>{{item.published?t('published'):t('scheduled')}}</small><button class="mw-danger-link" @click="remove('reviews',item.id)">{{t('delete')}}</button></article><p v-if="!data.reviews.length" class="mw-empty">{{t('noItems')}}</p></div><form class="mw-panel mw-form" @submit.prevent="saveReview"><h2>{{t('reviews')}}</h2><label>{{t('rating')}}<input v-model.number="review.rating" type="number" min="1" max="5"></label><label>{{t('customer')}}<input v-model="review.author_name"></label><label>{{t('description')}}<textarea v-model="review.body"></textarea></label><label class="mw-check"><input v-model="review.published" type="checkbox">{{t('published')}}</label><label v-if="review.published" class="mw-check mw-warning"><input v-model="review.publication_confirmed" type="checkbox">{{t('consentRequired')}}</label><button class="mw-primary">{{t('save')}}</button></form></div>
<div v-if="tab==='social'&&hasSocial" class="mw-two"><div class="mw-panel"><article v-for="item in data.social" :key="item.id" class="mw-review"><b>{{item.channel}} · {{t(item.format)}}</b><p>{{item.caption}}</p><small>{{t(item.status)}}</small><button class="mw-danger-link" @click="remove('social',item.id)">{{t('delete')}}</button></article><p v-if="!data.social.length" class="mw-empty">{{t('noItems')}}</p></div><form class="mw-panel mw-form" @submit.prevent="saveSocial"><h2>{{t('social')}}</h2><label>{{t('portfolio')}}<select v-model="social.portfolio_item_id"><option value=""></option><option v-for="item in data.portfolio" :key="item.id" :value="item.id">{{localized(item.title)}}</option></select></label><label>{{t('format')}}<select v-model="social.format"><option value="feed">{{t('feed')}}</option><option value="story">{{t('story')}}</option><option value="status">{{t('status')}}</option></select></label><label>{{t('channel')}}<select v-model="social.channel"><option v-for="x in ['share','instagram','whatsapp','telegram','viber','vk']" :key="x" :value="x">{{t(x)}}</option></select></label><label>{{t('caption')}}<textarea v-model="social.caption" rows="6"></textarea></label><button v-if="hasAi" type="button" class="mw-secondary" @click="aiContext=social.caption;ai('social')">{{t('aiSocial')}}</button><button class="mw-primary">{{t('save')}}</button></form></div>
<div v-if="tab==='aiAssist'&&hasAi" class="mw-panel mw-ai"><h2>{{t('aiAssist')}}</h2><textarea v-model="aiContext" rows="8" :placeholder="t('description')"></textarea><div><button class="mw-secondary" @click="ai('reply')">{{t('aiReply')}}</button><button class="mw-secondary" @click="ai('reminder')">{{t('aiReminder')}}</button><button v-if="hasSocial" class="mw-secondary" @click="ai('social')">{{t('aiSocial')}}</button></div><textarea v-if="aiResult" v-model="aiResult" rows="8"></textarea></div>
</section></template>