<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue';import {api} from '../api';
const props=defineProps<{tenantId:number;mode:'requests'|'messages';locale:string;entitlements?:Record<string,string>;t:(key:string)=>string}>();
const hasAi=computed(()=>String(props.entitlements?.ai_communication_enabled||'0')==='1');
const items=ref<any[]>([]),selected=ref<any>(null),search=ref(''),status=ref(''),reply=ref(''),note=ref(''),busy=ref(false),error=ref('');
async function load(){busy.value=true;error.value='';try{if(props.mode==='messages'){const r:any=await api(`/tenant/${props.tenantId}/workspace/conversations`);items.value=r.items}else{const q=new URLSearchParams();if(search.value)q.set('search',search.value);if(status.value)q.set('status',status.value);const r:any=await api(`/tenant/${props.tenantId}/workspace/requests?${q}`);items.value=r.items.data}}catch(e:any){error.value=e.message}finally{busy.value=false}}
function choose(item:any){selected.value=props.mode==='messages'?item.request:item;note.value=selected.value.internal_note||'';if(props.mode==='requests'&&!selected.value.messages)loadDetail(item.id)}
async function loadDetail(id:number){const r:any=await api(`/tenant/${props.tenantId}/workspace/requests?search=`);const found=r.items.data.find((x:any)=>x.id===id);if(found)selected.value=found}
async function saveStatus(value:string){if(!selected.value)return;busy.value=true;try{const r:any=await api(`/tenant/${props.tenantId}/workspace/requests/${selected.value.id}`,{method:'PUT',body:JSON.stringify({status:value,internal_note:note.value})});selected.value=r.request;await load()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function suggest(){if(!selected.value)return;busy.value=true;error.value='';try{const context=[selected.value.summary,...(selected.value.messages||[]).slice(-8).map((x:any)=>x.body)].filter(Boolean).join('\\n');const r:any=await api(`/tenant/${props.tenantId}/workspace/ai`,{method:'POST',body:JSON.stringify({task:'reply',locale:props.locale,context})});reply.value=r.text}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function send(){if(!selected.value||!reply.value.trim())return;busy.value=true;try{await api(`/tenant/${props.tenantId}/workspace/requests/${selected.value.id}/reply`,{method:'POST',body:JSON.stringify({body:reply.value,event:selected.value.status==='completed'?'work_ready':'master_replied'})});reply.value='';await load();if(props.mode==='messages')choose(items.value.find((x:any)=>x.request.id===selected.value.id)||items.value[0])}catch(e:any){error.value=e.message}finally{busy.value=false}}
watch(()=>props.mode,load);onMounted(load);
</script>
<template><section class="mw-stack"><header class="mw-page-head"><div><p class="mw-kicker">LOOKDO</p><h1>{{t(mode)}}</h1></div></header><div class="mw-toolbar"><input v-model="search" :placeholder="t('search')" @keyup.enter="load"><select v-if="mode==='requests'" v-model="status" @change="load"><option value="">{{t('allStatuses')}}</option><option v-for="s in ['new','viewed','in_progress','waiting','completed','cancelled']" :key="s" :value="s">{{t(s)}}</option></select></div><p v-if="error" class="mw-error">{{error}}</p><div class="mw-inbox"><div class="mw-inbox-list"><button v-for="entry in items" :key="mode==='messages'?entry.request.id:entry.id" :class="{active:selected?.id===(mode==='messages'?entry.request.id:entry.id)}" @click="choose(entry)"><span class="mw-avatar">{{((mode==='messages'?entry.customer:entry.customer)?.name||'?').slice(0,1)}}</span><span><b>{{(mode==='messages'?entry.customer:entry.customer)?.name||(mode==='messages'?entry.customer:entry.customer)?.phone}}</b><small>{{mode==='messages'?(entry.last_message?.body||entry.request.summary):(entry.summary||entry.number)}}</small></span><em v-if="mode==='messages'&&entry.unread">{{entry.unread}}</em><em v-else>{{t((mode==='messages'?entry.request:entry).status)}}</em></button><p v-if="!items.length&&!busy" class="mw-empty">{{t('noItems')}}</p></div><article v-if="selected" class="mw-thread"><header><button class="mw-thread-close" @click="selected=null">×</button><div><p class="mw-kicker">{{selected.number}}</p><h2>{{selected.customer?.name||selected.customer?.phone}}</h2><p>{{selected.summary}}</p></div><select :value="selected.status" @change="saveStatus(($event.target as HTMLSelectElement).value)"><option v-for="s in ['new','viewed','in_progress','waiting','completed','cancelled']" :key="s" :value="s">{{t(s)}}</option></select></header><div v-if="selected.media?.length" class="mw-media"><a v-for="media in selected.media" :key="media.id" :href="media.url" target="_blank"><img v-if="media.type==='image'" :src="media.url"><span v-else>▶</span></a></div><div class="mw-messages"><p v-for="message in selected.messages" :key="message.id" :class="message.sender_type||message.sender"><span>{{message.body}}</span><time>{{new Date(message.created_at).toLocaleString()}}</time></p></div><label>{{t('internalNote')}}<textarea v-model="note" rows="3"></textarea></label><button class="mw-secondary" @click="saveStatus(selected.status)">{{t('save')}}</button><form class="mw-reply" @submit.prevent="send"><button v-if="hasAi" type="button" class="mw-secondary" @click="suggest">{{t('aiReply')}}</button><textarea v-model="reply" rows="2" :placeholder="t('reply')"></textarea><button :disabled="busy">{{t('send')}}</button></form></article><article v-else class="mw-thread mw-empty">{{t('noItems')}}</article></div></section></template>