<script setup lang="ts">
import {computed,reactive,ref,watch} from 'vue';
import {api} from '../api';
import LineIcon from '../components/LineIcon.vue';
const props=defineProps<{tenantId:number;account:any;workspace:any;plans:any[];section:string;locale:string;t:(key:string)=>string}>();
const emit=defineEmits<{reload:[];navigate:[section:string]}>();
const busy=ref(false),error=ref(''),domain=ref(''),cycle=ref('monthly'),currency=ref(props.locale==='ru'?'RUB':props.locale==='uk'?'UAH':'EUR');
const profile=reactive<any>({}),team=ref<any>({members:[],limit:1,can_manage:false}),member=reactive({name:'',email:'',role:'staff'}),setupUrl=ref(''),copied=ref(false),pushStatus=ref('');
const entitlementEnabled=(key:string,fallback=false)=>String(props.account?.entitlements?.[key]??(fallback?'1':'0'))==='1';
const hasDomain=computed(()=>entitlementEnabled('custom_domain'));
const hasSms=computed(()=>entitlementEnabled('sms_enabled'));
const hasPush=computed(()=>Boolean(props.workspace?.push?.enabled&&props.workspace?.push?.public_key));
const moreItems=computed(()=>[['customers','user'],['work','photo'],['services','tools'],['business','briefcase'],['branding','photo'],['billing','card'],['team','user'],['settings','grid'],...(hasDomain.value?[['domain','globe']]:[])]);
watch(()=>props.account,v=>{if(v)Object.assign(profile,{name:v.tenant.name,locale:v.tenant.locale,...(v.tenant.profile||{}),notification_preferences:{push:true,sms:false,email:false,...(v.tenant.profile?.content?.notifications||{})}})},{immediate:true});
watch(()=>props.section,s=>{if(s==='team')loadTeam()},{immediate:true});
async function saveProfile(){busy.value=true;error.value='';pushStatus.value='';try{await api(`/tenant/${props.tenantId}/profile`,{method:'PUT',body:JSON.stringify(profile)});if(hasPush.value)await syncPush(Boolean(profile.notification_preferences.push));emit('reload')}catch(e:any){error.value=e.message}finally{busy.value=false}}
function applicationServerKey(value:string):Uint8Array{const padding='='.repeat((4-value.length%4)%4);const base64=(value+padding).replace(/-/g,'+').replace(/_/g,'/');return Uint8Array.from(atob(base64),char=>char.charCodeAt(0))}
async function syncPush(enabled:boolean){if(!('Notification' in window)||!('serviceWorker' in navigator)){pushStatus.value=props.t('pushUnsupported');return}const registration=await navigator.serviceWorker.ready;const current=await registration.pushManager.getSubscription();if(!enabled){if(current){await api(`/tenant/${props.tenantId}/workspace/push-subscriptions`,{method:'DELETE',body:JSON.stringify({endpoint:current.endpoint})});await current.unsubscribe()}pushStatus.value=props.t('pushDisabled');return}const permission=await Notification.requestPermission();if(permission!=='granted'){profile.notification_preferences.push=false;pushStatus.value=props.t('pushDenied');return}const subscription=current||await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:applicationServerKey(props.workspace.push.public_key) as BufferSource});const json=subscription.toJSON();await api(`/tenant/${props.tenantId}/workspace/push-subscriptions`,{method:'POST',body:JSON.stringify({endpoint:subscription.endpoint,keys:json.keys})});pushStatus.value=props.t('pushEnabled')}
async function addDomain(){busy.value=true;error.value='';try{await api(`/tenant/${props.tenantId}/domains`,{method:'POST',body:JSON.stringify({domain:domain.value})});domain.value='';emit('reload')}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function checkout(planId:number){busy.value=true;error.value='';try{const r:any=await api(`/tenant/${props.tenantId}/checkout`,{method:'POST',body:JSON.stringify({plan_id:planId,cycle:cycle.value,currency:currency.value})});location.href=r.checkout_url}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function loadTeam(){try{team.value=await api(`/tenant/${props.tenantId}/workspace/team`)}catch(e:any){error.value=e.message}}
async function addMember(){busy.value=true;error.value='';try{const r:any=await api(`/tenant/${props.tenantId}/workspace/team`,{method:'POST',body:JSON.stringify(member)});setupUrl.value=r.setup_url||'';Object.assign(member,{name:'',email:'',role:'staff'});await loadTeam()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function removeMember(id:number){if(!confirm(props.t('confirmDelete')))return;try{await api(`/tenant/${props.tenantId}/workspace/team/${id}`,{method:'DELETE'});await loadTeam()}catch(e:any){error.value=e.message}}
async function copySetup(){if(!setupUrl.value)return;await navigator.clipboard.writeText(setupUrl.value);copied.value=true;setTimeout(()=>copied.value=false,1800)}
const planName=(p:any)=>p?.name?.[props.locale]||p?.name?.de||p?.code;
</script>
<template><section class="mw-stack"><header class="mw-page-head"><div><p class="mw-kicker">LOOKDO APP</p><h1>{{t(section==='more'?'more':section)}}</h1></div></header><p v-if="error" class="mw-error">{{error}}</p>
<div v-if="section==='more'" class="mw-more-grid"><button v-for="x in moreItems" :key="x[0]" @click="emit('navigate',x[0])"><LineIcon :name="x[1]"/><b>{{t(x[0])}}</b></button><a :href="account.platform_url" target="_blank"><LineIcon name="external"/><b>{{t('openApp')}}</b></a></div>
<form v-if="section==='business'" class="mw-panel mw-form" @submit.prevent="saveProfile"><h2>{{t('business')}}</h2><label>{{t('title')}}<input v-model="profile.name" required></label><label>{{t('contact')}}<input v-model="profile.contact_name"></label><label>{{t('email')}}<input v-model="profile.email" type="email"></label><label>{{t('phone')}}<input v-model="profile.phone"></label><label>{{t('city')}}<input v-model="profile.city"></label><label>{{t('street')}}<input v-model="profile.street"></label><label>{{t('postalCode')}}<input v-model="profile.postal_code"></label><button class="mw-primary" :disabled="busy">{{t('save')}}</button></form>
<form v-if="section==='settings'" class="mw-panel mw-form" @submit.prevent="saveProfile"><h2>{{t('settings')}}</h2><label>{{t('languages')}}<select v-model="profile.locale"><option value="de">Deutsch</option><option value="en">English</option><option value="ru">Русский</option><option value="uk">Українська</option></select></label><label>{{t('primaryColor')}}<input v-model="profile.primary_color" type="color"></label><label>{{t('secondaryColor')}}<input v-model="profile.secondary_color" type="color"></label><fieldset><legend>{{t('notifications')}}</legend><p>{{t('notificationIntro')}}</p><label v-if="hasPush" class="mw-check"><input v-model="profile.notification_preferences.push" type="checkbox">{{t('push')}}</label><p v-if="pushStatus" class="mw-notice">{{pushStatus}}</p><label v-if="hasSms" class="mw-check"><input v-model="profile.notification_preferences.sms" type="checkbox">{{t('sms')}}</label><label class="mw-check"><input v-model="profile.notification_preferences.email" type="checkbox">{{t('emailChannel')}}</label></fieldset><button class="mw-primary" :disabled="busy">{{t('save')}}</button></form>
<div v-if="section==='team'" class="mw-two"><article class="mw-panel"><header><div><h2>{{t('team')}}</h2><p>{{t('teamUsage')}}: {{team.members.length}} / {{team.limit}}</p></div></header><div v-for="entry in team.members" :key="entry.id" class="mw-service-row"><span><b>{{entry.name}}</b><small>{{entry.email}} · {{t(entry.role)}}</small></span><button v-if="team.can_manage&&entry.role!=='owner'" class="mw-danger-link" @click="removeMember(entry.id)">{{t('removeMember')}}</button></div></article><form v-if="team.can_manage" class="mw-panel mw-form" @submit.prevent="addMember"><h2>{{t('addMember')}}</h2><label>{{t('name')}}<input v-model="member.name" required></label><label>{{t('email')}}<input v-model="member.email" type="email" required></label><label>{{t('role')}}<select v-model="member.role"><option value="staff">{{t('staff')}}</option><option value="manager">{{t('manager')}}</option></select></label><button class="mw-primary" :disabled="busy||team.members.length>=team.limit">{{t('add')}}</button><div v-if="setupUrl" class="mw-setup-link"><b>{{t('setupLink')}}</b><input :value="setupUrl" readonly><button type="button" class="mw-secondary" @click="copySetup">{{copied?t('copied'):t('copyLink')}}</button></div></form></div>
<div v-if="section==='domain'" class="mw-panel"><h2>{{t('domain')}}</h2><template v-if="hasDomain"><article v-for="d in account.tenant.domains" :key="d.id" class="mw-service-row"><span><b>{{d.domain}}</b><small>{{d.status}} · SSL {{d.ssl_status}}</small></span><em>{{d.is_primary?t('primary'):''}}</em></article><form class="mw-inline" @submit.prevent="addDomain"><input v-model="domain" placeholder="example.de" required><button class="mw-primary">{{t('add')}}</button></form></template><p v-else class="mw-warning">{{t('domainUnavailable')}}</p></div>
<div v-if="section==='billing'" class="mw-stack"><article class="mw-panel"><p class="mw-kicker">{{t('billing')}}</p><h2>{{planName(account.tenant.current_subscription?.plan)||'—'}}</h2><p>{{t(account.access.state)}} · {{account.access.days_remaining||0}} {{t('days')}}</p><div class="mw-inline"><select v-model="currency"><option>EUR</option><option>RUB</option><option>UAH</option></select><select v-model="cycle"><option value="monthly">{{t('monthly')}}</option><option value="yearly">{{t('yearly')}}</option></select></div></article><div class="mw-plan-grid"><article v-for="plan in plans" :key="plan.id"><img v-if="plan.image_url" :src="plan.image_url"><h2>{{planName(plan)}}</h2><p>{{plan.description?.[locale]||plan.description?.de}}</p><button class="mw-primary" @click="checkout(plan.id)">{{t('billing')}}</button></article></div></div>
</section></template>
